### ISSUE TITLE
Consider using NVM

### ISSUE THREAD

**Issue by ryantfowler** [davidalger/warden#10]
The version of Node that ships with this solution is set at v6, which is outdated, but is expected due to use of Centos and no external source repo for Node.js. With the use of something like NVM ( https://github.com/nvm-sh/nvm ), then someone could pass in an environment variable to set the version for their specific project. This would be the same as the current behavior with PHP/Mariadb/Traefic/etc.

For instance, if someone wished to use Mage2tv's cache clean tool, it requires at least Node.js v8.

**Comment by davidalger** [comment]
@ryantfowler Thanks for the suggestion! See the commits linked above for what's been done to support this. Updated base images now include `n` to facilitate installing different node versions, with NodeJS 10 installed by default. There is an `NODE_VERSION` setting in Warden 0.1.8 which, if set in the `.env` file on the project like this:

```
NODE_VERSION=12
```
…will cause the container startup script to call `n install 12` to enforce the desired version of Node for the project.
