### ISSUE TITLE
Can't get Blackfire to work

### ISSUE THREAD

**Issue by erfanimani** [davidalger/warden#104]
I followed the docs here: https://docs.warden.dev/configuration/blackfire.html

Added my keys, enabled WARDEN_BLACKFIRE and ran `warden env down && warden env up`.

I'm getting the following error when using Blackfire's extension: 

> "Are you authorized to profile this page? Probe not found, invalid signature or Varnish related issue . Troubleshooting?"

In the logs (warden env up output), I'm seeing php-blackfire_1 is correctly being hit and returning a 200, so I'm unsure how to debug..

```
php-blackfire_1    | 172.24.0.5 -  21/Feb/2020:01:16:46 +0000 "GET /index.php" 200
nginx_1            | 172.24.0.11 - - [21/Feb/2020:01:16:46 +0000] "GET / HTTP/1.1" 200 6513 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" "172.21.0.1, 172.21.0.3"
```

**Comment by vbuck** [comment]
I had the same problem. When did you try to configure your keys? Documentation just changed this week to omit quotes from the values. There is an issue with how docker-compose expands variables, such that you can’t enclose their values in quotes.

    BLACKFIRE_CLIENT_ID=“XXXX”

Should be

    BLACKFIRE_CLIENT_ID=XXXX

After this change, I rebuilt my container. This resolved the issue for me.

**Comment by erfanimani** [comment]
That was it! Thanks. Simple fix :)
