### ISSUE TITLE
 [Question] How to extract php-fpm Dockerfile, add new customization and use it? 

### ISSUE THREAD

**Issue by hoanglan87** [davidalger/warden#106]
Like title, I need to add ioncube into php-fpm docker but I can't find a way to do that properly, can you please help?

**Comment by davidalger** [comment]
@hoanglan87 The builds for all images used by Warden can be found here:
https://github.com/davidalger/warden/tree/develop/images

IonCube is included in all the PHP versions except for PHP 7.3 as the guy maintaining the IUS RPMs has decided to stop packing ioncube into the RPMs: https://github.com/iusrepo/wishlist/issues/248

I have not had the time to pivot that away from using IUS to downloading the loader and installing it in similar fashion to what has been done with Source Gaurdian (this Dockerfile is the base for all FPM images used by Warden):
https://github.com/davidalger/warden/blob/develop/images/php-fpm/Dockerfile#L36-L53

So there are probably two ways to go about this:

a) You could submit a PR that downloads ioncube loaders similar to the Source Gaurdian loader is downloaded (see dockerfile above)

b) Some vendors such as Unirgy offer Source Guardian encoded versions of their extensions for recent Magento and PHP versions. If the extensions you are using are available using Source Gaurdian, you could replace the IonCube version with one encoded using SG (this of course has implications on changing deployed infrastructure if the site is already live)

**Comment by hoanglan87** [comment]
hi @davidalger,
Thank you
 Where should I put that Dockerfile so warden can use it? I suppose I can just add a build step to include ioncube into the Dockerfile

**Comment by hoanglan87** [comment]
hi @davidalger I have created a pull request for adding ioncube for php 7.3
https://github.com/davidalger/warden/pull/109
