### ISSUE TITLE
Introduce Vault (safe place for credentials) as a global service

### ISSUE THREAD

**Issue by lbajsarowicz** [davidalger/warden#108]
## Why?

I'd love to introduce single service that handles all our credentials to different services and repositories (Composer keys, Sandobx API keys etc).

## What?

I know Vault: https://www.vaultproject.io/ from Hashicorp, which has Docker service too: https://hub.docker.com/_/vault

## How?

Add global service next to portainer etc.
For example: `vault.warden.test`

**Comment by navarr** [comment]
Does vault allow for the same path for multiple values?  E.g. Having different Vertex trusted ids for MFTF testing in different projects?
