### ISSUE TITLE
Add ImageMagick to base php container

### ISSUE THREAD

**Issue by chris-brabender** [davidalger/warden#114]
Can we add ImageMagick to the base Magento 2 PHP container so we can use this as an option to test things work as expected?

Magento seem to be pushing this as their preferred option more these days.

**Comment by davidalger** [comment]
Hi @chris-brabender. Thanks for the suggestion. I'm honestly not sure what you mean by Magento pushing this as a preferred option (I haven't seen it, and it's not listed in system requirements either), but I wanted to run a build before/after `pecl-imagemagick` is included to find out what the size impact of will be as I suspected it'd be a big one given the libraries Image Magick would require:

Sizes from fresh build of [base PHP 7.3 images](https://github.com/davidalger/docker-images-php):
```
$ docker image ls | grep davidalger/php
davidalger/php                 7.3-fpm-loaders          d07909ad6990        13 seconds ago      499MB
davidalger/php                 7.3-fpm                  816d366d567d        22 seconds ago      498MB
davidalger/php                 7.3-loaders              7a82fe88353a        44 seconds ago      469MB
davidalger/php                 7.3                      2f9592a65e4b        51 seconds ago      468MB
```

Sizes of PHP 7.3 base image build including the pecl-imagemagick extension:
```
$ docker image ls | grep davidalger/php
davidalger/php                 7.3-fpm-loaders          f52521743490        23 minutes ago      604MB
davidalger/php                 7.3-fpm                  4bd4862b017e        23 minutes ago      602MB
davidalger/php                 7.3-loaders              7dbb11010211        24 minutes ago      573MB
davidalger/php                 7.3                      88df61cb9e4d        24 minutes ago      572MB
```

Estimated impact: 105 MB increase in base image size. I'm hesitating on this one due to the size, but it IS something Magento natively supports using OOTB so I will likely go ahead and add it.

**Comment by chris-brabender** [comment]
Thanks for looking at it! 100mb+ is a decent addition to the container just for image processing but we are getting a lot of feedback from magento cloud support that we should switch to imagemagick over GD2 for performance reasons.

**Comment by davidalger** [comment]
Added this into the base PHP images, then forced a rebuild of the Warden FPM images. The extension shows up in PHP output:
```
$ warden shell -c 'php -m | grep imagick'
imagick
```

Noting for reference (since you can't do it via admin when in production mode) Magento can be configured to use ImageMagick rather than GD2 via the following:

```
bin/magento config:set dev/image/default_adapter IMAGEMAGICK
```

**Comment by davidalger** [comment]
Finally had the time to satisfy my curiosity and run a little test. It would seem that (at least in some cases) GD is actually quicker than ImageMagick. My test involved setting the adapter, then clearing the image cache and requesting a thumbnail from the default Magento sampledata set.

```
www-data@m2sandbox-php-fpm:/var/www/html$ bin/magento config:set --lock-env dev/image/default_adapter GD2
Value was saved in app/etc/env.php and locked.
www-data@m2sandbox-php-fpm:/var/www/html$ rm -rf pub/media/catalog/product/cache
www-data@m2sandbox-php-fpm:/var/www/html$ time curl -s https://app.m2sandbox.test/media/catalog/product/cache/d1d51fdffa2660b2ffaffe170a419f3c/m/h/mh07-gray_main_2.jpg >/dev/null

real	0m1.819s
user	0m0.028s
sys	0m0.128s
www-data@m2sandbox-php-fpm:/var/www/html$ rm -rf pub/media/catalog/product/cache
www-data@m2sandbox-php-fpm:/var/www/html$ time curl -s https://app.m2sandbox.test/media/catalog/product/cache/d1d51fdffa2660b2ffaffe170a419f3c/m/h/mh07-gray_main_2.jpg >/dev/null

real	0m1.586s
user	0m0.034s
sys	0m0.123s
www-data@m2sandbox-php-fpm:/var/www/html$ rm -rf pub/media/catalog/product/cache
www-data@m2sandbox-php-fpm:/var/www/html$ time curl -s https://app.m2sandbox.test/media/catalog/product/cache/d1d51fdffa2660b2ffaffe170a419f3c/m/h/mh07-gray_main_2.jpg >/dev/null

real	0m1.541s
user	0m0.031s
sys	0m0.123s
www-data@m2sandbox-php-fpm:/var/www/html$ bin/magento config:set --lock-env dev/image/default_adapter IMAGEMAGICK
Value was saved in app/etc/env.php and locked.
www-data@m2sandbox-php-fpm:/var/www/html$ rm -rf pub/media/catalog/product/cache
www-data@m2sandbox-php-fpm:/var/www/html$ time curl -s https://app.m2sandbox.test/media/catalog/product/cache/d1d51fdffa2660b2ffaffe170a419f3c/m/h/mh07-gray_main_2.jpg >/dev/null

real	0m2.486s
user	0m0.042s
sys	0m0.118s
www-data@m2sandbox-php-fpm:/var/www/html$ rm -rf pub/media/catalog/product/cache
www-data@m2sandbox-php-fpm:/var/www/html$ time curl -s https://app.m2sandbox.test/media/catalog/product/cache/d1d51fdffa2660b2ffaffe170a419f3c/m/h/mh07-gray_main_2.jpg >/dev/null

real	0m2.339s
user	0m0.037s
sys	0m0.111s
www-data@m2sandbox-php-fpm:/var/www/html$ rm -rf pub/media/catalog/product/cache
www-data@m2sandbox-php-fpm:/var/www/html$ time curl -s https://app.m2sandbox.test/media/catalog/product/cache/d1d51fdffa2660b2ffaffe170a419f3c/m/h/mh07-gray_main_2.jpg >/dev/null

real	0m2.205s
user	0m0.038s
sys	0m0.106s
```

Average with Image Magick was 2.34 seconds.
Average with GD2 was 1.65 seconds, or about 700 ms faster than when ImageMagick was used.
