### ISSUE TITLE
Feature Request: Plugin support

### ISSUE THREAD

**Issue by lbajsarowicz** [davidalger/warden#120]
I'd love to have possibility of creating my own `warden env` commands like `warden env-flush` or `warden env-reinit` with files located in my `~/.warden/` directory.

This way I'm able to adjust the system exactly to my needs.

Also that would be great to have an option for adding my own environment variables like
`M2COACH_FEATURE=1` and then create `m2coach.feature` that is included into `warden env` generation.

**Comment by davidalger** [comment]
Closely related to #64; specifically the idea outlined in this comment: https://github.com/davidalger/warden/pull/64#issuecomment-573112736
