### ISSUE TITLE
Errors in multiple domains configuration

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#133]
Following the instructions to setup a multiple domains for my projects, I display the error:

WARNING: The WARDEN_ENV_NAME variable is not set. Defaulting to a blank string.
WARNING: The TRAEFIK_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The WARDEN_ENV_TYPE variable is not set. Defaulting to a blank string.

ERROR: for php-fpm  Cannot create container for service php-fpm: bad format for add-host

I created the .warden/warden-env.yml file based on the example here
https://docs.warden.dev/configuration/multipledomains.html

**Comment by davidalger** [comment]
What does your `.env` file at your project rool look like? Each of the variables referenced in the above should be defined in the `.env`. Sounds like something got messed up in there. 

If nothing in `.env` stands out, could you let me know what versions of Docker, Docker Compose (this is where the warnings above are coming from), Warden, etc are you using here?

**Comment by gfilice** [comment]
This is the .env file:
WARDEN_ENV_NAME=XXXXXXXX
WARDEN_ENV_TYPE=magento2
WARDEN_WEB_ROOT=/

TRAEFIK_DOMAIN=XXXXXXXX.test
TRAEFIK_SUBDOMAIN=app

BYPASS_VARNISH=false

ELASTICSEARCH_VERSION=6.8
MARIADB_VERSION=10.3
NODE_VERSION=10
PHP_VERSION=7.3
RABBITMQ_VERSION=3.7
REDIS_VERSION=5.0
VARNISH_VERSION=6.0

WARDEN_SELENIUM=0
WARDEN_SELENIUM_DEBUG=0
WARDEN_BLACKFIRE=0
                    
You can see that the variables are defined.
I'm using warden 0.3.1, Docker version 18.09.3, build 774a1f4, docker-compose version 1.21.0, build unknown

**Comment by gfilice** [comment]
The warden/warden-env.yml file now works fine, after I updated the docker-compose to 1.25.4 version.
