### ISSUE TITLE
[Question] Access to Db container using Mysql Client

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#134]
How access to different Db containers using a client like Mysql Workbench?
I  can do it using the container ip address, but it's dynamic so you have to change it every time.

**Comment by lbajsarowicz** [comment]
Have you tried with documentation? https://docs.warden.dev/configuration/database.html

**Comment by gfilice** [comment]
Yes, thank you.
I'm trying but I can't connect (using Mysql Workbench, Phpstorm or TablePlus).
I can connect witt ssh using terminal ssh user@tunnel.warden.test.

**Comment by lbajsarowicz** [comment]
You can set up a tunnel with SSH:
```
ssh -N -L localhost:3306:magento2_db_1:3306 tunnel.warden.test
```

**Comment by gfilice** [comment]
It works now!!! I've just setup a tunnel via SSH following your indication @lbajsarowicz .
Thanks.

**Comment by Elamurugan-Nallathambi** [comment]
@lbajsarowicz I am trying to do the ssh tunnel to expose the container DB service to localhost to run another tool with warden DB service. 

Ran This
`ssh -N -L localhost:3306:m2_db_1:3306 tunnel.warden.test`

When I try to connect to the DB using 
`mysql -hlocalhost -uroot -pmagento`
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

The containers are running and M2 works ok from container or from  phpstorm/DataGrip I can able to connect. Not able to get the container DB service to localhost via tunneling working.

Ports are listening
> lsof -i tcp:3306
> COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> ssh     92975  ela    5u  IPv6 0x789e7061eaa20b2d      0t0  TCP localhost:mysql (LISTEN)
> ssh     92975  ela    6u  IPv4 0x789e706208cec31d      0t0  TCP localhost:mysql (LISTEN)


**System**
- OS : MacOS Catalina 10.15.4 (19E287)
- Warden : 0.4.1

I am missing something and not sure how to get this working.

**Comment by lbajsarowicz** [comment]
You need to run `127.0.0.1` connection, not `localhost`. Localhost uses socket, IP uses network layer.

**Comment by Elamurugan-Nallathambi** [comment]
Thank you so much @lbajsarowicz, this worked.
