### ISSUE TITLE
[Question] Need to edit hosts file in Ubuntu

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#135]
To reach every .test istance I need to manually edit the hosts file (by adding the relation 127.0.0.1 app.xxx.test). 
How to set up dnsmask to not have to edit this file?

**Comment by twolaver** [comment]
I had issues getting Ubuntu 19.10 to resolve xxx.test domains with the dnsmask docker container as well.

What I settled on was disabling systemd-resolved and using the dnsmask docker container (I always have to have warden up). 

Probably not the best way, but everything is working for me now.

@see https://github.com/jpillora/docker-dnsmasq/issues/21

**Comment by KyleMoran138** [comment]
Point your DNS configuration to your localhost ip (127.0.0.1) + whatever you were using after it.
Example: my DNS ip was "192.168.1.1" after modifications it now looks like "127.0.0.1,192.168.1.1"
Then reset your connection and everything should resolve through warden.

**Comment by davidalger** [comment]
Closing this issue for now due to inactivity.
