### ISSUE TITLE
Issue with elasticsearch cluster after update to 2.4 in first install

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#151]
Got this issue when i try to reinstall magento instance in local. Used github codebase in 2.4-develop branch
Everything set but when magento install to elastic setup step. Stop instantly and raise error
"Elastic Search Give error No alive nodes found in your cluster"
Any idea how to solve this ? This problem never happen before

Used warden 0.4.4. Also try down all network and container and up again but not help

**Comment by mrtuvn** [comment]
Close this cause not related with warden

**Comment by moElwan** [comment]
@mrtuvn What was the issue please? had the same 
in my case `warden env down && warden env pull && warden env up -d` helped
