### ISSUE TITLE
Warden 0.5.1 doesn't start M2 services

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#158]
Platform:
- OS: macOS Catalina 10.15.4 (19E287)
- Docker Desktop: 2.3.03
![Screen Shot 2020-06-01 at 2 21 33 PM](https://user-images.githubusercontent.com/54947876/83440602-33e1ee80-a413-11ea-8f86-2096f961fa27.png)
- mutagen version: 0.11.4
- warden version: 0.5.1

Steps to Reproduce:
- Create & start the services from new M2 environment
- `warden env-init w2 magento2`
- `warden sign-certificate w2.test`
- `warden env up -d` [This have problem with mutagen]

`Connecting traefik to w2_default network
Connecting tunnel to w2_default network
Starting w2_elasticsearch_1 ... 
Starting w2_rabbitmq_1      ... 
w2_redis_1 is up-to-date
Starting w2_rabbitmq_1      ... done
Starting w2_db_1            ... done
Starting w2_elasticsearch_1 ... done
w2_nginx_1 is up-to-date
w2_php-debug_1 is up-to-date
Starting w2_varnish_1       ... done
Installing agent...                                                             
Error: create failed: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to install agent: unable to invoke agent installation: exit status 1

ERROR: Command `mutagen sync create -c "${WARDEN_DIR}/environments/${WARDEN_ENV_TYPE}/${WARDEN_ENV_TYPE}.mutagen.yml" --label "warden-sync=${WARDEN_ENV_NAME}" --ignore "${WARDEN_SYNC_IGNORE:-}" "${WARDEN_ENV_PATH}${WARDEN_WEB_ROOT:-}" "docker://$(warden env ps -q php-fpm)/var/www/html"` on line 43 failed with exit code 1`

![Screen Shot 2020-06-01 at 2 28 53 PM](https://user-images.githubusercontent.com/54947876/83441252-38f36d80-a414-11ea-9a7e-fba2233ed7f3.png)

**Comment by Elamurugan-Nallathambi** [comment]
I no longer have this issue. This is what I did and that seems resolved this for me.
Removed warden completely, installed again and followed recreating or re-initing environment file for existing M2 project and then now my local warden toolchain based dev environment works fine.

**Comment by fballiano** [comment]
same problem, no solution at the moment

**Comment by davidalger** [comment]
@fballiano The error in the OPs post indicated something is stuck with Mutagen. If that's the error you're getting, I'd try the solution I posted over here on an older issue: https://github.com/davidalger/warden/issues/26#issuecomment-546543118 If that doesn't work and all else fails, reset Docker Desktop, kill any mutagen processes and then spin things back up.

**Comment by fballiano** [comment]
sadly it didn't work:

```
fab@MacBook-Pro-3 ~/P/prezzemolo (devel) [1]> warden sync start
Installing agent...                                                             
Error: create failed: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to install agent: unable to invoke agent installation: exit status 1
ERROR: Command `mutagen sync create -c "${MUTAGEN_SYNC_FILE}" --label "warden-sync=${WARDEN_ENV_NAME}" --ignore "${WARDEN_SYNC_IGNORE:-}" "${WARDEN_ENV_PATH}${WARDEN_WEB_ROOT:-}" "docker://$(warden env ps -q php-fpm)/var/www/html"` at /usr/local/Cellar/warden/0.10.1/commands/sync.cmd:45 failed with exit code 1

```
