### ISSUE TITLE
See list of running warden environments

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#16]
Every time I run `warden down` it fails with the following output:
```
Leto:warden vinai$ warden down
Stopping traefik   ... done
Stopping tunnel    ... done
Stopping portainer ... done
Stopping dnsmasq   ... done
Removing traefik   ... done
Removing tunnel    ... done
Removing portainer ... done
Removing dnsmasq   ... done
Removing network warden
ERROR: error while removing network: network warden id 83313fb38e7e4594bb91dcf81c2f73282235196a52c9cc3e6312dc6df4145d0d has active endpoints

ERROR: Command `docker-compose -p warden -f docker/docker-compose.yml down "${WARDEN_PARAMS[@]}" "$@"` on line 5 failed with exit code 1
```

I'm just starting to dig into warden so I might be overlooking something obvious, but at the moment this is the first obstacle, so I thought I'd report.

**Comment by Vinai** [comment]
Okay, I got it now - the problem is I left an initial test warden environment in up state.
Is there a way to list the current warden environments and maybe what directories they are bound to?

**Comment by ryantfowler** [comment]
@Vinai you can run `https://portainer.warden.test` to see a list of running environments, or what Portainer calls "stacks" ... but it will also show every other docker container running on your system as well. There's also `https://traefik.warden.test` which will show you a list of front/backends ... it's not as concise as a list of named projects, but it's specific to what's in warden.

**Comment by Vinai** [comment]
Thanks!
