### ISSUE TITLE
Xdebug Profile and Trace Requests Should Route to php-debug Container

### ISSUE THREAD

**Issue by davidalger** [davidalger/warden#163]
Xdebug has three different cookies which can be used to trigger various behaviour:

* XDEBUG_SESSION ([step-by-step debugger](https://xdebug.org/docs/remote))
* XDEBUG_PROFILE ([request profiler](https://xdebug.org/docs/profiler))
* XDEBUG_TRACE ([execution trace](https://xdebug.org/docs/execution_trace))

Support for routing Xdebug step-by-step debug sessions to the `php-debug` container based on the presence of the XDEBUG_SESSION cookie has existed from the early days of Warden.

As a developer debugging application performance issues, I'd like to be able to generate request profiles for analysis with tools capable of parsing the Cachegrind formatted output, and generating traces to analyze a complete log of all function calls executed during a request. 

Functionally this should allow for Xdebug Helper to be used to set not just the cookie for debugging, but also to set the profile and trace cookies and have requests route and active the appropriate Xdebug functionality.

![Screen-Shot-2020-06-15-15-10-14 01-P4lteeCykYkE](https://user-images.githubusercontent.com/658281/84702612-8b588200-af1c-11ea-864c-b42e0220665c.png)

The way Xdebug Helper works, only one of the 3 cookies for Xdebug will be set at any given time. Any 1 of 3, which means that currently traces and profiles do not even route to the php-debug container apart from setting a cookie manually in the browser dev tools.

**Comment by davidalger** [comment]
This has been implemented in the two tagged commits above which amend the `nginx` and `php-fpm:*-debug` images. As this did not require any changes to the environment definitions, only altering the image builds, simply ensure the latest images are pulled and running by executing `warden env pull && warden env up -d` in order to use tracing or profiling functionality.

It is recommended to put the local site into production mode before running profiles and traces in order to get closer-to-production information as well as avoid the profiling of image requests which is generally undesired: `bin/magento deploy:mode:set production`

Example of generated cachegrind files from hitting first the home page followed by the customer sign-in page on a test 2.4.0-alpha10 instance:
```
davidalger:/sites/m2template (develop) $ warden debug
www-data@exampleproject-php-debug:02:49 PM:/var/www/html$ ls -lh /tmp/cachegrind.out.*
-rw-r--r-- 1 www-data www-data 15M Jun 16 14:49 /tmp/cachegrind.out.1592318950._var_www_html_pub_index_php__
-rw-rw-r-- 1 www-data www-data 12K Jun 16 14:49 /tmp/cachegrind.out.1592318952._var_www_html_vendor_magento_framework_Session_SessionManager_php__
-rw-r--r-- 1 www-data www-data 15M Jun 16 14:49 /tmp/cachegrind.out.1592318955._var_www_html_pub_index_php__customer_account_login_referer_aHR0cHM6Ly9hcHAuZXhhbXBsZXByb2plY3QudGVzdC8%2C_
-rw-rw-r-- 1 www-data www-data 12K Jun 16 14:49 /tmp/cachegrind.out.1592318957._var_www_html_vendor_magento_framework_Session_SessionManager_php__customer_account_login_referer_aHR0cHM6Ly9hcHAuZXhhbXBsZXByb2plY3QudGVzdC8%2C_
```

The following is an example of the files which would show up when running a trace of the home page:
```
davidalger:/sites/m2template (develop) $ warden debug
www-data@exampleproject-php-debug:02:50 PM:/var/www/html$ ls -lh /tmp/trace.*
-rw-r--r-- 1 www-data www-data 41M Jun 16 14:50 /tmp/trace.1592319024._var_www_html_pub_index_php__.xt
-rw-rw-r-- 1 www-data www-data 466 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_colinmollenhour_credis_Client_php__.05c71c.xt
-rw-rw-r-- 1 www-data www-data 204 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_colinmollenhour_credis_Client_php__.0aa756.xt
-rw-rw-r-- 1 www-data www-data 524 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_colinmollenhour_credis_Client_php__.xt
-rw-rw-r-- 1 www-data www-data 192 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_magento_framework_DB_Adapter_Pdo_Mysql_php__.xt
-rw-rw-r-- 1 www-data www-data 635 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_magento_framework_Registry_php__.xt
-rw-rw-r-- 1 www-data www-data 19K Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_magento_framework_Session_SessionManager_php__.xt
-rw-rw-r-- 1 www-data www-data 730 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_magento_framework_View_Layout_php__.0ccaf7.xt
-rw-rw-r-- 1 www-data www-data 730 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_magento_framework_View_Layout_php__.xt
-rw-rw-r-- 1 www-data www-data 198 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_magento_framework_View_Model_Layout_Merge_php__.xt
-rw-rw-r-- 1 www-data www-data 486 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_monolog_monolog_src_Monolog_Handler_AbstractHandler_php__.00b54e.xt
-rw-rw-r-- 1 www-data www-data 567 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_monolog_monolog_src_Monolog_Handler_AbstractHandler_php__.03a917.xt
-rw-rw-r-- 1 www-data www-data 476 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_monolog_monolog_src_Monolog_Handler_AbstractHandler_php__.06f5b4.xt
-rw-rw-r-- 1 www-data www-data 485 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_monolog_monolog_src_Monolog_Handler_AbstractHandler_php__.0823b3.xt
-rw-rw-r-- 1 www-data www-data 482 Jun 16 14:50 /tmp/trace.1592319025._var_www_html_vendor_monolog_monolog_src_Monolog_Handler_AbstractHandler_php__.xt
```

Trace files can be easily viewed via `less` on the CLI, but currently the easiest way to retrieve cachegrind files for viewing from a developer workstation is to simply move them into /var/www/html or pub/media (`mv /tmp/cachegrind.out.* pub/media/`) where they will be synchronized from the container to the host machine for parsing with tools such as [Profile Viewer](https://apps.apple.com/us/app/profiling-viewer/id1079647046?mt=12) or [MCG](https://apps.apple.com/us/app/mcg/id799178412?mt=12) on Mac OS or via similar tools available for Linux (there are some listed out [here](https://xdebug.org/docs/profiler).

Some example profiles in Profile Viewer:
![Screen-Shot-2020-06-16-09-57-57 55-kzv8XxuXA2BV](https://user-images.githubusercontent.com/658281/84791192-eab7a000-afb7-11ea-913c-028bc3b92939.png)
![Screen-Shot-2020-06-16-10-03-12 07-3VCluSRx7Nl1](https://user-images.githubusercontent.com/658281/84791726-a082ee80-afb8-11ea-8850-8b1e9b7a7c57.png)

**Comment by MagePsycho** [comment]
@davidalger How to map the files to the host so that we can see the source code?

![Image](https://github.com/user-attachments/assets/617001ba-b153-4841-8eca-ee8db427fe45)

**Comment by bap14** [comment]
@MagePsycho Do you have path mappings set up properly?

![Image](https://github.com/user-attachments/assets/23e27e5b-a74f-4b9a-969a-5c95cbe76658)
