### ISSUE TITLE
Laravel 403 Forbidden  nginx/1.16.1

### ISSUE THREAD

**Issue by LucasMali** [davidalger/warden#167]
Hello,

Running Warden version 0.5.2 and trying to get laravel working. When I go to the shell the root is empty and the app.laravel.test set is giving me the following:

`403 Forbidden

nginx/1.16.1`

What steps am I missing to finalize the installation of laravel?

**Comment by davidalger** [comment]
@LucasMali I can't help out if I don't know what you have tried. A 403 could simply mean there are no files inside the container, or it could mean the permissions prohibit it from being accessed. Going to close this as having insufficient detail to proceed. Feel free to re-open if you can provide a reproducible test case.
