### ISSUE TITLE
Admin login impossible when using url rewrites

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#17]
After running `setup:install` with `--use-rewrites=1` or when switching `web/seo/use_rewrites` to `1` in the admin or using the cli, all admin sessions redirect to the login screen and all further login attempts fail without an error message.

**Comment by davidalger** [comment]
@Vinai I can unfortunately not reproduce this one. Each of the M2 projects I've been working on lately have URL rewrites enabled and this hasn't been an issue with the container / nginx configs in place. Also ran through each of the steps recorded here: https://github.com/davidalger/warden#initializing-an-environment but including `--use-rewrites=1` and the admin panel loaded, allowed me to sign-in, and functioned as expected with URL Rewrites both enabled and disabled.

Is this a clean Magento 2 installation you're experiencing this with or might there be some other store configuration surrounding cookies, X-Forwarded-Proto headers, etc involved?

**Comment by Vinai** [comment]
I'm using a clean, fresh M2 instance following the instructions on the warden github readme.

**Comment by davidalger** [comment]
Possibly related #42
