### ISSUE TITLE
is not writable

### ISSUE THREAD

**Issue by itsazzad** [davidalger/warden#171]
```
Changed current directory to /home/www-data/.composer
Cannot create cache directory /home/www-data/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/www-data/.composer/cache/files/, or directory is not writable. Proceeding without cache

                                               
  [RuntimeException]                           
  The file "./composer.json" is not writable.  
```

```
www-data@exampleproject-php-fpm:11:56 AM:/var/www/html$ ls -al /home/www-data          
total 32
drwxr-xr-x 1 www-data www-data 4096 Jun 25 11:41 .
drwxr-xr-x 1 root     root     4096 Jun 23 11:55 ..
-rw-r--r-- 1 www-data www-data   18 Apr  1 02:17 .bash_logout
-rw-r--r-- 1 www-data www-data  193 Apr  1 02:17 .bash_profile
-rw-r--r-- 1 www-data www-data  231 Apr  1 02:17 .bashrc
drwxr-xr-x 4      501 games    4096 Jun 25 06:12 .composer
drwx------ 5 www-data www-data 4096 Jun 25 11:41 .mutagen
```

**Comment by davidalger** [comment]
The best way to solve this is to either use `sudo chown ...` inside the container to fix the perms of that directory within the docker context, or to use chown on the host. Depends on if you're using macOS or Linux (I'm assuming macOS based on the 501 uid, which is the default uid for the first user account on macOS). This directory is mounted from your host machine ~/.composer directory, and Docker Desktop should normally automatically take care of the perms here. Feel free to re-open with more detail if using chown to fix ownership doesn't resolve it for you, but I can't promise I'll have an immediate solution to offer as it sounds like something specific permissions wise on your workstation.
