### ISSUE TITLE
How to purge Varnish cache

### ISSUE THREAD

**Issue by jschreck** [davidalger/warden#174]
I have the http_cache_hosts config set up per documentation but

`bin/magento cache:clean`

Does nothing to purge. 

Running varnishlog reveals that magento never even contacts varnish.

I've checked the ACL and the docker network is fine. Requests are getting through when run from `php-fpm` with curl like they're supposed to.

Ideas?

**Comment by davidalger** [comment]
Is it possible the `full_page` cache type is not enabled? As much as it doesn't make sense, Magento doesn't send PURGE requests to Varnish when the FPC cache type is disabled. Just tested this on an environment I have up atm to be sure, and the varnishlog didn't report anything until I enabled the full_page type (I typically leave it off while developing, but enable as-needed for testing)

In addition to using curl to purge varnish:
```
curl -X PURGE -H 'X-Magento-Tags-Pattern: *' varnish
```

You can also flush _everything_ (even if it is missing an X-Magento-Tags header) by restarting varnish:
```
warden env restart varnish
```

**Comment by jschreck** [comment]
Holy smokes. I'm running live sites with full_page disabled when I use Varnish because I've had cache corruptions (2.3.2) so I thought when Varnish is in use full_page should be disabled. Guess not...

Thank you for your insight on this!
