### ISSUE TITLE
Varnish PURGE not allowed from php-debug

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#181]
When saving a product during a php debug session, Varnish rejects the purge:

```
*   << Request  >> 1245412
-   Begin          req 1245411 rxreq
-   Timestamp      Start: 1594135372.059978 0.000000 0.000000
-   Timestamp      Req: 1594135372.059978 0.000000 0.000000
-   ReqStart       172.26.0.11 39308 a0
-   ReqMethod      PURGE
-   ReqURL         /
-   ReqProtocol    HTTP/1.1
-   ReqHeader      X-Magento-Tags-Pattern: ((^|,)cat_p_1(,|$))
-   ReqHeader      Host: varnish
-   ReqHeader      X-Forwarded-For: 172.26.0.11
-   VCL_call       RECV
-   VCL_acl        NO_MATCH purge
-   VCL_return     synth
-   VCL_call       HASH
-   VCL_return     lookup
-   Timestamp      Process: 1594135372.060007 0.000029 0.000029
-   RespHeader     Date: Tue, 07 Jul 2020 15:22:52 GMT
-   RespHeader     Server: Varnish
-   RespHeader     X-Varnish: 1245412
-   RespProtocol   HTTP/1.1
-   RespStatus     405
-   RespReason     Method Not Allowed
-   RespReason     Method not allowed
-   VCL_call       SYNTH
-   RespHeader     Content-Type: text/html; charset=utf-8
-   RespHeader     Retry-After: 5
-   VCL_return     deliver
-   RespHeader     Content-Length: 278
-   Storage        malloc Transient
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1594135372.060122 0.000144 0.000115
-   ReqAcct        80 0 80 210 278 488
```

After some digging, this is what I came up with:

In `images/varnish/6.0/Dockerfile` and `images/varnish/4.1/Dockerfile` the ACL PURGE environment variable is set as
```
ENV ACL_PURGE_HOST  php-fpm
```

In `images/varnish/context/default.vcl` the purge ACL is set to this value:
```
acl purge {
    "${ACL_PURGE_HOST}";
}
```

It would be great if the `php-debug` host could be included in the configuration, too, if only as it would have saved me an hour debugging the issue. :)
I would be happy to open a PR, but unfortunately I don't know the syntax to include two hosts in `ACL_PURGE_HOSTS`...

**Comment by davidalger** [comment]
Since these are development focused images, I'm included to have the default in the Dockerfile simply be `0.0.0.0` which should have the effect of allowing PURGE requests from any other container on the project's docker network. Making this value incluce more than a single hostname or a single CIDR address range would require a bit of an overhaul, and you are correct, it should accept PURGE requests from php-fpm, and debug, and also from php-blackfire, etc.

As the port is not published to the host machine, there shouldn't be any issues arising from allowing PURGE from anywhere by default in the container image (this would be a potential concern if the image was being used in a production Kuberenetes Pod for example however)

**Comment by davidalger** [comment]
The varnish images have been updated to default `ACL_PURGE_HOST` to `0.0.0.0/0` resolving the inability to PURGE from php-debug container:

```
$ warden shell -c 'curl -X PURGE -H "X-Magento-Tags-Pattern: *" varnish'
<!DOCTYPE html>
<html>
  <head>
    <title>200 Purged</title>
  </head>
  <body>
    <h1>Error 200 Purged</h1>
    <p>Purged</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 2</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

```
$ warden debug -c 'curl -X PURGE -H "X-Magento-Tags-Pattern: *" varnish'
<!DOCTYPE html>
<html>
  <head>
    <title>200 Purged</title>
  </head>
  <body>
    <h1>Error 200 Purged</h1>
    <p>Purged</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 32770</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

In order for this to take effect, you'll want to pull the latest images via `warden env pull varnish` followed by `warden env up -d varnish`

Appreciate you surfacing this issue, and providing the detail around what was going on (I'm honestly surprised nobody else had encountered and reported this by now!)
