### ISSUE TITLE
Multiple DB's

### ISSUE THREAD

**Issue by jschreck** [davidalger/warden#190]
I don't understand how to connect to the MySQL db and create a second or third DB for the same project? At times I have a need to run things in separate db's or switch back and forth between two Magento DBs for the same project.

**Comment by barbanet** [comment]
@jschreck You can connect to the database using the same credentials but the user should be root. Using that user with all the other credentials/host, you will be able to have the right privileges and do that kind of operations (new db, users, permissions, etc).

Let's say you are into the php-fpm container, normally you'll execute this to connect to the database.

`mysql -u magento -p -h db magento`

And then you enter the password `magento`

Now try with:

`mysql -u root -p -h db magento`

The same password we used before.

**Comment by jschreck** [comment]
Works a treat! Thank you @barbanet !
