### ISSUE TITLE
Problem with SSH Tunnel to DB using PHPStorm

### ISSUE THREAD

**Issue by jschreck** [davidalger/warden#195]
Any idea on how to resolve this issue? Following the configuration instructions for PHPStorm on the documentation page leads to failures on the SSH tunnel:

`RSA modulus is even`

![image](https://user-images.githubusercontent.com/1825269/88235720-10803680-cc41-11ea-805f-8c355206eb7a.png)

I use some other tools like Querious, MySQL Workbench, Coda without issue. I only have this problem in PHP storm. Hope someone can help...

Here's what's in my .ssh/config regarding warden.test

```
Host *
AddKeysToAgent yes
UseKeychain yes
#ServerAliveInterval 200
#ServerAliveCountMax 3

## WARDEN START ##
Host tunnel.warden.test
HostName 127.0.0.1
User user
Port 2222
IdentityFile ~/.warden/tunnel/ssh_key
## WARDEN END ##
```

Thanks!

**Comment by navarr** [comment]
Have you tried backing up and removing ~/.ssh/known_hosts?  This error is pretty rare, but it has come up before in PhpStorm: https://youtrack.jetbrains.com/issue/WI-53392

**Comment by jschreck** [comment]
@navarr - thanks for the pointer! 

Actually, you referenced my own request at JetBrains :-) but I hadn't realized that I received a response. So I dug a little deeper and found a ~/.ssh/known_hosts2 file in there in addition to the ~/.ssh/known_hosts ... Really no idea where that came from, but removing that one cleared things up! All good to go!
