### ISSUE TITLE
ERROR: for dnsmasq  Cannot start service dnsmasq: Ports are not available: port is already allocated.

### ISSUE THREAD

**Issue by MaybachDomei** [davidalger/warden#197]
Hello,

i want to use Warden, but i get this Error.

ERROR: for dnsmasq  Cannot start service dnsmasq: Ports are not available: port is already allocated.

ERROR: for dnsmasq  Cannot start service dnsmasq: Ports are not available: port is already allocated.
ERROR: Encountered errors while bringing up the project.

Thanks for help!

**Comment by davidalger** [comment]
@MaybachDomei That error would be coming from Docker and basically means exactly what it says, some other server is is listening on the DNS port 53.

You can run the following to see what's listening on port 53:
```
sudo lsof -nP -iUDP | grep :53
```

On my system the following line shows up and is present as the dnsmasq container is running and listening on this port (this is what docker is failing to configure on your machine right now):
```
com.docke 71651     davidalger   49u  IPv4 0x471d5907ceb434ad      0t0  UDP 127.0.0.1:53
```

If you're a former user of Valet, or other Homebrew based environments, you might try checking to see if brew is running anything like dnsmasq, unbound, as an artifact of the prior environment setup: `sudo brew services list`
