### ISSUE TITLE
Documentation how to setup cron with Magento 2

### ISSUE THREAD

**Issue by gfilice71** [davidalger/warden#201]
As the latest Warden release includes the crontab package with crond running in the background, it would be useful to have a document (with examples) on how to use this feature (for ex. in Magento 2).

**Comment by davidalger** [comment]
PRs are welcome if there is really a need for this, although I fail to see the need. Crontab works as crontab does: you can either edit it by running `crontab -e` per the usual, or use the `bin/magento` CLI tool per dev docs to install the crontab offered by the application:

```
$ warden shell
www-data@exampleproject-php-fpm:/var/www/html$ bin/magento cron:install
Crontab has been generated and saved
www-data@exampleproject-php-fpm:/var/www/html$ crontab -l

#~ MAGENTO START 69dd2b02e1f3a65918182048ea4e29979a849d8942e8f53ed20a4bf10e529b36
* * * * * /usr/bin/php /var/www/html/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /var/www/html/var/log/magento.cron.log
#~ MAGENTO END 69dd2b02e1f3a65918182048ea4e29979a849d8942e8f53ed20a4bf10e529b36

```
