### ISSUE TITLE
Folder pub/media inaccessible in docker container 

### ISSUE THREAD

**Issue by sajidpatel** [davidalger/warden#207]
If I have a lot of files in pub/media on my local machine when syncing using mutagen and running warden shell, I get the problem described here:

https://superuser.com/questions/957582/ls-cannot-access-file-no-such-file-or-directory

<div class="post-text" itemprop="text">
                    
<p>Context: I am unable to access a pub/media(?) when setting up Magento 2.</p>

<p><strong>ls -lthr pub/media</strong></p>

<pre><code>ls: cannot access pub/media: No such file or directory
total 56
d?????????  ? ?    ?        ?            ? pub
drwxr-xr-x 26 user    12288 Aug 12 23:29 foo
</code></pre>

<p><strong>ls -a pub</strong></p>

<pre><code>.  ..  media
</code></pre>

<p><strong>cd</strong></p>

<pre><code>bash: cd: pub/media: No such file or directory
</code></pre>

<p><strong>touch</strong></p>

<pre><code>touch: cannot touch ‘pub/media’: File exists
</code></pre>

<p><strong>mkdir pub/media</strong></p>

<pre><code>mkdir: cannot create directory ‘pub/media’: File exists
</code></pre>

<p><strong>cat pub/media</strong></p>

<pre><code>cat: pub/media: No such file or directory
</code></pre>

<p><strong>file pub/media</strong></p>

<pre><code>media: cannot open `pub/media' (No such file or directory)
</code></pre>

<p><strong>mv pub/media pub/media-temp</strong></p>

<pre><code>mv: cannot stat ‘pub/media’: No such file or directory
</code></pre>

<hr>

<p>Furthermore, the following commands do not remove the file(?), as root or otherwise:</p>

<pre><code>rm pub/media
rm -rf pub/media
rmdir pub/media
</code></pre>

<p>One more piece of information, bash auto-completes pub/media, so bash also seems to think it is there.</p>
    </div>

Unable to run the solutions mentioned due to permissions or missing applications.

I know pub/media has been setup as a delegated mount for Magento 2 by Warden.  Is this something that would cause this issue?

Any ideas would be helpful

**Comment by davidalger** [comment]
@sajidpatel Don't have too much time at the moment to help chase something like this down, but I'd try resetting permissions and ownership on the directory. Should be able to do this via `sudo chown 755 pub/media` while inside `warden shell` or possibly from the host machine (if running on Linux). The behavior described is as would be expected when permissions of a volume mounted into a container are screwed up, and resetting them should resolve the issue. The inability to remove the `pub/media` directory would be due to it being the mount point in the FS within the container (you cannot remove a mount point that's in use).

**Comment by sajidpatel** [comment]
Hi David,

I ran the command:
sudo chmod -R 755 pub/media

It has asked for a password to run as sudo.  What is the password?

**Comment by davidalger** [comment]
@sajidpatel There should be no password requested when running sudo within the php-fpm container from the www-data user. It almost sounds like you ran the sudo command from your host machine, in which case I won't be able to help with provide a pw for you ;)
