### ISSUE TITLE
Setting up Warden in remote machine [SUPPORT_REQUEST]

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#208]
In one of the project, we have to use remote machine based development which is out of DigitialOcean servers. 
It's bare-metal ubuntu instances with docker in it. I tried setting up warden in it, not able to connect to it from local using app.m2dev.test [Added local host entry to point to m2dev.test with DO server IP]

Do I need to do any extra configurations or is this not right way to do it? [I can also setup M2 with default M2 tech stack tools separately in this instances but I like using warden docker toolchain of all different available services & tools]

**Comment by davidalger** [comment]
@Elamurugan-Nallathambi See the note regarding `TRAEFIK_LISTEN` on this docs page; by default Traefik is configured to only listen on 127.0.0.1 so you would either need to run an SSH tunnel to forward the port to localhost OR change this setting so it's listening on a publicly available address: https://docs.warden.dev/services.html

**Comment by Elamurugan-Nallathambi** [comment]
@davidalger I understand I shouldn't bother you more on this but am hitting dead end, unfortunately I do not have background understanding on dnsmasq or how traefik should be configured from a remote Ubuntu machine.

This is what I have tried.

- Registered a new DigitalOcean Ubuntu 20 droplet
- Installed docker and default required tools
- Installed warden
- When running `warden svc up` am seeing below message

```
root@ubuntu-s-2vcpu-4gb-fra1-01:/opt# warden svc up
WARNING: The WARDEN_HOME_DIR variable is not set. Defaulting to a blank string.
Starting dnsmasq   ... error
Starting portainer ...
Starting mailhog   ...
Starting tunnel    ...
Starting traefik   ...
Starting portainer ... done
Starting mailhog   ... done
Starting tunnel    ... done
Starting traefik   ... done

ERROR: for dnsmasq  Cannot start service dnsmasq: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/dnsmasq.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/9313f901b9e67ecf801680d6e5bade0749f85d9bbf3daea88b3af0eafcb58009/merged\\\" at \\\"/var/lib/docker/overlay2/9313f901b9e67ecf801680d6e5bade0749f85d9bbf3daea88b3af0eafcb58009/merged/etc/dnsmasq.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

Am not sure what I should do to resolve the dnsmasq mapping. tried modifying /etc/systemd/resolved.conf, /etc/resolv.conf but that doesnt have any impact. 

Any references will be really helpful.

**Comment by vovsky** [comment]
@Elamurugan-Nallathambi FYI: `TRAEFIK_LISTEN` variable didn't work for me on Ubuntu. So I have replaced 127.0.0.1 with 0.0.0.0 directly in /opt/warden/docker/docker-compose.yml. Then run command: `warden svc up --force`. Hope that helps

**Comment by ajzele** [comment]
@vovsky thanks for the "**_replaced 127.0.0.1 with 0.0.0.0 directly in /opt/warden/docker/docker-compose.yml_**" hint ... aparently this is still the case nearly 3 years later, in 2024 :) ... running latest windows 11, and latest brew installed warden within Ubuntu WSL.
