### ISSUE TITLE
M2 - Add instruction how to run jasmine tests

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#209]
I just tried to execute js unit tests with following instruction, but it actually failed on npm install.
https://devdocs.magento.com/guides/v2.4/test/js/jasmine.html

Do anyone tried to run them? Is there any instruction?

**Comment by complexthings** [comment]
@ihor-sviziev since you're helping me I'll help you.

First make sure you do `warden env pull` to get the latest containers, followed by `warden env up`

Next I recommend using `warden shell` and inside your container running the following command:

```bash
rm -rf node_modules/ && npm install
```

**Comment by complexthings** [comment]
Also in your `.env` file you might need to see your `NODE_VERSION=10`

**Comment by ihor-sviziev** [comment]
@complexthings here is what I see after npm install, seems like something is not correct:
![image](https://user-images.githubusercontent.com/1873745/90252231-ce18d680-de47-11ea-8bd9-16547223b1f8.png)

running `grunt spec:luma` shows also exception:
![image](https://user-images.githubusercontent.com/1873745/90252322-edafff00-de47-11ea-87c3-683318322413.png)

```Running "spec:luma" (spec) task

Running "connect:luma" (connect) task
Started connect web server on http://localhost:8000

Running "jasmine:luma" (jasmine) task
(node:192) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
/var/www/html/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

  at onClose (/var/www/html/node_modules/puppeteer/lib/Launcher.js:348:14)
  at Interface.helper.addEventListener (/var/www/html/node_modules/puppeteer/lib/Launcher.js:337:50)
  at Interface.emit (events.js:203:15)
  at Interface.close (readline.js:397:8)
  at Socket.onend (readline.js:173:10)
  at Socket.emit (events.js:203:15)
  at endReadableNT (_stream_readable.js:1145:12)
  at process._tickCallback (internal/process/next_tick.js:63:19)

(node:192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by complexthings** [comment]
@ihor-sviziev somehow it looks like you're running the wrong version of jasmine.  Your grunt-contrib-jasmine should be `"grunt-contrib-jasmine": "~1.1.0",` They switched from PhantomJS to Puppeteer in version `2.0.0`.  Also make sure you're running `node -v` and getting ~`10.22.0` 

I would suggest checking your `package-lock.json` and verifiying the version that downloaded.  If you're still having issues, I would suggest deleting your `package-lock.json`, replacing your `package.json` with this one: https://github.com/magento/magento2/blob/2.4-develop/package.json.sample, deleting `node_modules` and running `npm install` again.

**Comment by ihor-sviziev** [comment]
Basically I got it working by running following commands:
```bash
cp package.json.sample package.json
rm package-lock.json
npm install
bin/magento setup:static-content:deploy -f
grunt spec:luma
```

What confused me - after npm install i got red messages about vulnerabilities, so I thought i have to run `npm audit fix`.
![image](https://user-images.githubusercontent.com/1873745/90254793-fd314700-de4b-11ea-9c64-bae47cb45649.png)
Also during running tests I see a lot of red errors
![image](https://user-images.githubusercontent.com/1873745/90254765-ef7bc180-de4b-11ea-984f-fcabba4b8044.png)
```
     ✓ removes duplicated entries
   "utilize" method
     - stores passed string to array under localStorage's "used" namespace...>> TypeError: undefined is not a constructor (evaluating 'data.ctx.contains(node)') at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:151
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:150
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/underscore.js:150 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:149 processAdded
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:291
>> TypeError: undefined is not a constructor (evaluating 'data.ctx.contains(node)') at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:151
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:150
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/underscore.js:150 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:149 processAdded
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:291
>> TypeError: undefined is not a constructor (evaluating 'data.ctx.contains(node)') at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:151
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:150
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/underscore.js:150 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:149 processAdded
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:291
     ✓ stores passed string to array under localStorage's "used" namespace
     - removes duplicated entries...>> TypeError: undefined is not a constructor (evaluating 'data.ctx.contains(node)') at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:151
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:150
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/underscore.js:150 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:149 processAdded
>> :0 forEach
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:291
>> TypeError: undefined is not a constructor (evaluating 'data.ctx.contains(node)') at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Ui/js/lib/view/utils/dom-observer.js:151
>> :0 forEach```

**Comment by ihor-sviziev** [comment]
Interesting thing that after few re-runs - there are no red errors anymore 🤯 

also not clear how to run single file test, for instance 
```
grunt spec:luma --file=dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js
```
shows following;
![image](https://user-images.githubusercontent.com/1873745/90256534-8f3a4f00-de4e-11ea-85ed-110399804540.png)

**Comment by complexthings** [comment]
I get the following, but I don't have your latest changes pulled down:

![image](https://user-images.githubusercontent.com/1484134/90257366-17036780-de15-11ea-8c4a-c11098420608.png)

**Comment by complexthings** [comment]
It's the `let` you have on line 78 needs to be a `var`

**Comment by ihor-sviziev** [comment]
@complexthings yeah, I found it too. Thx! for your help!

Anyway thank you so much!

Will keep this issue open for adding docs

**Comment by davidalger** [comment]
Thanks for your work on this! PR with new docs section has been merged. It may be found here:
https://docs.warden.dev/configuration/magento2-testing.html#running-javascript-unit-tests

**Comment by ihor-sviziev** [comment]
Would like to follow up on this - is there any instruction how to debug these tests? For php unit we have xdebug, what about js unit?

**Comment by ihor-sviziev** [comment]
Ok. I was able to debug the tests in... browser, used following instruction as a base: https://derickbailey.com/2014/07/03/debugging-browserified-unit-tests-in-a-real-browser/.

What I did:
1. Forwarded 8000 port to host machine by creating following `.warden/warden-env.yml` file:
```yml
version: "3.5"
services:
  php-debug:
    ports:
      - 8000:8000
```

and ran `warden env up` in order to apply this change.

2. Edited `dev/tests/js/jasmine/spec_runner/settings.json` file and changed `"keepalive": false` to `"keepalive": true`.

3. Executed in order to run start tests server
```bash
warden debug
grunt spec:luma
```

4. Opened in browser http://localhost:8000/_SpecRunner.html and tests started running directly in the Google Chrome, so I could open the developer console and put there some breakpoint.

Not sure if it's good option, but it works  for me.

**Comment by davidalger** [comment]
Good notes man. I wonder if it could be easily addressed by adding some labels so Traefik would route that in, similar to what's done here for Live Reload support: https://github.com/davidalger/warden/blob/develop/environments/magento2/magento2.base.yml#L8-L17

The route would go nowhere unless grunt was listening. But that would only send it to either php-fpm or php-debug and not be simple to switch. 🧐

**Comment by ihor-sviziev** [comment]
@davidalger i think using php-debug container is better here because it's basically designed for test debug :)
