### ISSUE TITLE
PHPStorm remote docker-compose based PHP interpreter configuration for integration testing

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#21]
In order to develop Magento extensions and core patches efficiently I want to be able to run integration tests in PHPStorm.

PHPStorm allows configuration of remote, docker-compose based, PHP interpreters.
Here is what I've done so far:

* Service: `php-debug`
* docker-compose files:
  * /usr/local/Cellar/warden/0.1.10/environments/magento2.base.yml 
  * /usr/local/Cellar/warden/0.1.10/environments/magento2.darwin.yml
* environment variables from `.env`:
  * `WARDEN_ENV_NAME`
  * `WARDEN_ENV_TYPE`
  * `TRAEFIK_DOMAIN`
  * `TRAEFIK_SUBDOMAIN`
  * `WARDEN_WEB_ROOT` (this one isn't from .env but I thought it might help)

With this configuration PHPStorm allows saving the interpreter even though it says it's unable to parse the validation script output.

Nevertheless, PHPStorm allows me to continue, even though PHPStorm can not determine the PHP version.

Then I add a path mapping to the interpreter configuration from `<Project root> -> /var/www/html` manually, however, PHPStorm also read an invalid mapping from the yaml:  
`/usr/local/Cellar/warden/0.1.10/environments/.${WARDEN_WEB_ROOT:-}/pub/media -> /var/www/html/pub/media`  
It seems PHPStorm doesn't like the config in `magento2.darwin.yaml`:
`.${WARDEN_WEB_ROOT:-}/pub/media:/var/www/html/pub/media:delegated`

Next I changed `.${WARDEN_WEB_ROOT:-}` to `${WARDEN_WEB_ROOT:-}` (removed the leading `.`) and it indeed allowed PHPStorm to find the PHP interpreter correctly.
I'm not sure why the `.` is here, I'll test shortly if warden seems to work without it, too.

When I then try to set up a PHPUnit configuration with this remote interpreter, I get the message:
```
Can not parse PHPUnit version output: Could not open input file: vendor/phpunit/phpunit/phpunit`
```
I tried setting the composer autoload.php file path to 
* `vendor/autoload.php`
* `/var/www/html/vendor/autoload.php`
* `/Volumes/CaseSensitive/Workspace/php-sites/m2-training/vendor/autoload.pnp` (my local path because of the path mapping config)

No luck. This might be an issue with PHPStorm, I don't know, but it would be wonderful to get integration tests working in the IDE.

**Comment by Vinai** [comment]
I did some testing what the effect of removing the leading `.` is.
In a nutshell, without the leading `.` the environment variable `WARDEN_WEB_ROOT` is required in `.env`, otherwise the mount `/pub/media` is considered an absolute path which of course is wrong.

A hardcoded complete path in turn means the project can't be moved to another location on the disk, but setting the environment variable to `.` has the desired effect.

@davidalger would you consider a PR to the `init-env` command so it adds `WARDEN_WEB_ROOT=.` to the initial `.env` file?
For backward compatibility the script that reads the file should probably set that value, too, if it's missing from `.env` at read time.

**Comment by dani97** [comment]
@Vinai I used docker image to setup interpreter and it worked for me perfectly.

**Comment by davidalger** [comment]
@dani97 Care to share details of how you set it up?

**Comment by dani97** [comment]
first configure docker service https://www.jetbrains.com/help/phpstorm/docker.html
Then configure a new interpreter, with the docker server configured earlier and select the warden container for running integration tests, I used debug container so that I can debug with breakpoints
![Screenshot from 2020-07-03 12-58-16](https://user-images.githubusercontent.com/13298685/86443444-e7990f80-bd2c-11ea-9660-a6bb66e8456e.png)

**Comment by Vinai** [comment]
Thanks for the info, it's been so long and a lot of work has been done on Warden, I'll try again soon.

**Comment by Vinai** [comment]
Tried to mirror your config without success.

<img width="726" alt="Bildschirmfoto 2020-07-06 um 18 12 33" src="https://user-images.githubusercontent.com/72463/86615227-74a1ca00-bfb4-11ea-83db-b2236a57e89e.png">

<img width="997" alt="Bildschirmfoto 2020-07-06 um 18 14 21" src="https://user-images.githubusercontent.com/72463/86615287-8aaf8a80-bfb4-11ea-8d3a-580aa5edd181.png">

<img width="1069" alt="Bildschirmfoto 2020-07-06 um 18 15 12" src="https://user-images.githubusercontent.com/72463/86615379-ab77e000-bfb4-11ea-8224-9819b09d3d1d.png">

<img width="1542" alt="Bildschirmfoto 2020-07-06 um 18 16 12" src="https://user-images.githubusercontent.com/72463/86615527-d82bf780-bfb4-11ea-9651-421fc2181caf.png">

Seems like PHPStorm is running the correct docker image, but isn't mounting the required volumes.

**Comment by Elamurugan-Nallathambi** [comment]
@Vinai @dani97 I myself have same issue. 
Every-time running test execution from container (`warden shell`) after writing test updates from PHPStorm.

PHPStorm: 2020.2 EAP or with previous version
OS: macOS Catalina 10.15.5 (19F101)

**Comment by dani97** [comment]
@Vinai @Elamurugan-Nallathambi, I noticed that in my setup that there is no folder like `/opt/project` inside the container and project is under `/var/www/html` but it still works for me. So I did some research and found this https://blog.alejandrocelaya.com/2017/02/01/run-phpunit-tests-inside-docker-container-from-phpstorm/
Phpstorm copies the project to `/opt/project` of a new container and runs the unit test. So change the path mapping to `/opt/project` and it will work for you. 

```
Testing started at 11:49 AM ...

[docker://wardenenv/php-fpm:7.4-magento2-debug/]:php /opt/project/vendor/phpunit/phpunit/phpunit --configuration /opt/project/dev/tests/unit/phpunit.xml --filter Magento\\Cms\\Test\\Unit\\Block\\BlockTest --test-suffix BlockTest.php /opt/project/app/code/Magento/Cms/Test/Unit/Block --teamcity
PHPUnit 9.1.5 by Sebastian Bergmann and contributors.



Time: 00:00.200, Memory: 14.00 MB
```

**Comment by dani97** [comment]
Adding screenshots of interpreter and phpunit config for your reference
![Screenshot from 2020-07-07 12-09-41](https://user-images.githubusercontent.com/13298685/86729460-21c72180-c04b-11ea-872f-08ba215ba094.png)
![Screenshot from 2020-07-07 12-11-02](https://user-images.githubusercontent.com/13298685/86729472-24c21200-c04b-11ea-916f-f590364fd35e.png)

**Comment by Vinai** [comment]
I fixed the `/opt/project mapping by removing it from the "Docker Container" settings beneath the "Path Mappings".

<img width="747" alt="Bildschirmfoto 2020-07-07 um 10 51 07" src="https://user-images.githubusercontent.com/72463/86752644-c9d6ed80-c03f-11ea-8502-eacb90f402e8.png">

When I add the "Project Root => /var/www/html" path mapping there, the remote interpreter can be executed by PHPStorm.

This is good enough for unit tests, but since PHPStorm executes the docker container for each PHP execution, no other containers are linked, and so there is no access to MySQL or Redis and the integration tests can't be run.

I think the PHP interpreter will have to be configured using "Docker Compose", but I haven't been able to get that working yet since the docker compse configuration is rather complex with many files having to be included in the right order with the right environment variables being set.

**Comment by Vinai** [comment]
Problem solved thanks to @lbajsarowicz 

The merged docker-compose config for a project can be dumped with
```
$ warden env config > docker-compose.yml
```

Then this configuration can be selected in the PHPStorm settings for a docker-compose remote interpreter.
Select the `exec` option instead of `create new container`  for the fastest startup. Anyhow, this way integration tests work fine in PHPStorm.

**Comment by lfolco** [comment]
Any chance how to set this up could be added to the official docs? I'm having a heck of a time getting this setup.

**Comment by naseeraslam** [comment]
How can I make the remote interpreter the default? I followed the steps above, but the default PHP local interpreter is still executing. Could someone please explain how to set the remote interpreter as the default in PhpStorm?

**Comment by naseeraslam** [comment]
![Remote](https://github.com/wardenenv/warden/assets/56691274/d780772e-e2f9-440a-9b8b-97d1e8c18774)
When I click on 'PHP CS Fixer - Whole File' in suggestions, it executes the default system PHP interpreter instead of my remote interpreter.
