### ISSUE TITLE
Elasticsearch service not run

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#210]
used warden 0.9.0 dev

start container elasticsearch show status done but when i check status docker services . Elasticsearch not available
Please see image below

![Screenshot from 2020-08-14 23-08-42](https://user-images.githubusercontent.com/1908873/90269841-7b5d1000-de83-11ea-8d0f-659a967f4c16.png)

Not sure why this problem happen. Try some docker re-init but not get luck

WARDEN_DB=1
WARDEN_ELASTICSEARCH=1
WARDEN_VARNISH=1
WARDEN_RABBITMQ=1
WARDEN_REDIS=1

ELASTICSEARCH_VERSION=7.6
MARIADB_VERSION=10.3
NODE_VERSION=10
PHP_VERSION=7.4
RABBITMQ_VERSION=3.8
REDIS_VERSION=5.0
VARNISH_VERSION=6.0

Here i another log screen

![Screenshot from 2020-08-14 23-19-43](https://user-images.githubusercontent.com/1908873/90270695-c9264800-de84-11ea-8612-918f8316b0d8.png)
CC: @davidalger

**Comment by mrtuvn** [comment]
used warden env up but not get any luck

**Comment by mrtuvn** [comment]
run warden env logs --tail 0 -f elasticsearch          
>> Attaching to contribution_elasticsearch_1
contribution_elasticsearch_1 exited with code 1

**Comment by mrtuvn** [comment]
Unfortunately i can't reproduce issue in macintosh
Successfull installation at first try. Everything work like charm

**Comment by ihor-sviziev** [comment]
@mrtuvn could you run following command?
```
warden env logs -f elasticsearch
```

**Comment by mrtuvn** [comment]
yes it's work now. Seem my setup linux got some issue
