### ISSUE TITLE
Mutagen fail sync in macos 10.15.6

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#215]
ERROR: Mutagen encountered an error during sync: alpha scan error: unable to open synchronization root: operation not permitted

Got this issue when sync my local warden dev magento 2

Run warden env up -d doesn't help
issue happen when run sync when docker env start sync

Used docker desktop for MacOS (2.3.0.4)
docker-engine 19.03.12
Mutagen 0.11.6

**Comment by mrtuvn** [comment]
run mutagen daemon stop/start may work with me

**Comment by micso** [comment]
Thanks @mrtuvn. I had the same issue and your solution worked.

**Comment by mrtuvn** [comment]
Glad it help u. Closed issue because this is system preferences
