### ISSUE TITLE
Global services unreachable via browser

### ISSUE THREAD

**Issue by springerin** [davidalger/warden#217]
warden version 0.9.0
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.25.0, build unknown
ubuntu 20.04

On a fresh install of warden, i can't reach any of the global services.
In the logs I've found this error:

> traefik      | time="2020-08-25T07:15:22Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
> traefik      | time="2020-08-25T07:15:22Z" level=info msg="Traefik version 2.2.8 built on 2020-07-28T15:46:03Z"
> traefik      | time="2020-08-25T07:15:22Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
> traefik      | time="2020-08-25T07:15:22Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
> traefik      | time="2020-08-25T07:15:22Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"/etc/traefik/dynamic.yml\"}"
> traefik      | time="2020-08-25T07:15:22Z" level=info msg="Starting provider *traefik.Provider {}"
> traefik      | time="2020-08-25T07:15:22Z" level=info msg="Starting provider *docker.Provider {\"watch\":true,\"endpoint\":\"unix:///var/run/docker.sock\",\"defaultRule\":\"Host(`{{ .Name }}.warden.test`)\",\"network\":\"warden\",\"swarmModeRefreshSeconds\":15000000000}"
> traefik      | time="2020-08-25T07:20:24Z" level=error msg="service \"portainer\" error: unable to find the IP address for the container \"/portainer\": the server is ignored" providerName=docker container=portainer-warden-f4f4a5daa929ce4ccf8691612be3b9c115c70cb5fb6f2d8c09f382ee538734ab

The services are up as you can see:

> 
> warden svc ps
>   Name                 Command               State                      Ports                    
> -------------------------------------------------------------------------------------------------
> dnsmasq     webproc --config /etc/dnsm ...   Up      127.0.0.1:53->53/udp                        
> mailhog     MailHog                          Up      1025/tcp, 8025/tcp                          
> portainer   /portainer                       Up      9000/tcp                                    
> traefik     /entrypoint.sh traefik           Up      127.0.0.1:443->443/tcp, 127.0.0.1:80->80/tcp
> tunnel      /entry.sh /usr/sbin/sshd - ...   Up      127.0.0.1:2222->22/tcp  

Any idea what could I do to fix this?

**Comment by davidalger** [comment]
@springerin Given each of the global services reports as up, it sounds like DNS resolution is where it's likely falling apart. Nameserver configuration often must be manual. Don't have good docs on how to configure the linux workstation in the Warden docs (yet!) but you'll either want to add items to /etc/hosts for these OR setup your resolver to point to 127.0.0.1; there is some good info on it here: https://devilbox.readthedocs.io/en/latest/howto/dns/add-custom-dns-server-on-linux.html#howto-add-custom-dns-server-on-linux

**Comment by springerin** [comment]
I confirm indeed this was the issue. thank you very much for the help
