### ISSUE TITLE
Trusted SSL Support

### ISSUE THREAD

**Issue by sprankhub** [davidalger/warden#221]
It would be really nice if Warden had trusted SSL support. It should not matter too much, but it is still nicer to not get a warning about untrusted SSL. Is anything like this planned?

I saw that other tools like ddev use [mkcert](https://github.com/FiloSottile/mkcert) for that. Maybe that would be an option for Warden as well?

**Comment by prestonchoate** [comment]
So warden has a tool for signing SSL certs built in. That is in the documentation. What isn't documented well is adding Warden's cert authority to your browser of choice. Which browser do you use most often?

**Comment by sprankhub** [comment]
Thanks for the quick reply!

Yes, I did generate a certificate via `warden sign-certificate exampleproject.test` as noted in the [docs](https://docs.warden.dev/environments/initializing.html). So yes, basically that second step - adding the authority to the browser is missing. I use Chromium.

Although it would be even nicer if I did not have to do this manually (this was not needed when using mkcert).

**Comment by prestonchoate** [comment]
I agree auto adding the cert authority to the installed system would be really nice. I'll do some preliminary research on how to do that, though David probably already has researched it. 

In the meantime do you know how to add the cert authority to Chromium? If not I can dig up my instructions on how to do that

**Comment by sprankhub** [comment]
Thanks! If this will be implemented in the nearer future, I do not need instructions for that. If this will not be implemented at all or not in the upcoming months, this should indeed be added to the docs IMHO :)

**Comment by davidalger** [comment]
The documentation should probably add something to the install page on this. Install procedure does actually add the CA root to the trust store. After it does that, curl for example will trust it on both Mac and Linux, but Firefox on Mac doesn't pick it up once added to the OS X Keychain and on Linux it seems Firefox has some of it's own rules on when it picks up a new CA root from the trust store or not (I've seen it pick it up when the root is added to the trust store prior to first opening Firefox, or not picked up when Firefox was in use prior to installing Warden…pretty sure Firefox has some sort of CA trust store cache of sorts). Chrome similarly has seen issues recognizing that the new root was added to the trust store.

See this code for how the CA root is "trusted" on Fedora, Ubuntu, or MacOS: https://github.com/davidalger/warden/blob/develop/commands/install.cmd#L28-L52

In the [M2 project template](https://github.com/davidalger/warden-env-magento2) I (and most of my colleagues use) there is some info on trusted the CA root in Firefox and Chrome should they not pick it up:

> **Note:** If you are using **Firefox** and it warns you the SSL certificate is invalid/untrusted, go to Preferences -> Privacy & Security -> View Certificates (bottom of page) -> Authorities -> Import and select `~/.warden/ssl/rootca/certs/ca.cert.pem` for import, then reload the page.
  
> **Note:** If you are using **Chrome** on **Linux** and it warns you the SSL certificate is invalid/untrusted, go to Chrome Settings -> Privacy And Security -> Manage Certificates (see more) -> Authorities -> Import and select `~/.warden/ssl/rootca/certs/ca.cert.pem` for import, then reload the page.

I'll leave this open until this can make it into the Warden docs page. Any input on where best to put it would be welcome. I'm thinking the page on install probably makes the most sense, but perhaps on a troubleshooting common problems page (doesn't currently exist) as well.

**Comment by sprankhub** [comment]
I thought that adding the `.pem` file to the Chrome settings solved it. However, I still randomly get the following error:

    NET::ERR_CERT_AUTHORITY_INVALID
    Subject: TRAEFIK DEFAULT CERT

    Issuer: TRAEFIK DEFAULT CERT

    Expires on: 08.09.2021

    Current date: 08.09.2020

    PEM encoded chain:
    -----BEGIN CERTIFICATE-----
    ...

Any idea why? If I accept, it works for a few minutes, until I get that message again. If I try to import the `.pem` file again, Chrome says it already exists.
