### ISSUE TITLE
apache support

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#222]
Is there a way I can use apache as web server here with warden docker toolchain?

**Comment by sebastian-ehrling** [comment]
This would be very helpful for some project types

**Comment by ihor-sviziev** [comment]
Is there any benefit of using apacke?
We actually switched from apache+mod php to nginx + php-fpm and it improved a bit performance of the website. I would recommend you to migrate also.

**Comment by davidalger** [comment]
This isn't something I plan support, so I'm going to close this out and wontfix. As @ihor-sviziev mentioned, it would be pretty complicated to maintain both Nginx and Apache on this. You're welcome to attempt overriding the nginx image with an apache one and perhaps using apache + php-fpm (likely simpler than attempting apache + mod_php) but do understand that you'll mostly be on your own in doing so. My recommendation would be to make the switch to Nginx if at all possible.
