### ISSUE TITLE
[Docs] Instruction missing in database configuration

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#223]
Navicat app on macOS missing info relate with password and can't connect to database
Is we need password for connect ?

**Comment by lbajsarowicz** [comment]
There is information about Database connection: https://docs.warden.dev/configuration/database.html

**Comment by mrtuvn** [comment]
yes i have checked that but seem not working with me when use navicat app

**Comment by lbajsarowicz** [comment]
Make sure that you can connect tunnel with ssh

**Comment by mrtuvn** [comment]
<img width="721" alt="Screen Shot 2020-09-03 at 09 59 19" src="https://user-images.githubusercontent.com/1908873/92066493-3403d880-edcc-11ea-99ef-501f36c9cc76.png">
here is the page setup ssh in navicat

**Comment by Elamurugan-Nallathambi** [comment]
@mrtuvn In my case the host entry to map the ssh_key file from ssh_config was gone after the OS upgrade. See if you have something like this in your `/etc/ssh/ssh_config`

```
## WARDEN START ##
Host tunnel.warden.test
  HostName 127.0.0.1
  User user
  Port 2222
  IdentityFile ~/.warden/tunnel/ssh_key
## WARDEN END ##
```

**Comment by mrtuvn** [comment]
still not work :')

**Comment by sajidunnar** [comment]
I have same issue , table plus can be easily connected but Navicat or or other softwares not connecting on Linux Ubunt
