### ISSUE TITLE
Question - How to run all M2 integration tests?

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#234]
Just tried to run all integration tests on Magento 2.4-develop branch and got following failure:
![image](https://user-images.githubusercontent.com/1873745/93758193-a835dd00-fc10-11ea-9d29-fd63cc045300.png)

I already set up 8GB memory limit, but it still fails.
Here is my changes in phpunit.xml file:
![image](https://user-images.githubusercontent.com/1873745/93758296-d74c4e80-fc10-11ea-9dda-11631e56a847.png)

I don't have this issue when running just single test

**Comment by lbajsarowicz** [comment]
`php -dmemory_limit=64G vendor/bin/...`

**Comment by ihor-sviziev** [comment]
Yeah, now it works fine! Maybe let's add some troubleshooting section?

**Comment by ihor-sviziev** [comment]
Just created PR for fixing that https://github.com/davidalger/warden/pull/239
