### ISSUE TITLE
Selenium hub container doesn't work anymore

### ISSUE THREAD

**Issue by sebastian-ehrling** [davidalger/warden#236]
Hi

we have an issue with MFTF tests in a magento 2 project. After starting a test with vendor/bin/mftf run:group ... 
I get a timeout after 600 seconds.

In portainer my selenium hub container has the state "unhealthy". 
I've tried to recreate all containers with warden env down -v.  :( 

Docker 2.3.0.5 (48029)
warden.dev 0.9.1

**Comment by lbajsarowicz** [comment]
What `warden env logs selenium-hub` reports?

**Comment by sebastian-ehrling** [comment]
Hi @lbajsarowicz 

do you have any idea?

selenium-hub_1     | 2020-09-25 09:30:07,061 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium-hub_1     | 2020-09-25 09:30:07,062 INFO supervisord started with pid 7
selenium-hub_1     | 2020-09-25 09:30:08,063 INFO spawned: 'selenium-hub' with pid 10
selenium-hub_1     | Starting Selenium Hub with configuration:
selenium-hub_1     | 2020-09-25 09:30:08,073 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub_1     | {
selenium-hub_1     |   "host": "0.0.0.0",
selenium-hub_1     |   "port": 4444,
selenium-hub_1     |   "role": "hub",
selenium-hub_1     |   "maxSession": 5,
selenium-hub_1     |   "newSessionWaitTimeout": -1,
selenium-hub_1     |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium-hub_1     |   "throwOnCapabilityNotPresent": true,
selenium-hub_1     |   "jettyMaxThreads": -1,
selenium-hub_1     |   "cleanUpCycle": 5000,
selenium-hub_1     |   "browserTimeout": 0,
selenium-hub_1     |   "timeout": 0,
selenium-hub_1     |   "debug": false
selenium-hub_1     | }
selenium-hub_1     | 09:30:08.432 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
selenium-hub_1     | 09:30:08.613 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
selenium-hub_1     | 2020-09-25 09:30:09.038:INFO::main: Logging initialized @959ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub_1     | 09:30:09.380 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub_1     | 09:30:09.380 INFO [Hub.start] - Nodes should register to http://172.28.0.5:4444/grid/register/
selenium-hub_1     | 09:30:09.381 INFO [Hub.start] - Clients should connect to http://172.28.0.5:4444/wd/hub
selenium-hub_1     | 09:30:14.462 INFO [DefaultGridRegistry.add] - Registered a node http://172.28.0.10:5555
selenium-hub_1     | 2020-09-25 09:31:03,328 WARN received SIGTERM indicating exit request
selenium-hub_1     | 2020-09-25 09:31:03,328 INFO waiting for selenium-hub to die
selenium-hub_1     | 2020-09-25 09:33:13,413 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
selenium-hub_1     | 2020-09-25 09:33:13,423 INFO supervisord started with pid 8
selenium-hub_1     | 2020-09-25 09:33:14,426 INFO spawned: 'selenium-hub' with pid 11
selenium-hub_1     | Starting Selenium Hub with configuration:
selenium-hub_1     | 2020-09-25 09:33:14,437 INFO success: selenium-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub_1     | {
selenium-hub_1     |   "host": "0.0.0.0",
selenium-hub_1     |   "port": 4444,
selenium-hub_1     |   "role": "hub",
selenium-hub_1     |   "maxSession": 5,
selenium-hub_1     |   "newSessionWaitTimeout": -1,
selenium-hub_1     |   "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
selenium-hub_1     |   "throwOnCapabilityNotPresent": true,
selenium-hub_1     |   "jettyMaxThreads": -1,
selenium-hub_1     |   "cleanUpCycle": 5000,
selenium-hub_1     |   "browserTimeout": 0,
selenium-hub_1     |   "timeout": 0,
selenium-hub_1     |   "debug": false
selenium-hub_1     | }
selenium-hub_1     | 09:33:15.498 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
selenium-hub_1     | 09:33:15.732 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 4444
selenium-hub_1     | 2020-09-25 09:33:16.331:INFO::main: Logging initialized @1789ms to org.seleniumhq.jetty9.util.log.StdErrLog
selenium-hub_1     | 09:33:16.760 INFO [Hub.start] - Selenium Grid hub is up and running
selenium-hub_1     | 09:33:16.760 INFO [Hub.start] - Nodes should register to http://172.28.0.7:4444/grid/register/
selenium-hub_1     | 09:33:16.760 INFO [Hub.start] - Clients should connect to http://172.28.0.7:4444/wd/hub
selenium-hub_1     | 09:33:17.210 INFO [DefaultGridRegistry.add] - Registered a node http://172.28.0.10:5555
selenium-hub_1     | 09:39:50.527 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [--window-size=1280,1024, --disable-extensions, --enable-automation, --disable-gpu, --enable-Passthrough]}}
selenium-hub_1     | 09:39:50.530 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {seleniumProtocol=WebDriver, se:CONFIG_UUID=7d25b650-3597-4f7e-a4ef-c56449d78797, browserName=chrome, maxInstances=1, version=64.0.3282.119, applicationName=, platform=LINUX}
selenium-hub_1     | 09:39:53.641 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, chromeOptions: {args: [--window-size=1280,1024, --disable-extensions, --enable-automation, --disable-gpu, --enable-Passthrough]}}

**Comment by sebastian-ehrling** [comment]
@davidalger @lbajsarowicz 
Du you have any idea?

**Comment by davidalger** [comment]
@sebastian-ehrling I know it's been a while, so perhaps you've moved on, but there is some good info over on #268 which may help you.
