### ISSUE TITLE
Issue while connecting to XDebug

### ISSUE THREAD

**Issue by gdoleczek** [davidalger/warden#237]
Hi,
It would be great to add information in XDebug documentation that debugging may not work if there is other service running on port 9000. And quick information how to detect it on Mac and Linux.

**Comment by redo-interactive** [comment]
@davidalger 
I use wsl2, and I'm not able to activate xdebug, I use phpstorm, I activate listening, and in browsers I have my xdebug extension activated. But unfortunately I'm not able to debug my magento2 module that I'm creating, same config in macos works without any problems. 

@gdoleczek are you able to tell me how to check if there is any other service running on port 9000 on windows with wsl2? 

Best regards and thanks for any infos... :)

**Comment by maverickk89** [comment]
Hello,
I followed the guide (environment with M2) but still no connection with xDebugger:

WARDEN_ENV_NAME=mydomain
WARDEN_ENV_TYPE=magento2
WARDEN_WEB_ROOT=/

TRAEFIK_DOMAIN=mydomain.test
TRAEFIK_SUBDOMAIN=app

WARDEN_DB=1
WARDEN_ELASTICSEARCH=1
WARDEN_VARNISH=1
WARDEN_RABBITMQ=0
WARDEN_REDIS=1

ELASTICSEARCH_VERSION=6.5
MARIADB_VERSION=10.3
NODE_VERSION=10
COMPOSER_VERSION=1
PHP_VERSION=7.2
PHP_XDEBUG_3=1
RABBITMQ_VERSION=3.8
REDIS_VERSION=3.2
VARNISH_VERSION=6.0

WARDEN_SYNC_IGNORE=

WARDEN_ALLURE=0
WARDEN_SELENIUM=0
WARDEN_SELENIUM_DEBUG=0
WARDEN_BLACKFIRE=0
WARDEN_SPLIT_SALES=0
WARDEN_SPLIT_CHECKOUT=0
WARDEN_TEST_DB=0
WARDEN_MAGEPACK=0

BLACKFIRE_CLIENT_ID=
BLACKFIRE_CLIENT_TOKEN=
BLACKFIRE_SERVER_ID=
BLACKFIRE_SERVER_TOKEN=

![Istantanea_2021-05-04_19-32-59](https://user-images.githubusercontent.com/34450139/117045376-bbb13680-ad0f-11eb-82d3-b879435df69a.png)


what could be the problem?

**Comment by redo-interactive** [comment]
For me the only solution to make it work was to install it on ubuntu / macOs. Windows and wsl2 doesn't work.

**Comment by redo-interactive** [comment]
@maverickk89 ah ok, 

have you set your PHPSTORM debugger settings ?
![image](https://user-images.githubusercontent.com/62672785/117173109-bbc33c00-adcc-11eb-9f17-fcfe3263e97b.png)

![image](https://user-images.githubusercontent.com/62672785/117173194-d1386600-adcc-11eb-99a4-86020736aa21.png)

![image](https://user-images.githubusercontent.com/62672785/117173240-df868200-adcc-11eb-9df0-a590d0e6ce7d.png)


sm-docker should be replaced by mydomain-docker in your case

I imagine you have installed xdebug extension in your browser?

**Comment by maverickk89** [comment]
no I have already set them as described. I found that system use by default Xdebug 3.x but M2's version I'm using is 2.3.x and it supports only Xdebug 2.x, changed that in the .env and after I have been checked that system is using Xdebug 2.x all is working again.

**Comment by 200263830** [comment]
@maverickk89 
How did you change PHP_XDEBUG_3 to 2.x in your env file

**Comment by tdgroot** [comment]
@200263830 by setting `PHP_XDEBUG_3` to `0`.

**Comment by mstojanow** [comment]
> @200263830 by setting `PHP_XDEBUG_3` to `0`.

Thanks a lot - this helped on my project as well!

**Comment by dgutman10** [comment]
> @davidalger I use wsl2, and I'm not able to activate xdebug, I use phpstorm, I activate listening, and in browsers I have my xdebug extension activated. But unfortunately I'm not able to debug my magento2 module that I'm creating, same config in macos works without any problems.
> 
> @gdoleczek are you able to tell me how to check if there is any other service running on port 9000 on windows with wsl2?
> 
> Best regards and thanks for any infos... :)

hello, to correct the problem in windows what you should do is the following

first add to the root of your project the .warden folder

inside .warden add the file warden-env.yml with the following content

`version: "3.5"
services:
  nginx:
    environment:
      - XDEBUG_CONNECT_BACK_HOST=host.docker.internal
`
