### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#240]
On the homepage https://warden.dev/ we have `warden up`, while the new command is `warden svc up`.
![image](https://user-images.githubusercontent.com/1873745/94788621-812f9600-03dc-11eb-8302-f7a1770b6c58.png)

I wasn't able to find a file that used here, so can't do PR for such small fix

**Comment by davidalger** [comment]
Thanks @ihor-sviziev! I've fixed this issue, and imported the files used to build warden.dev into this repository under the `homepage` directory so everything is now in one place.
