### ISSUE TITLE
Add plugin to elasticsearch container

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#243]
How can install plugins (analysis-phonetic, analysis-icu, ...) on the Elasticsearch container in order to use the SmileElastic Suite on Magento 2?

Thank you for your support.

**Comment by davidalger** [comment]
The ES containers built and used by default by this project include (and always have) both the `analysis-phonetic` and `analysis-icu` plugins with the express purpose being projects which include the SmileElastic suite. Reference this 7.9 build file for example: https://github.com/davidalger/warden/blob/develop/images/elasticsearch/7.9/Dockerfile

There is no mechanism currently for arbitrarily adding additional plugins apart from building and using a custom image on the project.
