### ISSUE TITLE
Include Cron in next warden release

### ISSUE THREAD

**Issue by gfilice** [davidalger/warden#249]
Hello @davidalger ,
can you include the Cron PR #80 in the next Warden release?

Thank you

**Comment by davidalger** [comment]
As was explained in this comment on that PR: https://github.com/davidalger/warden/pull/80#issuecomment-664689120 the approach there is one I'm not interested in seeing incorporated into Warden, instead favoring the use of running crond within the fpm containers. There is also information in that comment showing how one can persist a crontab configuration on the container if need be.
