### ISSUE TITLE
Upgrade NodeJS to ">=12.0" version

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#250]
Current node projects often require the current LTS version 12+
Examples are Symfony based projects like Marello or ORO Crm.

The current version of node is 
```
$ node -v
v10.22.1
```

**Comment by complexthings** [comment]
I always find myself setting `NODE_VERSION=14` in my .env so I'm with you on this.

**Comment by complexthings** [comment]
https://github.com/davidalger/warden/blob/develop/commands/env-init.cmd#L55

**Comment by Vinai** [comment]
Oh I didn't realize it was included in the `.env`, thanks for that info 👍 
Still I think it would be good to bump the default to 12.

**Comment by davidalger** [comment]
Definitely open to bumping up the default version installed in the images. IIRC I set it at v10 largely based on the input of more FE focused colleagues.

Do either of you know what version of Node JS is required by the latest PWA Studio iteration? If it still requires v10 (which I think it did back when I added node to the fpm images) it might warrant having a more current default in the generic fpm images and older default version in the magento1/magento2 fpm variants.

The way this is setup is using `n` to facilitate installation of different versions on container startup. Following shows install in the FPM container, the entrypoint script checks the NODE_VERSION variable and runs `n install <version>`
```
ENV NODE_VERSION    10
RUN npm install -g n \
    && n install ${NODE_VERSION} \
    && rm -rf /usr/local/n/versions/node
```

**Comment by Vinai** [comment]
PWA Studio still [requires](https://github.com/magento/pwa-studio/blob/develop/package.json#L89) `>=10.x`.
Strange though, that project doesn't seem to mind swapping in newer dependencies often. I wonder if in practice the developers don't use a somewhat more current node version.

**Comment by jahvi** [comment]
PWA Studio requires v10 at least but it runs fine on Node 12 (I haven't tried on v14).

Node 10 will be EOL by the end of April so using it as default should be discouraged.

**Comment by jahvi** [comment]
Is it worth bumping this now that v10 is officially unsupported now?

**Comment by davidalger** [comment]
Once #425 is released, env-init will create `.env` with `NODE_VERSION=12` instead of `NODE_VERSION=10` regardless of environment type.
