### ISSUE TITLE
" specified.ronment type "magento1

### ISSUE THREAD

**Issue by norgeindian** [davidalger/warden#252]
I set up a new Magento1 project. This worked fine and I could call the page without any issues.
Since I accidentally called a n98-magerun command directly from the Magento directory and not inside the container, I can not call any warden command any more.
Whatever I do, I get the error: `" specified.ronment type "magento1`
Does anyone have an idea what goes wrong here and how I can fix it?

**Comment by stephanie-ehrling** [comment]
Please check the line endings for the .env file. I think there is something messed up.
