### ISSUE TITLE
Enable XDEBUG through graphql requests?

### ISSUE THREAD

**Issue by rootindex** [davidalger/warden#255]
I am having difficulty enabling xdebug while using the graphql endpoint in a magento2 environment.

I tested to see if the XDEBUG_SESSION_START=PHPSTORM GET param might help, sadly the checks seems to be on $_cookie_{..} only currently.

I am using this extension - https://github.com/imolorhe/altair

Any direction would be appreciated.

**Comment by danielkperez** [comment]
@rootindex I'm able to use the following cookie and it works great. 

```
XDEBUG_SESSION=PHPSTORM; Path=/; Domain=.gifts-loc.theknot.com; Expires=Thu, 28 Oct 2021 18:07:33 GMT;
```

I'm using Postman for the majority of the debugging requests.

**Comment by dani97** [comment]
@rootindex there should be XDEBUG_SESSION cookie set with PHPSTORM as value for warden nginx to make debug connection. As a workaround you can install browser xdebug helper extension and open magento frontend on the same browser window and enable xdebug helper. The cookies are automatically set now for your magento graphql too.

**Comment by rootindex** [comment]
> @rootindex there should be XDEBUG_SESSION cookie set with PHPSTORM as value for warden nginx to make debug connection. As a workaround you can install browser xdebug helper extension and open magento frontend on the same browser window and enable xdebug helper. The cookies are automatically set now for your magento graphql too.

This is the solution that suited me best currently

Ideally having the ability to include `XDEBUG_SESSION_START=PHPSTORM` as a get in the url would most likely be the best way to solve this. The cookie trick seems to be a leak from a tab to an extension which will likely get patched in the future.

Please re-open if this solution can be marked as a future todo.
