### ISSUE TITLE
No mailhog after 0.9.1 upgrade

### ISSUE THREAD

**Issue by jschreck** [davidalger/warden#259]
After upgrading to 0.9.1 I get this message when launching a product with `warden env up -d`

`Error response from daemon: No such container: mailhog`

`docker ps` does indeed confirm there's no such container. I'm a bit unclear how I lost that and what I need to do to get it back?

Thanks for any advice!

**Comment by pchoate-blueacorn** [comment]
Mailhog was moved out of the individual environments and moved to a global service. If you do `warden svc down` and then `warden svc up` it should create the global mailhog service and you can access it at mailhog.warden.test

**Comment by jschreck** [comment]
@pchoate-blueacorn - That worked like a charm! Thanks for the help!

**Comment by pchoate-blueacorn** [comment]
Happy to help :)
