### ISSUE TITLE
unable to warden sync start

### ISSUE THREAD

**Issue by nickapopolus** [davidalger/warden#26]
Just updated to Catalina and am no longer able to get my environment to start because I am receiving the following error when running warden sync start. warden up and warden start are working fine, but sync start is throwing this error:

Warning: TOML-based configuration files are deprecated, please migrate to YAML
Connecting to agent (POSIX)...
Error: create failed: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)

ERROR: Command `mutagen create -c "${WARDEN_DIR}/environments/${WARDEN_ENV_TYPE}.mutagen.toml" --label "warden-sync=${WARDEN_ENV_NAME}" "${WARDEN_ENV_PATH}${WARDEN_WEB_ROOT:-}" "docker://$(warden env ps -q php-fpm)/var/www/html"` on line 32 failed with exit code 1

**Comment by davidalger** [comment]
@nickapopolus I've been running Catalina since it hit GA without issues, so I'm guessing something is stuck with Mutagen. The warning about TOML vs YAML can be ignored (Mutagen 0.10.0+ prefer YAML, but it doesn't affect anything), so the relevant error is this bit:
```
Error: create failed: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)
```
This is an error in the call out to the Mutagen tool, and here is what I would try to resolve:

a) Blow away the containers and associated data volumes (you'll lose the imported database when you do this):
```
warden env down -v
```
b) Start them all back up:
```
warden env up -d
```
c) Start the mutagen sync:
```
warden sync start
```

**Comment by nickapopolus** [comment]
This fixed the issue with Sync. Thank you so much.

**Comment by VivekShingala** [comment]
Hi @davidalger 

Above steps didn't work for me. I'm on warden 0.14.1 and trying to setup magento2.
![Screenshot 2023-10-22 at 9 50 25 AM](https://github.com/wardenenv/warden/assets/17267929/ded59e70-49f9-4d3b-ab78-09f3e6ce9722)

**Comment by VivekShingala** [comment]
I followed the below steps to make it work:

brew uninstall mutagen
---
brew install havoc-io/mutagen/mutagen
it will give below error:
Error: Formulae found in multiple taps: 
       * havoc-io/mutagen/mutagen-beta
       * mutagen-io/mutagen/mutagen-beta

Please use the fully-qualified name (e.g. havoc-io/mutagen/mutagen-beta) to refer to the formula.
---
To fix the error, run the below command:
brew untap havoc-io/mutagen && brew untap mutagen-io/mutagen
brew install havoc-io/mutagen/mutagen
---
Restart Docker
