### ISSUE TITLE
MaxOSX  error for dnsmasq  Cannot start service dnsmasq: Ports are not available: port is already allocated

### ISSUE THREAD

**Issue by ksutha** [davidalger/warden#262]
could not able to get the warden svc up  on the max osx because 

$ sudo lsof -nP -iUDP | grep :53
Password:
mDNSRespo   293 _mdnsresponder    6u  IPv4 0x4f7d49f5eb14cfd1      0t0  UDP *:5353
mDNSRespo   293 _mdnsresponder    7u  IPv6 0x4f7d49f5eb14ca01      0t0  UDP *:5353
mDNSRespo   293 _mdnsresponder   12u  IPv4 0x4f7d49f5eb63d149      0t0  UDP *:53
mDNSRespo   293 _mdnsresponder   16u  IPv6 0x4f7d49f5eb63ce61      0t0  UDP *:53

isince mac mdnsresponder runs to configure its networks needs. 

how can we solve this ?

**Comment by davidalger** [comment]
@ksutha What version of OS X are you seeing this on? Lots of Mac users (myself included) using this successfully without running into this problem. This is what I see when I look at what ports mDNSResponder is listening on:

```
$ sudo lsof -nP -iUDP | grep -i dns
mDNSRespo   285 _mdnsresponder    6u  IPv4 0xe2b5d104cc87ad05      0t0  UDP *:5353
mDNSRespo   285 _mdnsresponder    7u  IPv6 0xe2b5d104cc87c72d      0t0  UDP *:5353
mDNSRespo   285 _mdnsresponder   25u  IPv4 0xe2b5d104fae38a15      0t0  UDP *:56168
mDNSRespo   285 _mdnsresponder   27u  IPv6 0xe2b5d104fae36fed      0t0  UDP *:56168
mDNSRespo   285 _mdnsresponder   28u  IPv4 0xe2b5d104fae36d05      0t0  UDP *:53597
mDNSRespo   285 _mdnsresponder   40u  IPv6 0xe2b5d104fae505bd      0t0  UDP *:53597
```

As can be seen, not listening on port 53 over here, allowing the Docker container to listen as expected:

```
$ sudo lsof -nP -iUDP | grep :53\$
com.docke  4253     davidalger   71u  IPv4 0xe2b5d104cc7ae2d5      0t0  UDP 127.0.0.1:53
```

When I've seen Mac OS users have issues with the dnsmasq container starting due to a port conflict, in every case it's been due to something else they had installed previously such as the dnsmasq service Valet+ installs via brew and runs as a daemon conflicting on the port. I.e. this is the very first time I've heard a Mac OS user show mDNSResponder listening on port 53 and conflicting, hence the question about Mac OS version. This very well may be one of those issues which I cannot personally help resolve, as it sounds like something perhaps system specific.

**Comment by youanden** [comment]
Hi @davidalger ,

I am experiencing the same problem. I am using a completely clean Big Sur install but on Apple Silicon. I think this might have something to do with it. 

```
youanden@Georgiys-Mac-mini /opt % sudo lsof -nP -iUDP | grep -i dns
Password:
mDNSRespo 9570 _mdnsresponder    6u  IPv4 0x5fe92c55d7575139      0t0  UDP *:5353
mDNSRespo 9570 _mdnsresponder    7u  IPv6 0x5fe92c55d7576b61      0t0  UDP *:5353
mDNSRespo 9570 _mdnsresponder   28u  IPv4 0x5fe92c55dae48e51      0t0  UDP *:53
mDNSRespo 9570 _mdnsresponder   29u  IPv6 0x5fe92c55dae49cd9      0t0  UDP *:53
```
I had a coworker try on his Big Sur Intel-based Mac and he got:

```
ag@Alains-MacBook-Pro ~ % sudo lsof -nP -iUDP | grep -i dns
Password:
mDNSRespo  223 _mdnsresponder    6u  IPv4 0xbb95e063d54ea8e3      0t0  UDP *:5353
```

It looks like on Apple Silicon apple is binding to port 53 directly, perhaps for security reasons. Is there any way to reconfigure the port that is used by the docker configuration?

**Comment by youanden** [comment]
@ksutha @davidalger  I was able to figure it out.

First, I edited the docker-compose for warden:
```
/usr/local/opt/warden/docker/docker-compose.yml
```

I changed the port mapping for dnsmasq like so:
```
      - "127.0.0.1:5053:53/udp"
```



Then, edited the `test` resolver:
```
sudo vi /etc/resolver/test
```

I just added the port here:
```
nameserver 127.0.0.1
port 5053
```

Then just restarted dnsmasq:
```
warden svc restart dnsmasq
```

Of course, if it hasn't started fully yet, you can just do:
```
warden svc up
```

**Comment by davidalger** [comment]
Did a little interesting digging, and I found one person saying that Internet Sharing being on would cause `_mdnsresponder` to listen on port 53 (incidentally I just setup a completely clean Big Sur machine and installed Warden on it about 3 weeks ago with no issues at all). So I decided to do a little test:

Checked my listens, no port 53, just 5353:
```
$ sudo lsof -nP -iUDP | grep -iE ':(53|5353)$'
mDNSRespo  234 _mdnsresponder    6u  IPv4 0x36ce91a526998ddd      0t0  UDP *:5353
mDNSRespo  234 _mdnsresponder    7u  IPv6 0x36ce91a526998af5      0t0  UDP *:5353
```

So then I went to Sharing in System Preferences and turned on Internet Sharing and bam, there it is!
```
$ sudo lsof -nP -iUDP | grep -iE ':(53|5353)$'
mDNSRespo  234 _mdnsresponder    6u  IPv4 0x36ce91a526998ddd      0t0  UDP *:5353
mDNSRespo  234 _mdnsresponder    7u  IPv6 0x36ce91a526998af5      0t0  UDP *:5353
mDNSRespo  234 _mdnsresponder   56u  IPv4 0x36ce91a5436d251d      0t0  UDP *:53
mDNSRespo  234 _mdnsresponder   57u  IPv6 0x36ce91a5436d080d      0t0  UDP *:53
$ warden svc start
Starting traefik   ... done
Starting portainer ... done
Starting dnsmasq   ... error
Starting mailhog   ... done
Starting tunnel    ... done

ERROR: for dnsmasq  Cannot start service dnsmasq: Ports are not available: port is already allocated.
```

Turn Internet Sharing back off, and it stopped listening and works again:

```
$ sudo lsof -nP -iUDP | grep -iE ':(53|5353)$'
mDNSRespo  234 _mdnsresponder    6u  IPv4 0x36ce91a526998ddd      0t0  UDP *:5353
mDNSRespo  234 _mdnsresponder    7u  IPv6 0x36ce91a526998af5      0t0  UDP *:5353
$ warden svc start
Starting traefik   ... done
Starting portainer ... done
Starting dnsmasq   ... done
Starting mailhog   ... done
Starting tunnel    ... done
$ sudo lsof -nP -iUDP | grep -iE ':(53|5353)$'
mDNSRespo  234 _mdnsresponder    6u  IPv4 0x36ce91a526998ddd      0t0  UDP *:5353
mDNSRespo  234 _mdnsresponder    7u  IPv6 0x36ce91a526998af5      0t0  UDP *:5353
com.docke 9172     davidalger  121u  IPv4 0x36ce91a52d010695      0t0  UDP 127.0.0.1:53
```

Your workaround is a good solution perhaps if you need Internet Sharing (or something else that triggers this), but not something I could put into the defaults since it would mess up Valet+ (for those switching back and forth between them) and complicate cross-platform portability.

**Comment by youanden** [comment]
But did you try it on Apple Silicon M1? I don't have internet sharing enabled. 

https://www.loom.com/share/cb55d4587f9a41b4a905647756d5578f

Enabling and disabling it didn't help either.

**Comment by floorz** [comment]
> @ksutha @davidalger I was able to figure it out.
> 
> First, I edited the docker-compose for warden:
> 
> ```
> /usr/local/opt/warden/docker/docker-compose.yml
> ```
> 
> I changed the port mapping for dnsmasq like so:
> 
> ```
>       - "127.0.0.1:5053:53/udp"
> ```
> 
> Then, edited the `test` resolver:
> 
> ```
> sudo vi /etc/resolver/test
> ```
> 
> I just added the port here:
> 
> ```
> nameserver 127.0.0.1
> port 5053
> ```
> 
> Then just restarted dnsmasq:
> 
> ```
> warden svc restart dnsmasq
> ```
> 
> Of course, if it hasn't started fully yet, you can just do:
> 
> ```
> warden svc up
> ```

@youanden Thank you! this worked for me. Without changing the port, I couldn't get to any of the warden svc urls or my local dev urls. Using Apple M1 Max

**Comment by brandontamm** [comment]
This worked for me as well! 

> > @ksutha @davidalger I was able to figure it out.
> > First, I edited the docker-compose for warden:
> > ```
> > /usr/local/opt/warden/docker/docker-compose.yml
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I changed the port mapping for dnsmasq like so:
> > ```
> >       - "127.0.0.1:5053:53/udp"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then, edited the `test` resolver:
> > ```
> > sudo vi /etc/resolver/test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just added the port here:
> > ```
> > nameserver 127.0.0.1
> > port 5053
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then just restarted dnsmasq:
> > ```
> > warden svc restart dnsmasq
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Of course, if it hasn't started fully yet, you can just do:
> > ```
> > warden svc up
> > ```
> 
> @youanden Thank you! this worked for me. Without changing the port, I couldn't get to any of the warden svc urls or my local dev urls. Using Apple M1 Max

@youanden - This worked for me as well! Thank you!

**Comment by mokanfar** [comment]
My solution was following:
 _Originally posted by @youanden in https://github.com/wardenenv/warden/issues/262#issuecomment-748291589_ 

A couple differences:
My file was
`/opt/warden/docker/docker-compose.yml
`
When running 
` warden svc up --force-recreate dnsmasq
`
I was greeted with this error:
`network warden was found but has incorrect label com.docker.compose.network set to "warden"
`
Running this fixes it for me:
`docker network rm warden`
Then running:
`warden svc up --force-recreate
`
 I am on Intel Mac.

**Comment by dannynimmo** [comment]
FYI, looks like the dnsmasq config is now located in: `/usr/local/opt/warden/docker/docker-compose.dnsmasq.yml`

**Comment by DavidLambauer** [comment]
I installed warden via brew. For me the file was located under:

`/opt/homebrew/Cellar/warden/0.14.1/docker/docker-compose.dnsmasq.yml`.

If you still can't find it, just try:

```
find /opt/ -type f -name "docker-compose.dnsmasq.yml"
# or
find /usr/ -type f -name "docker-compose.dnsmasq.yml"
```

**Comment by olivierognn** [comment]
> This worked for me as well!
> 
> > > @ksutha @davidalger I was able to figure it out.
> > > First, I edited the docker-compose for warden:
> > > ```
> > > /usr/local/opt/warden/docker/docker-compose.yml
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I changed the port mapping for dnsmasq like so:
> > > ```
> > >       - "127.0.0.1:5053:53/udp"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then, edited the `test` resolver:
> > > ```
> > > sudo vi /etc/resolver/test
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I just added the port here:
> > > ```
> > > nameserver 127.0.0.1
> > > port 5053
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then just restarted dnsmasq:
> > > ```
> > > warden svc restart dnsmasq
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Of course, if it hasn't started fully yet, you can just do:
> > > ```
> > > warden svc up
> > > ```
> > 
> > 
> > @youanden Thank you! this worked for me. Without changing the port, I couldn't get to any of the warden svc urls or my local dev urls. Using Apple M1 Max
> 
> @youanden - This worked for me as well! Thank you!

This worked also for me, but I have a problem also on traefik on port 443.
Can I do in the same way?

**Comment by micahbule** [comment]
This issue resurfaced with Docker 4.24.0 release.

Here's the fix, instead of patching Warden's internal docker-compose file.
https://docs.docker.com/desktop/release-notes/#for-mac-3

**Comment by diazwatson** [comment]
I have a similar issue on Apple M1 Max but related to `traefik` instead of `dnsmasq`:

```
warden svc up                                                                                                                                           0|1 ✘  system   10:36:37 
[+] Building 0.0s (0/0)                                                                                                                                                                                    docker:orbstack
[+] Running 4/4
 ✔ Container traefik  Created                                                                                                                                                                                         0.0s
 ✔ Container mailhog  Started                                                                                                                                                                                         0.1s
 ✔ Container tunnel   Started                                                                                                                                                                                         0.0s
 ✔ Container dnsmasq  Started                                                                                                                                                                                         0.1s
Error response from daemon: driver failed programming external connectivity on endpoint traefik (bb2e7b0424224d4202a457a80bbd99799ff6300d6e81d2429a6b2eba9ab3398f): Bind for 127.0.0.1:443 failed: port is already allocated
```

I will update this once I manage to fix it.

**Comment by bap14** [comment]
@diazwatson Looks like something is already bound to port 443. Not sure what other apps / services you have running but Traefik can't bind to port 443.

**Comment by diazwatson** [comment]
That was indeed the issue.

In my case it turned out to be [OrbStack](https://orbstack.dev/), what I did to fix it was:
- Stopped all the containers
- Stop warden processes with `warden svc stop`
- Completely close OrbStack and kill all processes related to it
![Screenshot 2023-11-13 at 16 58 46](https://github.com/wardenenv/warden/assets/1080386/2ce92978-c18e-4822-a426-6f9c93241228)
- Re open OrbStack
- `warden svc up`

**Comment by tiagosampaio** [comment]
@youanden your solution worked for me. Thanks for sharing!

**Comment by wojtekn** [comment]
I spotted this issue too, and a workaround from the link posted by @micahbule worked for me.

**Comment by dimohamdy** [comment]
Before running your command, run this command to kill all processes that use port 53 in the terminal like this

```
sudo lsof -t -i :53 | xargs sudo kill -9

warden svc start
```

**Comment by joshfedo** [comment]
The port change worked for me with the only difference being the yml file was located at /System/Volumes/Data/opt/homebrew/Cellar/warden/0.14.2/docker/docker-compose.dnsmasq.yml

**Comment by shawnabramson** [comment]
For anyone that finds issue, I am on a MBP with M3 Max chip and Sonoma OS. I also had the problem where port 53 was not binding. 

This solution, which originated in Docker's release notes, worked for me.

https://docs.docker.com/desktop/release-notes/

```vim ~/Library/Group\ Containers/group.com.docker/settings.json```
Find the line containing ```"kernelForUDP": true``` and change it to ```false```.
Close the file.
Quit docker and restart.
```warden svc down```
```warden svc up```

**Comment by key88sf** [comment]
@shawnabramson I tried your solution but still getting this on Mac OSX:
```
Error response from daemon: Ports are not available: exposing port UDP 127.0.0.1:53 -> 0.0.0.0:0: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
```

Any ideas?

**Comment by ozanhazer** [comment]
"Reset to factory defaults" fixed the issue for me.

**Comment by EspertoMagento** [comment]
I resolve it using orbStack ;)

[https://docs.orbstack.dev/]

**Comment by drdouglasghd** [comment]
> For anyone that finds issue, I am on a MBP with M3 Max chip and Sonoma OS. I also had the problem where port 53 was not binding.
> 
> This solution, which originated in Docker's release notes, worked for me.
> 
> https://docs.docker.com/desktop/release-notes/
> 
> `vim ~/Library/Group\ Containers/group.com.docker/settings.json` Find the line containing `"kernelForUDP": true` and change it to `false`. Close the file. Quit docker and restart. `warden svc down` `warden svc up`


This is now a setting in the Desktop version. Uncheck to free up the port. 


<img width="927" alt="Image" src="https://github.com/user-attachments/assets/72f78c10-865a-401f-a84b-6fd3c53c87aa" />
