### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by qaniel** [davidalger/warden#265]
Hello! I just followed the documentation guide to install magento2 on my local machine, but I can't access any page of the magento2. I get the ERR_TOO_MANY_REDIRECTS and see the infinite loop on the console, any hint on what I could be doing wrong here? o is a problem outside of what I'm doing?

**Comment by davidalger** [comment]
Given what I know of Magento 2, this is most likely an incorrectly configured base URL. You must use a secure, i.e. https URL, and it must be statically configured in Magento config or there are cases where Magento will cache bad info for the config resulting in a redirect loop. You could try using `curl -I` to debug and see what's in the response.

**Comment by qaniel** [comment]
@davidalger ty for your response, I manage to track down the issue. The problem was following the [setup guide](https://docs.warden.dev/environments/initializing.html) I had registered my portal with camel case e.g `warden env-init exampleProject magento2` as you can guess the registered domain was `exampleProject` but magento was expecting the domain of `exampleProject` and since URLs are always downcased it was receiving an `exampleproject` then magento would try to redirect to `exampleProject` creating the infinite loop.
