### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by Ekumfer5** [davidalger/warden#266]
Cloning into '/home/linuxbrew/Homebrew/Library/Taps/davidalger/homebrew-warden'...
fatal: unable to access 'https://github.com/davidalger/homebrew-warden/': Could not resolve hosts: github.com
error: failure while executing; 'git clone https://github.com/davidalger/homebrew-warden /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/davidalger/Homebrew-warden' exited with 128.

I get this error message, and I can reach the webpage from a web browser

**Comment by davidalger** [comment]
> Could not resolve hosts: github.com

Inability to resolve DNS for github.com when Homebrew clones a repository is well outside the scope of this project. Sounds like a deeper issue with your system may be at fault, but I would suggest fixing any issues with DNS resolution and trying again.
