### ISSUE TITLE
db import doesn't fix triggers

### ISSUE THREAD

**Issue by fballiano** [davidalger/warden#271]
Hello everybody, I was starting a magento 2 project and importing a previous database with some triggers.

Warden db import fixes the triggers identifiers (changing the username) but it seems it doesn't change the host, leaving "localhost" instead of the db container name, resulting in errors during the importing phase.

Does anybody have the same problem?

**Comment by davidalger** [comment]
I haven't seen this be an issue TBH, the regex used to do the replace when piping through `warden db import` is here:
https://github.com/davidalger/warden/blob/develop/commands/db.cmd#L37-L40

Particularly this bit:
```
LC_ALL=C sed -E 's/DEFINER[ ]*=[ ]*`[^`]+`@`[^`]+`/DEFINER=CURRENT_USER/g'
```

You could do something similar to strip your db further:

```
cat dump.sql | LC_ALL=C sed -E '...' | warden db import
```

**Comment by davidalger** [comment]
Going ahead and closing this. If you can provide reproducible test case where the output of `mysqldump` fails due to a bad DEFINER statement, feel free to re-open with more details.
