### ISSUE TITLE
"warden svc up" command not working

### ISSUE THREAD

**Issue by PranavPusarla** [davidalger/warden#272]
Hi, I was working on project with Magento 2 installation and using warden for this process.

I'm able to get warden installed but whenever I run the "warden svc up" command, it gives me the error message "ERROR: Docker does not appear to be running. Please start Docker." However, if I check the status of Docker, it says that it is running.

I'm using VirtualBox to run a virtual machine with Linux and am trying to run warden in that virtual machine. I've tried Linux versions Debian 10 and Ubuntu 18.10.

Can anyone help provide some insight on this issue? Thanks

**Comment by prestonchoate** [comment]
We had someone run into this recently. It was solved by changing the docket daemon to run rootless. https://docs.docker.com/engine/security/rootless/

**Comment by davidalger** [comment]
The check to see if Docker is running is pretty simple:
https://github.com/davidalger/warden/blob/develop/utils/core.sh#L37-L42

It's doing nothing more than attempting to run `docker system info`. On macOS there really isn't any reason this should fail if Docker is indeed running, but on Linux it is most likely related to not following the post-installation steps when installing Docker: https://docs.docker.com/engine/install/linux-postinstall/ (specifically, adding your user to the `docker` group, to which running in rootless mode is an alternative so you don't have to use sudo with everything)

**Comment by PranavPusarla** [comment]
Following the post-installation steps of Docker (adding my user to the docker group) worked!
Thank you guys for the help!
