### ISSUE TITLE
Mutagen sync sessions for "local" environment type

### ISSUE THREAD

**Issue by rafashkembi** [davidalger/warden#28]
Hello!

I have a small issue making the mutagen working on macOS using the local environment.
When I try to run the warden sync start I get this:
![image](https://user-images.githubusercontent.com/41292729/67208774-6d329480-f416-11e9-9915-74f3df5a8a4f.png)
Is there any way I can fix this for local environments?

Best Regards,
Rafael

**Comment by davidalger** [comment]
@rafashkembi Would be more than willing to court a PR to implement something if you care to share more regarding the use-case. For now, I'm closing this out as this is not a bug and I'm unclear on what is expected based on the original post.
