### ISSUE TITLE
Problem accessing private repos when composer is executed inside php-fpm

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#283]
When executing composer, or running a bin/magento command that in turn executes composer (e.g. sampledata:deploy), private keys are not available to access any private repos defined in the root composer.json.

How do you handle that?
Would it maybe be an option to mount $HOME/.ssh, similar to how $HOME/.composer is mounted?

**Comment by Den4ik** [comment]
@Vinai you may set github-ouath token at `auth.json` in composer folder. This solved problem for me.

**Comment by springerin** [comment]
@Vinai  I've already asked about this issue, please refer to https://github.com/davidalger/warden/issues/225
There are 2 options, one i suggested, the second in theory out of the box although is doesn't always work for me.

**Comment by Vinai** [comment]
Thanks for the info, looking into this...

**Comment by ihor-sviziev** [comment]
Note - for those who're using WSL2 - you may need to use this in order to have ssh agent running https://esc.sh/blog/ssh-agent-windows10-wsl2/

**Comment by Vinai** [comment]
Thanks for the input, mounting my .ssh dir with .warden/warden-env.yml worked out for me.
