### ISSUE TITLE
Magento 2 environment access to .idea folder for URN

### ISSUE THREAD

**Issue by lfolco** [davidalger/warden#291]
The Magento 2 environment explicitly excludes the `.idea` folder from mutagen. Is there a particular reason for this? As it is, you cannot run the built-in `bin/magento dev:urn-catalog:generate` command because of this without having to do a workaround.

**Comment by davidalger** [comment]
@lfolco This may have simply been an overzealous attempt at ignoring things which didn't need to be synced to avoid sync cycles where unnecessary. Checked `.idea` from an old large M2 project I have laying around, and it's both small and doesn't have a ton of files, so I don't see why this ignore rule needs to be there. It can certainly be removed, appreciate the suggestion.

```
 $ du -hs .idea/
412K	.idea/
```

```
ls -lhR .idea/
total 800
drwxr-xr-x  3 davidalger  admin    96B Jun 20  2020 codeStyles
drwxr-xr-x  4 davidalger  admin   128B Apr 20  2020 inspectionProfiles
-rw-r--r--  1 davidalger  admin   174B Apr 20  2020 misc.xml
-rw-r--r--  1 davidalger  admin   260B Apr 20  2020 modules.xml
-rw-r--r--  1 davidalger  admin   160K Jun 18  2020 php.xml
-rw-r--r--  1 davidalger  admin    56K Jun 18  2020 <redacted>.iml
-rw-r--r--  1 davidalger  admin   180B Apr 20  2020 vcs.xml
-rw-r--r--  1 davidalger  admin   168K Aug 17 17:56 workspace.xml

.idea//codeStyles:
total 8
-rw-r--r--  1 davidalger  admin   149B Jun 20  2020 codeStyleConfig.xml

.idea//inspectionProfiles:
total 16
-rw-r--r--  1 davidalger  admin   605B Apr 20  2020 Project_Default.xml
-rw-r--r--  1 davidalger  admin   128B Apr 20  2020 profiles_settings.xml
```
