### ISSUE TITLE
Set MAGE_DEBUG_SHOW_ARGS?

### ISSUE THREAD

**Issue by sprankhub** [davidalger/warden#292]
It could be a nice addition to set the environment variable `MAGE_DEBUG_SHOW_ARGS` to have nicer debug output. See https://github.com/magento/magento2/search?q=MAGE_DEBUG_SHOW_ARGS&type=code.

What do you think?

**Comment by davidalger** [comment]
Seems like it could be useful, ideally able to be configured if necessary. Either would need to be added to `environment` in the docker-compose config for php-fpm, or could be added via the magento2.conf in the nginx image.

**Comment by norgeindian** [comment]
@davidalger , something similar would be also great for Magento1 with setting `MAGE_IS_DEVELOPER_MODE`.
I addded `- MAGE_IS_DEVELOPER_MODE=1` to `environments/magento1/magento1.base.yml`, but that did not help.
I also tried it at `environments/includes/php-fpm.base.yml`, but that also did not change anything. 
Finally I added `fastcgi_param MAGE_IS_DEVELOPER_MODE=1` to `images/nginx/context/etc/nginx/available.d/magento1.conf` Still no change.
I obviously did not understand the logic here.
So please be so kind and give me a hint, where I could try it, then I will be happy to prepare a pull request for both variables.
