### ISSUE TITLE
Add Varnish 6.4 Support

### ISSUE THREAD

**Issue by norgeindian** [davidalger/warden#294]
As Magento2 now supports Varnish 6.4, it would be great, if this could be included here as well.

**Comment by davidalger** [comment]
Just as a side-note, although Magento supports 6.4 (which is good) I'd personally recommend sticking to 6.0 LTS (which is the image already present here) unless you need something in 6.4 as the 4.x versions are deprecated fairly quickly leading to a good bit of churn: https://varnish-cache.org/docs/index.html

That said, I just pushed a PR to add both 6.4 and 6.5 images for use with Warden :) Should be built and on Docker Hub by the time you get this.

**Comment by norgeindian** [comment]
@davidalger ,thanks a lot, that's great.
