### ISSUE TITLE
Add possibility to switch between Composer 1 and Composer 2

### ISSUE THREAD

**Issue by norgeindian** [davidalger/warden#296]
Magento 2.4.1 supports only Composer1 whereas Magento 2.4.2 supports Composer 2 as well.
So it would be great if this could be a setting to switch between the versions

**Comment by Den4ik** [comment]
@norgeindian composer1 and compose2 alredy preinstalled.
You may use it by `composer` or `composer2` commands

**Comment by norgeindian** [comment]
@Den4ik , just tried it. Does not work in the warden shell.
Even in the current develop branch, `composer2` is not found

**Comment by Den4ik** [comment]
@norgeindian Looks like you have older pulled docker images. Please, try to pull latest
Just checked with latest image
`docker run --rm -it wardenenv/php-fpm:7.2 bash`

Command to help update all pulled images:
`docker images | grep -v REPOSITORY | awk '{image=$1":"$2; print image}' | xargs -L1 docker pull`

**Comment by norgeindian** [comment]
@Den4ik , thanks a lot for the hint. You are right, now it works.
Anyway, @davidalger , what do you think about adding a general env setting here, so that the composer version for each environment is fixed?
Maybe that could be done in `images/php-fpm/Dockerfile`?

**Comment by davidalger** [comment]
@norgeindian @Den4ik This is a wonderful idea. Added support for this to the image entrypoint. See #300 for details on it. Next steps is to update all usages of php-fpm based images in docker-composer config to pass the value through, should be relatively simple to do.

I grok the awk/xargs usage above to pull all the images. :) Pro-tip: If you only want to pull latest images used by a given environment: `warden env pull` will do the trick, then the usual `warden env up` to recreate containers with the new images.

**Comment by davidalger** [comment]
`COMPOSER_VERSION=2` in the `.env` file will now cause 'composer' in the container to be v2 instead of v1. The default remains v1 due to v2's newness and to ensure compatibility. It may be changed to default v2 at some point in the future once folks have had more time to update and use it.

**Comment by Brengineer** [comment]
I'm not sure if something is hard-coded here, but when I have `COMPOSER_VERSION=2.1` (as required by Magento 2.4.4) in my `.env` file, the version is still 1.x in the Warden shell. However, if I revert to exactly `COMPOSER_VERSION=2` in the `.env` file, then the version is 2.x in the Warden shell (after running `$ warden env up` of course).

**Comment by alinalexandru** [comment]
That variable just swich composer version from 1.x to 2.x There is no
functionality to specify the composer version exactly (like 2.1,2.2, etc)

**Comment by sohelrana09** [comment]
How to make a specific composer version @alinalexandru? Did you manage @Brengineer?

**Comment by alinalexandru** [comment]
You can not run a specific version. You can specify to use composer 1.x or 2.x by setting in `.env` the variable `COMPOSER_VERSION`

If you set `COMPOSER_VERSION=2`, the composer version will be `2.2.5`, at this moment. 
If you set `COMPOSER_VERSION=1`, the composer version will be `1.10.23`, at this moment. 

If you need a specific version, there are 2 options:
- create your one image, and use them
- install required composer version after each `warden env up`.

**Comment by sohelrana09** [comment]
Thanks @alinalexandru. Our case composer version is 2.3 when we checkout master branch which cause the installation problem for M2.4.4. Not sure which warden version we use for composer 2.2.x.

**Comment by alexandrosk** [comment]
Is there a way to specify 2.2.10 when using COMPOSER_VERSION=2 instead of 2.3 ?

**Comment by navarr** [comment]
> Is there a way to specify 2.2.10 when using COMPOSER_VERSION=2 instead of 2.3 ?

You can specify `2.2` to get the latest 2.2.x
