### ISSUE TITLE
Space in parent folder breaks .warden/warden-env.yml

### ISSUE THREAD

**Issue by fooman** [davidalger/warden#3]
I haven't been able to work out yet exactly where it happens but thought I document it here. I came across this while trying out `.warden/warden-env.yml`. After creating this file all `warden env` commands failed with a command not found. And the command would show from the last space in the full path, ie this
`/Users/name/Projects/With Space/magento2/.warden/warden-env.yml`
would have split at Space.

**Comment by davidalger** [comment]
@fooman Thanks for reporting this. This should be resolved in the Warden 0.1.5 release which I just pushed out a few moments ago. The solution was to have `DOCKER_COMPOSE_ARGS` be an array allowing each element to be quoted when it is passed along to docker-compose, avoiding the space in any path from splitting the argument.
