### ISSUE TITLE
How to add additional php-extension i.e: APCu 

### ISSUE THREAD

**Issue by meminuygur** [davidalger/warden#306]
I really loved warden, it makes me easily up multiple projects same time.
I am trying to create akeneo pim project using warden env. 
But it needs APCu php extension. 

 I tried to add this `images/php-fpm/Dockerfile` but did not work.

`
RUN pecl install apcu \
    && pecl install apcu_bc-1.0.3 \
    && docker-php-ext-enable apcu --ini-name 10-docker-php-ext-apcu.ini \
    && docker-php-ext-enable apc --ini-name 20-docker-php-ext-apc.ini
`

**Comment by ihor-sviziev** [comment]
You can create your own Dockerfile and use it, our example for installing a snappy PHP extension was following:
```dockerfile
ARG PHP_VERSION=7.3
ARG IMG_SUFFIX=magento2-debug3

FROM docker.io/wardenenv/php-fpm:${PHP_VERSION}-${IMG_SUFFIX}

USER root

RUN yum install -y php-snappy \
    && yum clean all \
    && rm -rf /var/cache/yum

USER www-data
```

So I believe you can try to run `yum install -y php-apcu`

**Comment by meminuygur** [comment]
@ihor-sviziev thank you ! I will try and update the issue.

**Comment by tdgroot** [comment]
@meminuygur Aside from what @ihor-sviziev explained, I think you need to install the `php-pecl-apcu` package:
``` shell
dnf install php-pecl-apcu
# use yum install php-pecl-apcu if you're on an older image
```
