### ISSUE TITLE
Xdebug max nesting level

### ISSUE THREAD

**Issue by antoniocarboni** [davidalger/warden#313]
I have an error on xdebug for max limit nesting level.
I'm trying to set warden-env.yml to change that parameter like this but it doesn't work:

`version: "3.5"
services:
    php-fpm:
       environment:
           XDEBUG_MAXNESTING_LEVEL: 1000`
or
`version: "3.5"
services:
    php-debug:
       environment:
           XDEBUG_MAXNESTING_LEVEL: 1000`

**Comment by davidalger** [comment]
PHP doesn't read settings from environment variables. See the example on #198 for an example of how one can customize settings on a per-project basis within the containers.

**Comment by antoniocarboni** [comment]
Oh sorry, in my research I missed that issue/example. Perfect was what I needed! 
thank you!
