### ISSUE TITLE
Fatal error: Allowed memory size of 2147483648 bytes exhausted - on sample data:deploy for magento 2 env

### ISSUE THREAD

**Issue by pandemicGander** [davidalger/warden#314]
https://github.com/davidalger/warden/blob/develop/images/php-fpm/context/etc/php.d/01-php.ini#L4

What's the recommended way to change `memory_limit = 2G` to a higher value for a magento 2 environment. e.g. I could bash onto the docker container update it manually, but would be nice to have an automated way I could set this to a higher value when I run `warden svc up`.

**Comment by davidalger** [comment]
See #198 for an example of how to do this.
