### ISSUE TITLE
Share db between projects

### ISSUE THREAD

**Issue by rafaelpatro** [davidalger/warden#316]
Hi guys. I'm using Warden to manage a Magento 1 network and a Magento 2 network.

But my Magento 2 project requires connecting to the database of my Magento 1 project for migration purposes.

How can I do that?

**Comment by sprankhub** [comment]
Not sure if this is the nicest way, but you can:

1. Log into the Warden nginx container via `warden shell`.
2. Connect to MySQL as a `root` user: `mysql -h db -u root -pmagento` (the password for `root` is also `magento`).
3. Do anything you want like creating a new database `magento-1`.

**Comment by lbajsarowicz** [comment]
The connectivity should be possible using the same hostnames that you use to configure the Database IDE connection. For example `m1_db_1` as a hostname, you are connecting.

**Comment by davidalger** [comment]
The approach I typically would take for a scenario like this would be to create multiple databases in the M2 site's db container. You can actually still use the `warden db ..` commands as any args are passed through to mysql command:

```
$ warden db connect -uroot -e 'create database magento1_source'
$ warden db connect -uroot -e 'create database magento2_target'
$ warden db connect -uroot -e 'show databases'
+--------------------+
| Database           |
+--------------------+
| information_schema |
| magento            |
| magento1_source    |
| magento2_target    |
| mysql              |
| performance_schema |
+--------------------+
```

The alternate approach @lbajsarowicz is suggesting will as well, but keep in mind to do that you'll need to link the network from the M1 environment to the M2 php-fpm container, afterwhich connecting to either from within the M2 environment will work just fine:

```
$ mkdir m1ex && (cd m1ex; warden env-init m1ex magento1; warden env up 2>/dev/null >&2)
$ mkdir m2ex && (cd m2ex; warden env-init m2ex magento2; warden env up 2>/dev/null >&2)
$ docker network ls | grep 'm[0-9]ex'
5a93974bdabd   m1ex_default        bridge    local
90c1d480b9a1   m2ex_default        bridge    local
$ docker network connect m1ex_default m2ex_php-fpm_1
$ cd m2ex/
$ warden shell
www-data@m2ex-php-fpm:/var/www/html$ mysql -hm2ex_db_1 -umagento -pmagento --vertical -e 'show databases'
*************************** 1. row ***************************
Database: information_schema
*************************** 2. row ***************************
Database: magento
www-data@m2ex-php-fpm:/var/www/html$ mysql -hm1ex_db_1 -umagento -pmagento --vertical -e 'show databases'
*************************** 1. row ***************************
Database: information_schema
*************************** 2. row ***************************
Database: magento
www-data@m2ex-php-fpm:/var/www/html$ exit
```

**Comment by rafaelpatro** [comment]
Amazing! Save my day
