### ISSUE TITLE
ERROR: for {WARDEN_ENV_NAME}_php-fpm_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=120)

### ISSUE THREAD

**Issue by rootindex** [davidalger/warden#319]
I am reporting this bug for users who experience the same within the warden community, no action required. This seems to be a mac related problem. My solution was to upgrade docker for mac to the latest version 3.2

Increasing the timeout limit had no effect, starting a new project was unsuccessful too.

This bug was introduced on my system on magento1 after I customised the config at `.warden/warden-env.yml` (added elasticsearch, no changes to fpm)

```
Recreating retired_php-fpm_1     ...

ERROR: for retired_php-fpm_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=120)

ERROR: for php-fpm  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=120)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
```

**Comment by davidalger** [comment]
When this sort of error occurs, restarting Docker Desktop is generally sufficient. It's an upstream bug which causes docker to hang within the VM in which Docker Desktop runs things and is something I've seen happen spontaneously.
