### ISSUE TITLE
Sync vcs files between warden and host

### ISSUE THREAD

**Issue by sebastian-ehrling** [davidalger/warden#321]
Hi @davidalger 

is it possible to sync git vcs files between macOS host and warden php container? 
I've create a some private magento extensions and I want to install them via composer. This work's fine. 

But when I run composer install or update inside the warden shell, the necessary .git folder will not be synced to my mac hosts.

I've found this in the magento mutagen config file. It is possible to set the parameter vcs=true?
https://github.com/davidalger/warden/blob/develop/environments/magento2/magento2.mutagen.yml#L8

---
sync:
  defaults:
    mode: two-way-resolved
    watch:
      pollingInterval: 10
    ignore:
      vcs: true

**Comment by davidalger** [comment]
@sebastian-ehrling Removing the ignore on VCS files isn't something I plan to do. Syncing VCS files can slow down the sync dramatically, especially for projects with an incredibly long history, or where large files (such as database dumps) have accidentally been added in past git commits resulting in bloated object files.

There are however two workarounds that may work for you:

a) Use the `WARDEN_SYNC_IGNORE` setting in the `.env` file with a negative ignore rule to explicitly include the .git directory withing vendor (I haven't tried this to see if it works with ignore.vcs==true setting intact). See more on #142 

b) Override the mutagen sync configuration by copying the default config (linked in your post) to `.warden/mutagen.yml`. See more on #246
