### ISSUE TITLE
Any plans to add MYSQL 8 Image?

### ISSUE THREAD

**Issue by orionpt** [davidalger/warden#322]
Cheers, do you have any plans to include an option for a MYSQL 8 Image?

Since Magento 2.4 suggests MySQL 8.0 for on-premise installations it would be nice to have the option to deploy a MYSQL 8 image.

**Comment by davidalger** [comment]
Resolved in b1034297. Images are available for MySQL 8.0, and I added MariaDB 10.5 while I was at it.

**Comment by sebastian-ehrling** [comment]
Hi @davidalger 
it is possible to add this option to mysql 8 container per default? Otherwise magento 2 get an error by creating triggers
log_bin_trust_function_creators=ON
