### ISSUE TITLE
Specifying COMPOSER_VERSION=2 in .env doesn't seem to work

### ISSUE THREAD

**Issue by erfanimani** [davidalger/warden#323]
# Steps to reproduce

* Add `COMPOSER_VERSION=2` to `.env` file.
* Run `warden env down && warden env up -d`
* Run `warden shell`
* Run `www-data@pacvac-php-fpm:/var/www/html$ composer --version`

## Expected result

        Composer version 2 [...]

## Actual result

    Composer version 1.10.19 2020-12-04 09:14:16

It's expected because of this commit: https://github.com/davidalger/warden/commit/b64fd71c376a1af5def964072cf5d35d9b16ebec

**Comment by sprankhub** [comment]
This does work for us, so I do not expect a general bug here.

What does `warden version` output? Are you using 0.10.0 or later?

Try running `warden env pull` to update the underlying Docker images. Additionally, try adding the `--force-recreate` flag to `warden env up`.

**Comment by erfanimani** [comment]
Hmm, you're right, the `--force-recreate` flag seems to have fixed it! Thanks
