### ISSUE TITLE
Port 53 in use in M1 Docker

### ISSUE THREAD

**Issue by RA-nateblanchette** [davidalger/warden#326]
M1 build of docker is facing an issue with port 53 being reserved. This is preventing dnsmasq from starting in the case of Warden on the m1 build of Docker for mac. See [this issue on the docker Github](https://github.com/docker/for-mac/issues/5335)

A solution is offered in the issue thread as well, which is to bind the port to an IP like 127.0.0.1.

**Comment by RA-nateblanchette** [comment]
Fixed in the latest docker.

**Comment by RA-nateblanchette** [comment]
I was in error, as mentioned in the linked issue. This is still an issue for anyone trying to setup Warden on an M1 mac with the Docker technical preview.

Posting here for visibility, I do realize it's something the docker team needs to fix (not Warden). Best case on this end is considering a workaround.

**Comment by davidalger** [comment]
https://github.com/davidalger/warden/issues/327#issuecomment-804184284
