### ISSUE TITLE
Not work with Apple M1 Chip

### ISSUE THREAD

**Issue by bonzinho** [davidalger/warden#327]
This not work with Apple m1 Chip, dnsmask can not start because por 53 already in use.

**Comment by youanden** [comment]
@bonzinho See my comment here with a workaround:
https://github.com/davidalger/warden/issues/262

Actually, the M1 docker preview release candidate update yesterday finally mentions this:

![image](https://user-images.githubusercontent.com/183880/111851432-7fee1900-88e9-11eb-9062-a92b90b3597e.png)

You can read the known issues here:
https://docs.docker.com/docker-for-mac/apple-m1/

**Comment by stefanskotte** [comment]
Just want to answer from M1 perspective. As of todays date dnsmasq works fine:

b3e0efe0c6d9   jpillora/dnsmasq                       "/bin/sh -c ' echo \"…"   9 minutes ago   Up 9 minutes   127.0.0.1:53->53/udp                                                   dnsmasq

Webservice also works perfectly.
![image](https://user-images.githubusercontent.com/521625/119131252-83149b00-ba39-11eb-9de5-2c9212185606.png)

**Comment by davidalger** [comment]
@stefanskotte Super cool, appreciate the update for everyone here.

**Comment by sndrgb** [comment]
Someone resolve this?

**Comment by youanden** [comment]
@sndrgb Looks like newer version of Mac OS X virtualization framework no longer binds directly to :53 so this shouldn't be an issue any more.
