### ISSUE TITLE
Sporadic ERR_NETWORK_CHANGED Issues

### ISSUE THREAD

**Issue by sprankhub** [davidalger/warden#338]
I am using Warden on Ubuntu 20.04 (and absolutely love it btw). However, I have one issue that bugs me multiple times a day. For specific requests, I sometimes get an `ERR_NETWORK_CHANGED` error. This takes time, because I need to reload the page and it also leads to errors, which are hard to get if e.g. one specific resource cannot be loaded due to that error.

To be honest, I have no idea where it comes from, but I am pretty sure it comes from Warden as I struggle with it since I installed Warden. Any idea or help is highly appreciated :pray:

**Comment by davidalger** [comment]
I'm not really sure what would cause this (not a Chrome user, so I haven't seen it, but I also haven't heard of it being a possible issue before either). There are a lot of possible things to try for resolving it here: https://www.troubleshootingcentral.com/how-to-fix-the-err-network-changed-error-in-google-chrome/

Also found this Super User article where one Ubuntu user said disabling IPv6 resolved this type of issue for them: https://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome

It's possible it could be related to running docker somehow, or some change in network configuration, but what exactly I have no idea nor where to start on this one.

**Comment by adrifkat** [comment]
I have the same problem on Ubuntu 20.04.2 with magento2 type environment

**Comment by danslo** [comment]
Same issue here, haven't been able track it down yet.

**Comment by danslo** [comment]
Disabling ipv6 via grub boot flag resolved this for me. See [here](https://askubuntu.com/a/1210959).

**Comment by sprankhub** [comment]
This indeed seems to work. Thanks, @danslo! Does not feel nice to disable IPv6, but if it resolves the issue, I am currently fine with it :D

**Comment by ihor-sviziev** [comment]
@sprankhub,
Could you check if the workaround from https://github.com/davidalger/warden/issues/431 will help you?

**Comment by sprankhub** [comment]
At least I can confirm that my log looks the same (as in, Portainer restarts every five minutes). However, since disabling IPv6 resolved the issue for me, I do not really want to check the issue again unless it would really help you.
