### ISSUE TITLE
issue related resolve elasticsearch host

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#340]
Somehow while following setup container by warden i got this issue
My Magento 2.3 Project used elastic suite from SMILE (Not elasticsearch default by magento). I have followed install env with php73 and only use elasticsearch (7.6) no varnish and messagequeue only used default fullpage
Every setup and run. Elastic run but i'm not sure magento can't ping to this
I got status indexer like this 
elasticsuite_quote_fulltext view does not exist.

browser with this url 
https://elasticsearch.project.test <= response some json data in browser
mmem is name project
{
  "name" : "mmem-elasticsearch",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "nMt7cgqwRVS9WORfWxbyVA",
  "version" : {
    "number" : "7.6.2",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "ef48eb35cf30adf4db14086e8aabd07ef6fb113f",
    "build_date" : "2020-03-26T06:34:37.794943Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

but when i used elasticsearch:9200 for config from backend (at the end search still not work)
127.0.0.1:9200 not work or show any response

warden env logs -f elasticsearch show responses but seem not help much

Frontend test
https://app.mmem.test/catalogsearch/result/?q=tesT show error
Exception #0 (LogicException): catalog_product index does not exist yet. Make sure everything is reindexed.

docker ps -f name=elasticsearch
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS          PORTS                NAMES
c29e0e38ec9e   wardenenv/elasticsearch:7.6   "/usr/local/bin/dock…"   38 minutes ago   Up 38 minutes   9200/tcp, 9300/tcp   mmem_elasticsearch_1

Used warden version 0.10.1
I got issue when setup project
Clone source code along with magento (no env.php available at the moment). This source contain all magento codebase + smile elasticsuite
Then after that i import my dev db for my project (2 dbs one for magento and other contain products for elastic search). Is this project support 2 db work under one project ?
Every set after run setup:install but i got error "No node alive" in terminal or sometimes no error but frontend not work with elasticsearch functional because somehow elastic container may not running

**Comment by mrtuvn** [comment]
cc: @davidalger

**Comment by mrtuvn** [comment]
May out of scope of this but should we have extra docs for how to setup warden for projects with git source + multiple db imports ?

**Comment by mrtuvn** [comment]
![Screenshot from 2021-04-03 13-44-12](https://user-images.githubusercontent.com/1908873/113470844-b8156000-9482-11eb-8a9f-f817a332a8d7.png)

**Comment by ihor-sviziev** [comment]
Hi @mrtuvn,
Inside PHP-FPM containers (`warden shell`), you should use the following command:
```bash
curl http://elasticsearch:9200/
```


Outside php-fpm container we're using traefic global service on port `elasticsearch.contribution.test:443` to the `elasticsearch:9200` inside the `contribution` project. 
```bash
curl https://elasticsearch.contribution.test/
```

**Comment by mrtuvn** [comment]
Thank you for the clarify
