### ISSUE TITLE
Improve support for symfony

### ISSUE THREAD

**Issue by alinalexandru** [davidalger/warden#347]
I am trying to start a Symfony proiect and I have noticed some problems. Probably support for SF was not a priority.

- [ ] Add support for blackfire
- [ ] Add default ELASTICSEARCH_VERSION in .env
- [ ] Nginx support for Symfony < 4 https://symfony.com/doc/current/setup/web_server_configuration.html vs https://symfony.com/doc/3.4/setup/web_server_configuration.html. Probably new nginx template needs to be added.
- [ ] Support for symfony developer mode
- [ ] Mutagen?

**Comment by davidalger** [comment]
>  Nginx support for Symfony < 4

If you're starting a new Symfony project, why would you not start with a more current and maintained version of Symfony?

Would be happy to see PRs adding support for Blackfire, docs on using Eleasticsearch with Symfony, etc, but adding support for unmaintained old versions of frameworks is not something I intend to do here.

You're also welcome to mount a custom Nginx template into the nginx container yourself however to accomplish whatever changes you require for your project using info from these pages as a guide:

* https://github.com/davidalger/warden/issues/325
* https://docs.warden.dev/environments/customizing.html#php-specific-customizations

> Mutagen?

See here: https://github.com/davidalger/warden/issues/203#issuecomment-677774991

**Comment by alinalexandru** [comment]
I am not starting a new project. I want to migrate an existing one from vagrant to docker with warden.
I agree with you regarding Symfony versions <4. 

I will create a custom nginx template inside my project.
I will submit only the setting for Blackfire and ElasticSearch.

**Comment by davidalger** [comment]
> I am not starting a new project

Gotcha, my bad, I read "trying to start a Symfony proiect" the wrong way then. :)

> I will create a custom nginx template inside my project.

After glancing at the docs you linked, you might try putting the following in a `.warden/warden-env.yml` file (in the project root) to override the NGINX_PUBLIC variable to use web vs public dir. Not sure if it's the only Nginx change they're asking for, but at a glance it appears it could be

```
version: "3.5"
services:
  nginx:
    environment:
      - NGINX_PUBLIC=/web
```

>  I will submit only the setting for Blackfire and ElasticSearch.

Sounds good.
