### ISSUE TITLE
Varnish and Elasticsearch don't start on Apple M1

### ISSUE THREAD

**Issue by antonio-vitale** [davidalger/warden#348]
Hello, i'm trying to create a magento 2 enviroment but Varnish (6.0) and Elasticsearch (7.6, 7.10, 7.12) don't start.
There are the logs.

##### Elasticsearch
<pre>
Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/elasticsearch/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 232, exit value: 1
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:114)
at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 232, exit value: 1
at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
... 6 more
</pre>

##### Varnish
<pre>
Error:
Running VCC-compiler failed, signal 5
VCL compilation failed
</pre>

**Comment by davidalger** [comment]
@stefanskotte There is a much simpler way of disabling varnish if that's something you want to do as a workaround:

1. Set `WARDEN_VARNISH=0` in the project `.env` file (this is likely in the file, but set to `1` which is default for some env types)

2. Update cleaning up the orphan container: `warden env up --remove-orphans`

This will completely remove the `varnish.base.yml` config from what's used.

**Comment by stefanskotte** [comment]
Ah excellent - I must have missed that digging through all the configs :)  - THANKS!

**Comment by sankharay** [comment]
i have seen same issue but somehow. i am not able to connect with elasticsearch

`           Name                          Command               State     Ports  
--------------------------------------------------------------------------------
vcarepro_db_1                 docker-entrypoint.sh mysql ...   Up       3306/tcp
vcarepro_elasticsearch-hq_1   supervisord -c /etc/superv ...   Up       5000/tcp
vcarepro_elasticsearch_1      /usr/local/bin/docker-entr ...   Exit 1           
vcarepro_nginx_1              /bin/sh -c envsubst '${NGI ...   Up       80/tcp  
vcarepro_php-debug_1          docker-entrypoint php-fpm        Up       9000/tcp
vcarepro_php-fpm_1            docker-entrypoint php-fpm        Up       9000/tcp
vcarepro_rabbitmq_1           docker-entrypoint.sh rabbi ...   Exit 0           
vcarepro_redis_1              docker-entrypoint.sh redis ...   Up       6379/tcp
`

**Comment by sohelrana09** [comment]
What is the solution if this? Elastic and Varnish both are broken.

**Comment by sebastian-ehrling** [comment]
@sohelrana09  I have migrated to ddev. This works

**Comment by sohelrana09** [comment]
https://github.com/drpayyne/warden-multi-arch -> this repo working fine with Apple M1.

**Comment by convenient** [comment]
I am having luck building my own multi arch images for older versions of elasticsearch and varnish.

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

1. Start with a multi arch debian image
2. Install what you need, either from `apt` or source depending on what it is
3. Build your multi arch image https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

I've got my magento2 instances up and running now. Don't need docker platform emulation for anything other than our mysql versions so far.

**Comment by celorodovalho** [comment]
+1

**Comment by NicolasFritz** [comment]
any solution ?

**Comment by fooman** [comment]
Just leaving a few notes here in case they help someone else. I am not 100% sure what finally made our cross built images for our complete setup work. (the elasticsearch startup in our arm64 builds still does take a long time so it's not perfect).

- The elasticsearch bundled jdk came up with errors around spawning a process similar to the OP. I ended up swapping to the jdk from the distro and instructed elasticsearch to use it with ES_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-%%TARGETARCH%%
- I encountered memory errors on starting elasticsearch - again mostly during the crossbuild process of our images. The below changes helped:

```
  echo "bootstrap.system_call_filter: false" >> /etc/elasticsearch/elasticsearch.yml
  echo "discovery.type: single-node" >> /etc/elasticsearch/elasticsearch.yml
  echo "xpack.security.enabled: false" >> /etc/elasticsearch/elasticsearch.yml
  echo "bootstrap.memory_lock: true" >> /etc/elasticsearch/elasticsearch.yml
  echo "network.host: 127.0.0.1"  >> /etc/elasticsearch/elasticsearch.yml
  echo "indices.memory.index_buffer_size: 20%" >> /etc/elasticsearch/elasticsearch.yml

  echo "* hard memlock unlimited" >> /etc/security/limits.conf
  echo "* soft memlock unlimited" >> /etc/security/limits.conf
  echo "session required pam_limits.so" >> /etc/pam.d/common-session
```

```
ES_JAVA_OPTS="-Xms1024m -Xmx1024m -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=50 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.pidfile=/var/run/elasticsearch/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch
```

**Comment by convenient** [comment]
@fooman I got multiarch images working for older elasticsearch versions like this, for newer elasticsearch version I use the official multiarch image.

Recently I needed a multiarch image of Elasticsearch 6.5 

1. Clone this repo and go into this directory https://github.com/blacktop/docker-elasticsearch-alpine/tree/master/6.5
2. Run the following commands (replace `YOURNAMESPACE`) to build a muiltiarch image that does `linux/amd64` and `linux/arm64`

```
cd ../6.5.4
docker buildx create --name mybuilder --use
docker buildx build -t YOURNAMESPACE/elasticsearch:6.5.4 --platform linux/amd64,linux/arm64 --push . 
docker buildx stop mybuilder
docker buildx rm mybuilder
```

I've not used it much yet, but the container boots up just fine and is pretty quick. No emulation needed or anything.

**Comment by ihor-sviziev** [comment]
I believe after https://github.com/davidalger/warden/pull/505 this issue is resolved.
You should just run 
```
warden env pull
warden env up --force-recreate # ensure all containers are running native on arm64 where available
```
Note: php-fpm images still works slow

**Comment by davidalger** [comment]
Couple notes adding to what @ihor-sviziev said:

* Elasticsearch 7.0+ has ARM native images
* Varnish 6.0 (LTS) and 6.5+ have ARM native images

If using Varnish 6.4 or 4.1, I would recommend changing the version to 6.0 (an lts release). Similarly, if using Elasticsearch 6.x, updating to ES 7.x will be required for ARM support.
