### ISSUE TITLE
How to assign elasticsearch more diskspace

### ISSUE THREAD

**Issue by Vinai** [davidalger/warden#352]
Noob question, soory.
I'm running into the issue that elastic is setting read-only-allow-delete because it's running out of disk space.
When running `bin/magento setup:upgrade`, as soon as it hits the configurable products recurring setup script (it updates the index), or when running `bin/magento index:reindex catalog_search` I get the error

```
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "index [magento2_product_1_v37] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "index [magento2_product_1_v37] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"
  },
  "status": 403
}
```
Google said to try
```
curl -XPUT -H "Content-Type: application/json" http://elasticsearch:9200/_all/_settings?pretty -d '{"index.blocks.read_only_allow_delete": null}'
```

But that only fixes the issue for a minute or so.

The issue is described nicely here:
https://stackoverflow.com/questions/48155774/elasticsearch-read-only-allow-delete-auto-setting/56143760

I need to clear up some diskspace or give it more diskspace for `esdata:/usr/share/elasticsearch/data:rw`.

How do I do that?

**Comment by navarr** [comment]
Hi @Vinai, not a definitive answer but in my current experience all stores simply auto expand up to the allowed amount of disk space for docker total.

This is available to be edited in settings of docker desktop if you're using it. 

If you're using Mac, this article provides some great insights for expanding and recovering space from docker

https://docs.docker.com/docker-for-mac/space/

**Comment by Vinai** [comment]
Thank you @navarr, that was spot on and super helpful!

**Comment by norgeindian** [comment]
@navarr , thanks for sharing that link. Seems to be a great solution for Mac. Do you know by chance also a way to fix that on Ubuntu, as I have similar issues.

**Comment by navarr** [comment]
@norgeindian I'm not as familiar, no.  My expectation is that docker for linux wouldn't care about disk space at all and would utilize whatever is available on the mount it is on.

There is [a helpful article of commands for managing docker's used diskspace](https://docs.docker.com/engine/reference/commandline/system_df/) but that's the extent of my knowledge for Linux

**Comment by davidalger** [comment]
> docker for linux wouldn't care about disk space at all and would utilize whatever is available on the mount it is on

This is accurate. The issue with space that sometimes comes up generally has to do with partitioning schemes that, for example (and this is pretty common for desktop/workstation installations), allocate the majority of allocatable free space to `/home` with a (relatively) small amount allocated to `/` (which includes what's under `/var` where Docker containers, volumes, etc are located).

Using `docker system df` (as @navarr linked to) to find out what is taking up the space and / or `docker system prune` to basically garbage collect will only get you so far if `/` is fairly small. You can run `df -h /var/lib/docker` to see what drive it's located on, and how large the partition is.

On my linux box, I have `/var/lib/docker` running on it's very own separate 150GB partition both for the additional space as well as so [I can use `nobarrier` for better I/O performance](https://davidalger.com/posts/mysql-write-performance-and-io-barriers/) without potentially compromising the integrity of anything under `/home`. As long as you're not wanting to optimize with mount flags such as `nobarrier`, moving `/var/lib/docker` to somewhere under `/home` (there are quite a few different methods of doing this, symlink, docker config, etc; easy google search will find them) so it'll share the main partition would be another easy option that wouldn't require adjusting partition tables.
