### ISSUE TITLE
How create and import second database with warden command

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#353]
This may not a issue
Example i want extra database work along with default (magento db)
How i can create/import db to that with convenient command same as command warden db import like document describe
Normal work flow is
1. Have db file
2. Create new second db with privileges of user magento
3. Import db file to that db

**Comment by sprankhub** [comment]
I think https://github.com/davidalger/warden/issues/190#issuecomment-656973560 should answer your question :)

**Comment by mrtuvn** [comment]
Thank you for response but can we use this command with argument like below
warden db import "second-dbname" for example ?

**Comment by sprankhub** [comment]
No, you have to do this manually.

**Comment by mrtuvn** [comment]
Thank you for clarify
