### ISSUE TITLE
PHP containers don't start

### ISSUE THREAD

**Issue by jahvi** [davidalger/warden#367]
I just pulled the latest `0.11.0` version of warden and now I'm getting the following errors in both php-fpm and xdebug containers that prevent them from starting:

```
sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr='mailhog:1025'"
sudo: n: command not found
```

The problem seems related to this line where it tries to change the Node version:
https://github.com/davidalger/warden/blob/684d248b3cfa6eecc56542db450319a6e803af6e/images/php-fpm/context/docker-entrypoint#L34

If I remove the `NODE_VERSION=14` line from my `.env` file it works as expected. Looks like for some reason `n` is not installed in the image.

This works fine on another project using 0.10.0.

**Comment by davidalger** [comment]
@jahvi Seems this would happen when `NODE_VERSION` different than that backed into the images is specified in a project's `.env` as that is what triggers the `sudo n "${NODE_VERSION}"` call that is failing.

As to why it's happening now and wasn't before, I'm not sure. Latest EL 7 and 8 both have identical `secure_path` settings in `/etc/sudoers` Regardless though, it's an easy fix, which I'm about to push a change for so the docker-entrypoint will instead run `sudo /usr/local/bin/n "${NODE_VERSION}"`

**Comment by jahvi** [comment]
Thanks @davidalger you commented just before I added more info to the issue but that's exactly it.

**Comment by davidalger** [comment]
Thanks for reporting the issue! :) Once [the builds](https://github.com/davidalger/warden/actions/runs/778164289) complete, you should be able to resolve by running the following to pull the latest images and start things back up:

```
warden env pull && warden env up
```
