### ISSUE TITLE
redirect loop (M2 storeview not default)

### ISSUE THREAD

**Issue by maverickk89** [davidalger/warden#372]
Hello,
I used for months the classic system with docker-compose.yml for a project with Magento 2. When I tried to use warden instead of the system already mentioned I get a redirect loop (302) visiting a storeview different from default, visiting the default storeview website is fine. I would exclude a DB related problem because using the same DB with "docker-compose.yml and docker-compose up" I never got this problem.

**Comment by sprankhub** [comment]
Not 100% if this helps, but try to set `web/secure/offloader_header` to `X-Forwarded-Proto`.

**Comment by maverickk89** [comment]
@sprankhub already set to `X-Forwarded-Proto`. :(

**Comment by Skullsneeze** [comment]
Are you using store codes to switch store views, or is it based on domains? And if you are using multiple domains, have you set them up using [this guide](https://docs.warden.dev/configuration/multipledomains.html)?
