### ISSUE TITLE
I am having "maximum nesting" problem when xdebug a Magento 2

### ISSUE THREAD

**Issue by oreales** [davidalger/warden#376]
I am having an error when trying to xdebug a Magento 2 warden site. It is known that sometimes 250 nesting level for xdebug it is not enough. How can I change xdebug.max_nesting_level in my environment? Is there any way of replacing xdebug config with my custom config?

**Comment by sprankhub** [comment]
I'd say this should be possible to configure with a custom config file as described in the [docs](https://docs.warden.dev/environments/customizing.html#php-specific-customizations).
