### ISSUE TITLE
php-fpm on M1 - can we use laradock/php-fpm image?

### ISSUE THREAD

**Issue by stefanskotte** [davidalger/warden#379]
I was wondering if it's possible to swap out php-fpm for the one they made on the laradock.io project, it appears to be a native arm64 image ?

Not sure how to do it though, or that there is customizations to the one that warden uses.

Any help appreciated.

**Comment by stefanskotte** [comment]
I figured out it was not based on Centos 8, so it will not work directly.. Oh well.

**Comment by davidalger** [comment]
@stefanskotte It's not generally speaking going to be possible to drop in a generic PHP image from another project, although a CentOS 8 base isn't required for compatibility, there is a good deal of stuff specific to Warden features embedded in the php-fpm images in the Dockerfile and the entrypoint scripts:

https://github.com/davidalger/warden/blob/develop/images/php-fpm/Dockerfile
https://github.com/davidalger/warden/blob/develop/images/php-fpm/context/docker-entrypoint

In theory what you're asking would be possible, but you would likely have to build an image using the other as a base, and making sure everything is there.

Now that Docker Desktop for Apple Silicon is GA (as of April 15th) I do plan to make the time to get builds setup so these can run natively, but I don't have a timeline for that as this is a side project and I have competing personal priorities atm.

**Comment by stefanskotte** [comment]
OK, thanks for the info - I will see if I get some time to tinker with a m1 variation, maybe that can save you some time integrating it later.

**Comment by stefanskotte** [comment]
@davidalger I just did a quick build on arm64 yesterday - it doesn't appear to be a huge issue getting it to work. I will continue when I have more time and update the issue here :)

**Comment by MagePsycho** [comment]
@stefanskotte Can you please share how did you use the custom `php-fpm` image?

**Comment by stefanskotte** [comment]
> @stefanskotte Can you please share how did you use the custom `php-fpm` image?

I only swapped the arch and did a docker rebuild of the original image that David created. I don't think I made any changes to the packages it contains - however let me check this on my other (m1) machine.

**Comment by julienanquetil** [comment]
@stefanskotte : If you get some details on the php-fpm image on m1 i'll take it. Thanks

**Comment by stefanskotte** [comment]
I will try to dig into it this weekend - sorry, been swamped here with work.

**Comment by julienanquetil** [comment]
Many thanks :)
