### ISSUE TITLE
CRLF line endings in .env file break warden env up

### ISSUE THREAD

**Issue by navarr** [davidalger/warden#380]
```
navarr@Bulbasaur:/e/PhpstormProjects/dependency-annotation$ warden env up
" specified.ronment type "laravel
```

System: Ubuntu WSL2 on Windows 10, Docker Desktop setup for WSL2.

.env:
```env
WARDEN_ENV_NAME=depends
WARDEN_ENV_TYPE=laravel
WARDEN_WEB_ROOT=/

TRAEFIK_DOMAIN=depends.test
TRAEFIK_SUBDOMAIN=app

WARDEN_PHP=1
PHP_VERSION=7.4

COMPOSER_VERSION=2
WARDEN_COMPOSER_DIR=./.composer
```

Not really sure what's going on here.  I have another environment with WARDEN_ENV_TYPE=laravel that launches fine:

```env
WARDEN_ENV_NAME=grakkus
WARDEN_ENV_TYPE=laravel
WARDEN_WEB_ROOT=/webroot

TRAEFIK_DOMAIN=grakkus.test
TRAEFIK_SUBDOMAIN=app

WARDEN_NGINX=1
WARDEN_DB=1
WARDEN_REDIS=1
WARDEN_PHP=1

PHP_VERSION=7.4

MYSQL_DATABASE=grakkus
MYSQL_ROOT_PASSWORD=grakkus
MYSQL_USER=grakkus
MYSQL_PASSWORD=grakkus
```

Warden 0.11.0:

```
navarr@Bulbasaur:/opt/warden$ git status
HEAD detached at 0.11.0
nothing to commit, working tree clean
```

**Comment by tdgroot** [comment]
@navarr this problem looks familiar to me. I encountered this issue when I was generating .env files incorrectly. What was incorrect at that time was that I quoted every value by default. Warden didn't seem to like that.

You config file looks fine to me. Perhaps the file has Windows line endings?

**Comment by navarr** [comment]
@tdgroot You got it in one, thanks!

Working every day in Mac, it stopped being something I'd even consider having to think about.  Appreciate it!

**Comment by davidalger** [comment]
I can easily reproduce this by changing line endings from LF to CRLF:
```
davidalger@silver-bullet:~/Sites/m2sandbox (develop) $ cat .env | perl -pe "s/\n$/\r\n/g" > .env-cr; mv .env-cr .env
davidalger@silver-bullet:~/Sites/m2sandbox (develop *) $ warden env ps
" specified.ronment type "magento2
```

Would it be worth it perhaps to update `loadEnvConfig` (https://github.com/davidalger/warden/blob/develop/utils/env.sh#L34-L57) to instead do the following:

```
    eval "$(cat "${WARDEN_ENV_PATH}/.env" | sed 's/\r$//g' | grep "^WARDEN_")"
    eval "$(cat "${WARDEN_ENV_PATH}/.env" | sed 's/\r$//g' | grep "^TRAEFIK_")"
    eval "$(cat "${WARDEN_ENV_PATH}/.env" | sed 's/\r$//g' | grep "^PHP_")"
```

Sed removes the trailing '\n' when it parses for matching, hence the use of `\r$` to match the CRLF, removing the `\r` before grepping. Thoughts?

**Comment by navarr** [comment]
It'd certainly be a nice UX tweak to prevent issues like this that someone may not notice or think to look at
