### ISSUE TITLE
Can't Connect To DB Using SSH Tunnel

### ISSUE THREAD

**Issue by ryan-copeland** [davidalger/warden#387]
I am unable to setup a connection to the DB using the instructions in the docs:

https://docs.warden.dev/configuration/database.html#phpstorm

When adding the SSH tunnel I get the following error message:

Authentication failed.

See configuration for SSH tunnel below:

https://www.dropbox.com/s/l8zwq4ey2a2rno0/Screenshot%202021-06-08%20at%2016.53.40.png?dl=0

I've also tried table plus and am getting the same error message.

**Comment by tdgroot** [comment]
@ryan-copeland I have found the credentials to be incorrect when using DBeaver.

Here are the credentials I'm using to connect to the environment database:

**Host**: `your_environment_db_1`
**Username**: `magento`
**Password**: `magento`
**Database**: `magento`

**SSH Host**: `127.0.0.1`
**SSH Port**: `2222`
**SSH Username**: `user` (yes, literally `user`)
**SSH Private Key**: `~/.warden/tunnel/ssh_key`

**Comment by ryan-copeland** [comment]
@tdgroot - Thanks for providing that info. That all seems to be working well with the updated details.

**Comment by tdgroot** [comment]
@ryan-copeland You're welcome, glad to help!

**Comment by iranimij** [comment]
and the question is that why the documentation SSH host is something different "tunnel.warden.test"
https://docs.warden.dev/configuration/database.html#phpstorm

**Comment by navarr** [comment]
> and the question is that why the documentation SSH host is something different "tunnel.warden.test" https://docs.warden.dev/configuration/database.html#phpstorm

In most scenarios `tunnel.warden.test` should be pointing to 127.0.0.1
