### ISSUE TITLE
Guide to enable Xdebug on WSL system

### ISSUE THREAD

**Issue by vinayshah** [davidalger/warden#389]
Hello @davidalger 

The warden env is working just perfect with the brew setup and other configuration, quick easy and fast. Kudos to it.

I am struggling to enable and use Xdebug with PHPStorm, it would be great if you or any one other can help me with setting this up.

Thanks,

**Comment by Skullsneeze** [comment]
Have you checked [this configuration setup for PHPStorm](https://docs.warden.dev/configuration/xdebug.html#phpstorm)?
