### ISSUE TITLE
"Killed" during Updating dependencies

### ISSUE THREAD

**Issue by christian-walker** [davidalger/warden#39]
Hello,

I'm running into an issue on step 7. Whenever I run 
```
composer create-project --repository-url=https://repo.magento.com/ \
    magento/project-community-edition /tmp/exampleproject 2.3.x
```
Once it gets to `Updating dependencies (including require-dev)` it gets stuck for awhile and then says `Killed`

After doing some research, this looks like its due to the php memory limit needing to be increased.  Is there a way to do that so it can finish downloading the project?

**Comment by davidalger** [comment]
@christian-walker Please see the following note from the README. The `Killed` message is due to the process being killed by the Linux kernel:

> By default Docker Desktop assigns 2GB memory. This leads to extensive swapping, killed processed and extremely high CPU usage during some Magento actions, like for example running sampledata:deploy. It is recommended to assign at least 6GB RAM (unless your on a 8GB MBP, then go 4GB).

ref: https://github.com/davidalger/warden#recomended-additions

**Comment by christian-walker** [comment]
@davidalger ok thanks! That worked!

**Comment by shashidharg** [comment]
Hello Christian,
I have 8GB MBP, and increased the memory_limit to 4G, but still I am getting "**Killed**" when trying do a `$ composer update`. Tried to increase more too, but still this issue was not resolved. Please suggest what I should do

Regards,
Shashidhar.G
