### ISSUE TITLE
Warden delete bin/phar file after stop/start environment

### ISSUE THREAD

**Issue by igil-pk** [davidalger/warden#400]
I installed a n98-mage-run on my Magento2 containers and works well, the problem is when I stop and start the containers, the binaries files have gone. I tried to install it on different folders but the result it's the same. Does anyone have the same issue?

Steps to reproduce:
- download bin/phar files and put them on the bin global folder '/usr/local/bin' (I tried to put on other folders with the same result).
- stop and start containers (some times requires 2 or more restars)
- in my case. I follow this guide: https://github.com/netz98/n98-magerun2 

Regards.

**Comment by Lunaetic** [comment]
@igil-pk The default Magento 2 image that is included in a warden `Magento 2` environment type has n98-magerun2 aliased to `mr`; you should be able to just run magerun2 commands like: `mr c:f` without installing anything else.

**Comment by igil-pk** [comment]
Great ! I got it! 
 I didn't see anything related in the documentation.

 Thanks for the clarification!

**Comment by davidalger** [comment]
Worth noting that n98-magerun2 is installed at `/usr/local/bin/n98-magerun` in Magento 2 containers, and Magento 1 containers have the original v1 also installed at that location. So you can also simply use `n98-magerun` in addition to the `mr` shortcut, which largely exists for historical reasons.
