### ISSUE TITLE
PHP OCI8

### ISSUE THREAD

**Issue by franz177** [davidalger/warden#401]
Hi @davidalger

I would like to know if it would be possible to integrate OCI8 in Warden and how please.

**Comment by tdgroot** [comment]
@franz177 have you tried running `pecl install oci8` in the php-fpm container?

**Comment by franz177** [comment]
Hello @tdgroot,
I accessed the container with the warden shell command but the pecl command is not found. 
I also tried to install it but apt-get doesn't exist

Thanks in advance for the support

**Comment by tdgroot** [comment]
@franz177 pecl is not available in the container by default. You can install it using `sudo dnf install php-pear`.

**Comment by franz177** [comment]
I receive this error after executed pecl install oci8 

`Can't find PHP headers in /usr/include/php
The php-devel package is required for use of this command.
ERROR: 'phpize' failed`

**Comment by franz177** [comment]
@tdgroot I installed php-delev that resolved phpize error. Now i'm receving the follow error:

`configure: WARNING: OCI8 extension: ORACLE_HOME is not set, looking for default Oracle Instant Client instead
checking Oracle Instant Client directory... configure: error: Oracle Instant Client directory /usr/lib/oracle/.../client64/lib libraries not found. Try --with-oci8=instantclient,DIR
ERROR: '/tmp/pear/install/oci8/configure --with-php-config=/bin/php-config --with-oci8' failed`

**Comment by franz177** [comment]
Please note this official Docker Image:

[https://github.com/oracle/docker-images/tree/main/OracleInstantClient](url) 

Could it be added in the Warden configuration?

**Comment by tdgroot** [comment]
@franz177 apparently, the php-oci8 package is also available by the Remi repo: https://blog.remirepo.net/post/2020/05/18/Installation-of-Oracle-extensions-for-PHP.

Try installing it using `dnf install php-oci8`.

**Comment by franz177** [comment]
Hello @tdgroot,

I executed the following commands:

`sudo dnf install php-pear`
`sudo dnf install php-oci8`
`sudo dnf install libaio`
`sudo sudo rpm -i oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm.`

The oci_connect function returns an error from the Nginx Web server while it is working correctly from the CLI. 
This is the detail of the error in the Frontend: Fatal error: Uncaught Error: Call to undefined function oci_connect()

I look forward to hearing from you

**Comment by franz177** [comment]
Hi @tdgroot,

I resolved it. 

I added the follow instructions on `zz-config.ini: env[LD_LIBRARY_PATH]=/usr/lib/oracle/21/client64/lib clear_env = no`

Thanks for support
