### ISSUE TITLE
docker-compose 2 support

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#405]
I starting getting an issue:
![image](https://user-images.githubusercontent.com/1873745/126299504-9d2e0d72-4eea-4f81-be07-3ee773251d07.png)
![image](https://user-images.githubusercontent.com/1873745/126299639-77ecaae9-b0f2-4dc2-903b-4c3d921c3ee5.png)

Workaround - disable this flag: 
![image](https://user-images.githubusercontent.com/1873745/126299522-05e5ad78-baf8-4883-8636-a276d15808b1.png)

More info: https://docs.docker.com/compose/cli-command/

**Comment by davidalger** [comment]
Duplicate #394 

This is interesting. Based on the CLI output, looks like it's resulting from the call to `docker-compose -v` used in the version check.

Do you know if `docker-compose --version` works on experimental v2 or is it also broken?

**Comment by ihor-sviziev** [comment]
@davidalger it shows the following:
```bash
$ docker-compose --version
Docker Compose version v2.0.0-beta.6
```

So I think we can change it

**Comment by pocallaghan** [comment]
By sheer co-incidence, I just found this and edited my warden file to try `--version` about 5 mins before your post, it works for finding the version and your grep basically still works, but after doing so I got this: 

```pocallaghan@pete magento % warden env stop
WARN[0000] The NGINX_VERSION variable is not set. Defaulting to a blank string. 
WARN[0000] The XDEBUG_CONNECT_BACK_HOST variable is not set. Defaulting to a blank string. 
WARN[0000] The XDEBUG_CONNECT_BACK_HOST variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_DATABASE variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_USER variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_PASSWORD variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_DATABASE variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_USER variable is not set. Defaulting to a blank string. 
WARN[0000] The MYSQL_PASSWORD variable is not set. Defaulting to a blank string. 
```

**Comment by davidalger** [comment]
```
$ echo "Docker Compose version v2.0.0-beta.6" | grep -oE '[0-9\.]+' | head -n1
2.0.0
```
Yeah, the existing version parsing appears to work with that new format. So I'm going to push a PR to change that flag.

**Comment by ihor-sviziev** [comment]
@davidalger https://github.com/davidalger/warden/pull/406

**Comment by davidalger** [comment]
Thanks @ihor-sviziev beat me to it :) 

@pocallaghan Sounds like a bug in v2 to me. Surely I can't be the only one with default values specified in the yml:

```
- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
```

```
- XDEBUG_CONNECT_BACK_HOST=${XDEBUG_CONNECT_BACK_HOST:-''}
```
