### ISSUE TITLE
unknown shorthand flag: 'v' in -v

### ISSUE THREAD

**Issue by pcmerc** [davidalger/warden#407]
unknown shorthand flag: 'v' in -v occurs when executing warden commands after the most recent MacOSX docker desktop install.
Looking at the packages that Docker has chosen to deploy with this build, it would appear they are shipping a beta version of docker-compose - Docker Compose version v2.0.0-beta.6
Replacing that with a STABLE version corrects that issues as it appears warden using a -v option to check the version I assume & that option is no longer available.
Replacing that with the 1.29.x version corrects the issue, Docker introduced.

**Comment by davidalger** [comment]
Related #405
