### ISSUE TITLE
elasticsearch and db container continuously stopping one after another for Magento 2 setup (exited with code 137)

### ISSUE THREAD

**Issue by VivekShingala** [davidalger/warden#408]
Hi 

I have set up M2 with warden on my Mac. 

```
call_db_1 exited with code 137
call_elasticsearch_1 exited with code 137
```

Magento is running on 2.4.0.

**Comment by VivekShingala** [comment]
This only happens when the crons are set to run using the below command.

`bin/magento cron:install`

The site works fine when crons are disabled.

**Comment by ihor-sviziev** [comment]
@VivekShingala, why do you need to run the cron jobs on the local machine? :)

**Comment by VivekShingala** [comment]
Hi @ihor-sviziev 

I had to run it because it only worked when I run it using n98 command but the new crontab I set is never get scheduled using the crons. any idea? I also tried creating a custom group but cron is not scheduled.

`n98-magerun2.phar sys:cron:run cancelorder_cancel`

**Comment by ihor-sviziev** [comment]
@VivekShingala, I woule recommend you installing some UI for the cron jobs, it would be more informative why it's not running. There might be some failure, or different cron schedule, etc.

**Comment by VivekShingala** [comment]
Thanks @ihor-sviziev, I will check it

**Comment by davidalger** [comment]
If I recall correctly, exit code 137 from docker frequently means it was sig killed with an OOM error. If that's the case, you'd likely see an OOMKilled true in the state section of `docker inspect call_db_1`. Should this be the case, either do as @ihor-sviziev suggested and manually run the cron jobs, alternatively you'll need to give Docker Desktop more memory in preferences or find other unrelated containers to shutdown (if you have multiple environments running, for example)
