### ISSUE TITLE
Please add Option to route custom Ports to the php-fpm container (with SSL Certificate)

### ISSUE THREAD

**Issue by m4m-simon** [davidalger/warden#411]
For Frontend Development it would be very helpful to configure custom Ports.
For example for hot-reloading proxy-servers.

**Comment by lbajsarowicz** [comment]
Could you provide some example, because I'm not sure I understand your problem :(

**Comment by danslo** [comment]
This is already possible, if you are using browsersync or something similar:
.warden/warden-env.yml:
```
services:
  php-fpm:
    ports:
      - "4000:4000"
```

**Comment by m4m-simon** [comment]
Hey @lbajsarowicz and @danslo thank you for your participation.

I already tried to just routing the port in the `.warden/warden-env.yml` for the php-fpm service.

The Problem is for example with shopware 6, when i try to open the hot-proxy port in the browser, i get an "ERR_SSL_PROTOCOL_ERROR". As i understand the structure of the warden enviroment, the app domain is connected through and get ssl certificate by the traefik service. But if I connect to the port directly on the php-fpm container, no ssl certificate is signed. Is that right?

You can try this by installing shopware as described here: https://docs.warden.dev/environments/shopware.html
And start the hot-proxy with the command `./psh.phar storefront:hot-proxy` as described here: https://developer.shopware.com/docs/guides/plugins/themes/add-css-js-to-theme#using-the-hot-proxy-live-reload

**Comment by m4m-simon** [comment]
or do I need to connect through the nginx service somehow?
