### ISSUE TITLE
Installation results in older version (0.9.1)

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#417]
I installed the `warden` in my MacOS as
```
brew install davidalger/warden/warden
```
But it resulted in `0.9.1`.

But I can see from tags the current version is `0.12.0`

Is there a way to update?

**Comment by MagePsycho** [comment]
Is there a `self-update` like command?

**Comment by davidalger** [comment]
It's possible you had an old version of the tap present, as Homebrew shouldn't install old versions like that.

Given you've installed using `brew` you should be able to upgrade to the latest tagged release via the following:
```
brew upgrade warden
```

**Comment by MagePsycho** [comment]
@davidalger well noted! Thanks
