### ISSUE TITLE
After bin/magento application redirects to /index.php

### ISSUE THREAD

**Issue by torhoehn** [davidalger/warden#42]
I set up an Magento 2 environment via composer and it was working perfectly fine, but after running bin/magento setup:upgrade I got redirected to /index.php. Are there any experiences with this?

Before bin/magento setup:upgrade
<img width="1552" alt="Screenshot 2019-11-26 at 21 13 02" src="https://user-images.githubusercontent.com/1945725/69679133-aca07080-10a7-11ea-884d-59edaf37a4d4.png">

After  bin/magento setup:upgrade
<img width="1552" alt="Screenshot 2019-11-26 at 21 16 13" src="https://user-images.githubusercontent.com/1945725/69679141-b033f780-10a7-11ea-8198-f8b9c3d89718.png">

The only thing to make it work again was to run the bin/magento setup... again.

**Comment by davidalger** [comment]
Hi @torhoehn - I've also seen this. In every case though a simple `bin/magento cache:flush` fixed the issue. It stems I believe from Magento not having a Base URL set and caching a bad URL. Maybe try setting base URLs in `env.php` (examples of doing this can be found here: https://gist.github.com/davidalger/3101b61996af0010dcf9035b7db894e8#file-env-php-warden-php-L114-L150) or saving base URLs via the Magento admin? 

If you think this is something else, feel free to say so. Perhaps it would be good to amend the documented setup steps to include setting an explicit base URL to avoid this. 🤔
