### ISSUE TITLE
Execute custom commands on every `warden env up`

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#420]
I want to execute a certain set of commands on every `warden env up` command.
Is there a way to do it in `warden`?

**Comment by lbajsarowicz** [comment]
The easiest way is to prepare your own custom command - like `warden bootstrap` in the @davidalger 's template:
https://github.com/davidalger/warden-env-magento2/blob/develop/.warden/commands/bootstrap.cmd

**Comment by MagePsycho** [comment]
> The easiest way is to prepare your own custom command - like `warden bootstrap` in the @davidalger 's template:
> https://github.com/davidalger/warden-env-magento2/blob/develop/.warden/commands/bootstrap.cmd

But how this will be invoked with `warden ev up` command?

**Comment by ivan-veres** [comment]
executing `warden bootstrap`  invokes `warden  env up -d` https://github.com/davidalger/warden-env-magento2/blob/develop/.warden/commands/bootstrap.cmd#L162

So modifying or creating your command you can have before/after. Depends how you write it.

**Comment by MagePsycho** [comment]
@ivan-veres Thanks for pointing the `bootstrap` approach. Looks cool.
