### ISSUE TITLE
Environment variables are not set when using docker-compose V2

### ISSUE THREAD

**Issue by hanhpv** [davidalger/warden#423]
Today I'm trying to setup Magento 2 with Warden on a Mac, with latest Docker desktop installed. Got these messages when starting env services:

![Clipboard - September 12, 2021 10_28 AM](https://user-images.githubusercontent.com/5069672/133070258-5d989f91-08a4-4fea-ac1c-8951f08c1f8b.png)

It took me few hours to figure out the problem is latest Docker desktop is shipped with Compose V2 RC enabled by default:

![Clipboard - September 13, 2021 3_10 PM](https://user-images.githubusercontent.com/5069672/133070561-d12ef1d2-c249-4338-a9e9-7b5183ac556c.png)

I downgraded docker-compose to version 1.25.0 and it works well.

**Comment by hanhpv** [comment]
This is the setting to downgrade Compose in Docker Desktop.
![Clipboard - September 13, 2021 3_49 PM](https://user-images.githubusercontent.com/5069672/133071262-7008dc30-dc51-427c-9c28-7563a0a91be1.png)

**Comment by intray** [comment]
Amazing, I also solved the same problem when I downgraded docker-compose to version 1.29.2 .

**Comment by brendanfalkowski** [comment]
Just had the same issue on a Mac (just downloaded Docker fresh). Disabling that experimental feature worked.

**Comment by ihor-sviziev** [comment]
This issue isn’t reproducing anymore. More info https://github.com/davidalger/warden/pull/437#issuecomment-1002186894
I think we can close it
