### ISSUE TITLE
Container _php-fpm_1  Error on creating

### ISSUE THREAD

**Issue by joaotnlima** [davidalger/warden#429]
[+] Running 5/5
 ⠿ Container test_elasticsearch-hq_1  Created                                                                                             0.2s
 ⠿ Container test_db_1                Created                                                                                             0.2s
 ⠿ Container test_redis_1             Created                                                                                             0.2s
 ⠿ Container test_elasticsearch_1     Created                                                                                             0.2s
 ⠿ Container test_rabbitmq_1          Created                                                                                             0.2s
 ⠋ Container test_php-fpm_1           Creating                                                                                            0.0s
Error response from daemon: bad format for add-host: ":172.23.0.2"

**Comment by ytorbyk** [comment]
@joaotnlima Looks like the issue is because of docker-compose V2. 
Uncheck option in Settings -> Experimental Features -> Use Docker Compose V2 release candidate.
https://github.com/davidalger/warden/issues/423

**Comment by ihor-sviziev** [comment]
Duplicates #423.
I think it could be closed.
