### ISSUE TITLE
Importing DB via warden db import stalls

### ISSUE THREAD

**Issue by christian-walker** [davidalger/warden#43]
I see where you can run `warden db import test_db.sql magento` but when I run this it just stalls.  I've already verified and installed `pv`. I ended up just importing via Sequel Pro but would like to know if my syntax is correct for future reference. 

Thanks!

**Comment by rsisco** [comment]
The correct syntax is `warden db import < test_db.sql`. It will automatically use the `magento` database.

**Comment by davidalger** [comment]
@rsisco is correct (thanks for chiming in!) the import command specifically reads data from stdin (there is also `connect`; details in `warden db -h` output, it'll allow passing commands via `-e 'query;'` but doesn't work for loading sql files).

I typically use `pv` to pipe a database into it with progress indicator like so (hence the recommendation for `pv` as a useful addition; `cat` would work just as well minus the progress indicator):

```
$ pv /path/to/dump/magento_db-XXXXXXXX.sql.gz | gunzip -c | warden db import
28.4MiB 0:00:40 [ 441KiB/s] [==>                                 ] 13% ETA 0:04:06
```
