### ISSUE TITLE
How to add aliases in php-fpm shell?

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#430]
I would like to add some aliases on `php-fpm` shell, for example:
```
alias m2="./bin/magento"
```

I could add it `~/.bashrc` but it would be gone in re-build.

Is there a way we can add it via `.warden/warden-env.yml` somehow? or can we add the `m2` alias on warden level?

**Comment by tdgroot** [comment]
@MagePsycho you could add alias suggestions to the image, and otherwise you could add aliases to your host:
``` shell
alias m2="warden env-exec php-fpm bin/magento"
```

You could also write a bash function on your host which copies your preferred `.bash_profile` (or whatever) to the container before it executes `warden shell`.

**Comment by MagePsycho** [comment]
@tdgroot I have already created some aliases for `warden` commands. For example:

## Aliases
With aliases, you don't need to write full `warden` command.

| Category | Warden Command | Alias Command |
| ------- | -------------- | ------------ |
| Magento 2   | `warden shell -c "bin/magento <action>"`  | `wm2 <action>` |
| MageRun   | `warden shell -c "n98-magerun <action>"` | `wmr <action>` |
| Redis   | `warden redis <action>` | `wrd <action>` |
| Database  | `warden db <action>` | `wdb <action>` |
| Logs | `warden env logs --tail 0 -f nginx php-fpm php-debug`  | `wlg` |
| Shell (`php-fpm`) | `warden shell`  | `wsh` |
| Shell (`php-debug`) | `warden debug`  | `wdg` |
| Environment | `warden env <action>`  | `wenv <action>` |

Source - https://github.com/MagePsycho/magento2-warden-aliases

But I would like to add some aliases in the container itself.

**Comment by ihor-sviziev** [comment]
@davidalger, what do you think about adding these aliases to the warden itself?

**Comment by ihor-sviziev** [comment]
Let's keep it open
