### ISSUE TITLE
Magento site can't be reached after installation

### ISSUE THREAD

**Issue by guzasmod** [davidalger/warden#435]
Following [Magento 2 installation documentation](https://docs.warden.dev/environments/magento2.html) everything went smoothly without any problems but when trying to access project in browser I'm getting "This site can't be reached" error.

[app.magento2.test](https://app.magento2.test/)
[app.magento2.test/backend](https://app.magento2.test/backend/)
[rabbitmq.magento2.test](https://rabbitmq.magento2.test/)
[elasticsearch.magento2.test](https://elasticsearch.magento2.test/)

![image](https://user-images.githubusercontent.com/24250017/137603134-14d93725-84ac-4695-a444-996d20942bcf.png)

Docker containers:

![image](https://user-images.githubusercontent.com/24250017/137603153-0851d8ed-a7b4-4695-b91e-4e59511f4b53.png)

env.php settings:

![image](https://user-images.githubusercontent.com/24250017/137603239-5fdf1228-c446-41b7-a48b-902e8ef69bf0.png)

What could be the problem?

**Comment by guzasmod** [comment]
`host app.magento2.test` command returns

`Host app.magento2.test not found: 3(NXDOMAIN)`

I'm using Ubuntu 20.04

Installing Magento 2.4.3

**Comment by alinalexandru** [comment]
Configure the dns resolver. Use the systemd settings

https://docs.warden.dev/configuration/dns-resolver.html#systemd-resolved

**Comment by guzasmod** [comment]
It worked, thanks!

**Comment by VivekShingala** [comment]
Hi @alinalexandru 

Any idea on how to fix this in Mac? Getting the similar issue after recent Docker update.
#569
