### ISSUE TITLE
Selenium Instructions are Incorrect

### ISSUE THREAD

**Issue by navarr** [davidalger/warden#44]
The instructions listed for selenium (in the README) are incorrect.

The selenium host should be just `selenium` with the current Warden setup.  I would submit a PR but I cannot currently create screenshots of a VNC with SSH tunnel

**Comment by davidalger** [comment]
@lbajsarowicz Care to chime in here? At a glance, I'm thinking the screenshots were probably based on a connection which used the chome and selenium hub containers vs the standalone perhaps.

**Comment by lbajsarowicz** [comment]
@navarr You are right. I've created README based on the setup I had locally, but submitted with `selenium` only. You can actually update that README if you want to, or I'll do it soon.

Nice catch BTW!

**Comment by davidalger** [comment]
This should be resolved in PR #49
