### ISSUE TITLE
upgrading warden

### ISSUE THREAD

**Issue by emreakay** [davidalger/warden#442]
hi,

I have installed 0.9.1
i want to upgrade it to latest version

how can i do that?
 
Thanks.

**Comment by tdgroot** [comment]
What OS are you on? MacOS? Linux?

**Comment by emreakay** [comment]
im using Linux

**Comment by tdgroot** [comment]
Then you have probably installed Warden in `/opt/Warden`. If that's the case, run the following commands:
```
cd /opt/Warden
git pull
warden svc pull
warden svc up
```

**Comment by sprankhub** [comment]
Or via `brew` :)

In this case, run e.g. `brew update && brew upgrade && brew cleanup`.

**Comment by emreakay** [comment]
thanks @tdgroot and @sprankhub
