### ISSUE TITLE
Reset Portainer password

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#452]
Is there a way to reset the Portainer password in case if you forgot?
FYI, I am trying to access https://portainer.warden.test/

**Comment by navarr** [comment]
`warden down -v` and `warden up` (note: not `env`) might do it.  You'd also lose any mail in mailhog but I think that's it.

@davidalger can you confirm?

**Comment by MagePsycho** [comment]
> `warden down -v` and `warden up` (note: not `env`) might do it. You'd also lose any mail in mailhog but I think that's it.
> 
> @davidalger can you confirm?

Is it ?
```
warden svc down
warden svc up
```

**Comment by navarr** [comment]
> Is it ?
> 
> ```
> warden svc down
> warden svc up
> ```

Ah yeah, it is now

**Comment by MagePsycho** [comment]
> > Is it ?
> > ```
> > warden svc down
> > warden svc up
> > ```
> 
> Ah yeah, it is now

That did the trick. Yay!
