### ISSUE TITLE
Can't Upgrade Warden Via Brew

### ISSUE THREAD

**Issue by ryan-copeland** [davidalger/warden#453]
HI - I can see that a lot of updates have been applied to warden on the github repo but these don't seem to have been made available via brew. I currently have v0.9.1 but when I run `brew upgrade warden` it says that I am already running the latest version. 

Looking at the changelog the latest version is v0.12.0.

Is there a specific command that I need to run in order to pull the latest version?

**Comment by Lunaetic** [comment]
I just tried this locally, as I was also on `0.9.1`, and was updated to `0.12.0`

**Comment by ryan-copeland** [comment]
I am not seeing the same at my end. See below:

> ~ % brew upgrade warden
> Error: 
>   homebrew-core is a shallow clone.
>   homebrew-cask is a shallow clone.
> To `brew update`, first run:
> 
>   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
>   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
>
> This restriction has been made on GitHub's request because updating shallow
> clones is an extremely expensive operation due to the tree layout and traffic of
> Homebrew/homebrew-core and Homebrew/homebrew-cask. We don't do this for you
> automatically to avoid repeatedly performing an expensive unshallow operation in
> CI systems (which should instead be fixed to not use shallow clones). Sorry for
> the inconvenience!
> 
> Warning: davidalger/warden/warden 0.9.1 already installed

I wonder if the brew update error message has anything to do with it? I have tried to run the commands it says but it just hangs.

**Comment by ryan-copeland** [comment]
Update: The upgrade does work after you run those commands but they took a lot long than expected. :-D
