### ISSUE TITLE
Support for m1 chips

### ISSUE THREAD

**Issue by AlphaJanus** [davidalger/warden#454]
All images are not arm based. With magento always 404 error on m1 mac, no mater installing it on existing project, or new one.

**Comment by DavidLambauer** [comment]
+1

**Comment by hardyjohnson** [comment]
@AlphaJanus @DavidLambauer you might close this as it is duplicative and there is an existing milestone project tracking it:  https://github.com/davidalger/warden/milestone/28

**Comment by DavidLambauer** [comment]
+1

**Comment by AlphaJanus** [comment]
Sorry, haven't noticed it.
