### ISSUE TITLE
problem accessing to portainer

### ISSUE THREAD

**Issue by maverickk89** [davidalger/warden#457]
Hello,
accessing to portainer it asks for username and password, but I don't have/remember neither username and password as well.
Is there a way to reset them?

Thank you

![Istantanea_2021-12-01_17-29-04](https://user-images.githubusercontent.com/34450139/144273886-7c73fff8-81d2-44e3-8dd2-53f06fa9afc8.png)

**Comment by tdgroot** [comment]
Run the following commands:
```
warden env down -v
warden env up
```

Now you should be greeted again with the signup form of Portainer.

**Comment by maverickk89** [comment]
I tried down command but I didn't tried the -v option.
Thank you very much!
