### ISSUE TITLE
DB dump is not working

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#461]
Trying to dump the DB as
```
warden db dump | gzip > mydump.sql.gz
```
It gives an error
> mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

May I know the correct way of dumping the DB from the container?

**Comment by sprankhub** [comment]
Just wanted to confirm that your command works flawlessly in my case. Not sure why it does not work for you. Make sure you use the latest Warden version and make sure to update your images via `warden env pull && warden env up` (just in case).

**Comment by rbouma** [comment]
This is not a problem of warden this is a problem in user rights in mysql. You probably have a function or script in your database that is not created by the user 'magento' that warden initialize. Its either created as root or another user.

sometimes it happens we have a special price calculation function in the database thats not created as the current user then we got this error in the db if we want to see the function: ```-- This user does not have permission to view 'specialprice_calculation_0'``` This user can't dump this function, so thats the problem.

I don't know if you can dump the database with root

**Comment by rbouma** [comment]
@MagePsycho Please try to dump your database with this command: ```DB_CONTAINER=$(warden env ps -q db); docker exec $DB_CONTAINER /usr/bin/mysqldump -u root --password=magento magento > ~/path/to/database.sql``` It works for me
