### ISSUE TITLE
Visibility between two different containers

### ISSUE THREAD

**Issue by dudzio12** [davidalger/warden#465]
Hi!

Could you point me at the right direction?

I have Magento 2 project which is `app1`.

I have Symfony project which is `app2`.

Both `app1` and `app2` have API's, which I need to communicate with bidirectionally.

What's the best way to achieve that with a minimum config change?

**Comment by erfanimani** [comment]
I think as long as the port that they need to communicate over is mapped on the host, there shouldn't be any issues right?

**Comment by dudzio12** [comment]
Thanks for the tip @erfanimani. I'll test it later :)

**Comment by francesco-di-marcantonio** [comment]
i don't underestand what you mean for mapping. I would like to create a channel between  warden-m2  and a local  deploy of fastapi that is reachable on 127.0.0.1:8000 on host env. How can we make it visible to warden?
