### ISSUE TITLE
Easy Installation of vanilla Magento (w/wo sample data)

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#467]
Dear Warden users,

We have released the new version of "Simplistic Magento Installer" v0.1.3 which now supports `warden`:
https://github.com/MagePsycho/magento2-installer-bash-script

The installation of Magento on warden container is fairly simple:
```
cd /path/to/warden/m2/project
warden shell
```
After login to the container, you can download the script (as mentioned in the doc) and install Magento as
```
# With sample data
m2-installer --version=2.4.3 --install-sample-data --use-secure --base-url=app.<project>.test --db-host=<project>_db_1 --db-user=magento --db-pass=magento --db-name=magento --elasticsearch-host=<project>_elasticsearch_1 --use-redis-cache --redis-host=<project>_redis_1 --force

# Without sample data
m2-installer --version=2.4.3 --use-secure --base-url=app.<project>.test --db-host=<project>_db_1 --db-user=magento --db-pass=magento --db-name=magento --elasticsearch-host=<project>_elasticsearch_1 --use-redis-cache --redis-host=<project>_redis_1 --force
```
Hope you find this script useful.   
Let me know what you think of this script.

**Comment by ihor-sviziev** [comment]
Hi @MagePsycho,
Looks good! We might use environment variables to pass the base url, correct container names, etc. Can’t we?

**Comment by MagePsycho** [comment]
> Hi @MagePsycho, Looks good! We might use environment variables to pass the base url, correct container names, etc. Can’t we?
> 
> Also DB and Redis containers can be reached by just `db` and `redis` for a more straightforward example

That's a good idea.
And thanks for your suggestions on using the generic container names.
So based on it, the new command should look like this:

`m2-installer --version=2.4.3 --install-sample-data --install-for-warden`

**Comment by ihor-sviziev** [comment]
@MagePsycho, my suggestion was just updating instruction like thi:s 🙂
```
# With sample data
m2-installer --version=2.4.3 --install-sample-data --use-secure --base-url="app.$TRAEFIK_DOMAIN" --db-host=db --db-user=magento --db-pass=magento --db-name=magento --elasticsearch-host=elasticsearch --use-redis-cache --redis-host=redis --force

# Without sample data
m2-installer --version=2.4.3 --use-secure --base-url="app.$TRAEFIK_DOMAIN" --db-host=db --db-user=magento --db-pass=magento --db-name=magento --elasticsearch-host=elasticsearch --use-redis-cache --redis-host=redis --force

```

**Comment by MagePsycho** [comment]
> @MagePsycho, my suggestion was just updating instruction like this 🙂
> 
> ```
> # With sample data
> m2-installer --version=2.4.3 --install-sample-data --use-secure --base-url="app.$TRAEFIK_DOMAIN" --db-host=db --db-user=magento --db-pass=magento --db-name=magento --elasticsearch-host=elasticsearch --use-redis-cache --redis-host=redis --force
> 
> # Without sample data
> m2-installer --version=2.4.3 --use-secure --base-url="app.$TRAEFIK_DOMAIN" --db-host=db --db-user=magento --db-pass=magento --db-name=magento --elasticsearch-host=elasticsearch --use-redis-cache --redis-host=redis --force
> ```

Gotcha!
That's even simpler/easier.

**Comment by sprankhub** [comment]
@MagePsycho, since this is not a Warden issue, please close.
