### ISSUE TITLE
Composer breaks on every composer command

### ISSUE THREAD

**Issue by norgeindian** [davidalger/warden#468]
Since I ran `warden svc pull` and `warden env pull` a few days ago, I can not run any composer command inside the warden shell anymore.
No matter which command I try to run, I get the following error:

```
Fatal error: Uncaught TypeError: Argument 3 passed to Composer\Package\Locker::__construct() must be an instance of Composer\Repository\RepositoryManager, instance of Composer\Installer\InstallationManager given, called in phar:///usr/bin/composer/src/Composer/Factory.php on line 446 and defined in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php:54
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Factory.php(446): Composer\Package\Locker->__construct(Object(Composer\IO\ConsoleIO), Object(Composer\Json\JsonFile), Object(Composer\Installer\InstallationManager), '{\n    "name": "...', Object(Composer\Util\ProcessExecutor))
#1 phar:///usr/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false, '/var/www/html', true, false)
#2 phar:///usr/bin/composer/src/Composer/Console/Application.php(445): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, false, false)
#3 phar:///usr/bin/composer/src/Composer/Command/BaseCommand.php(65 in /var/www/html/vendor/composer/composer/src/Composer/Package/Locker.php on line 54
``` 
This happens on each Magento 2.4.3-p1 installation, and the only workaround I found so far is deleting the `vendor` folder.
Then  In can run `composer install` once, after that it is broken again.
Anyone facing the same issue?

**Comment by MagePsycho** [comment]
How did you install the Magento?

Have you tried installing Magento via this approach? - https://github.com/davidalger/warden/issues/467

**Comment by norgeindian** [comment]
We ran Magento now for a few months already in several warden environments.
It used to work without any issues, so I don't think the installation approach is the reason here.
But thanks, @MagePsycho

**Comment by sprankhub** [comment]
This is an issue with Composer < 2.2.3. Updating to 2.2.3 fixes the issue. See https://github.com/composer/composer/issues/10408.

**Comment by norgeindian** [comment]
@sprankhub , thanks for that finding, awesome.
@davidalger , what do we need to do to get the latest composer version inside the warden environments?
I just ran `warden env pull` and `warden env up --force-recreate`, but that did not help, I'm still on 2.2.2

**Comment by sprankhub** [comment]
https://twitter.com/SimonSprankel/status/1479420396520751104 :joy:

**Comment by davidalger** [comment]
@norgeindian The images have been rebuilt, so if you re-pull and update your environment, you should see Composer has been bumped from 2.2.2 -> 2.2.3 in the current images as of this morning.

**Comment by norgeindian** [comment]
@davidalger , great, thanks. Just tried it and it works fine. Then I can close this issue.
