### ISSUE TITLE
Expired Cert for warden.test

### ISSUE THREAD

**Issue by pocallaghan** [davidalger/warden#475]
Not 100% sure if this is a bug or something I missed during set-up but attempting to access the global services such as https://mailhog.warden.test is now warning me that the SSL certificate has expired. 

Is this supposed to self-renew in some fashion?

Not sure if I'm supposed to run `warden sign-certificate` or run `warden install` on a regular basis or something else.

**Comment by Lunaetic** [comment]
@pocallaghan You should be able to run `warden sign-certificate warden.test` to update the global services certificate.

**Comment by davidalger** [comment]
> Is this supposed to self-renew in some fashion?

There is no auto-renewal of certificates. @Lunaetic is correct, you should re-run `sign-certificate` to reissue the cert.

**Comment by Lunaetic** [comment]
@pocallaghan Were you able to resolve your issue with `warden sign-certificate`?
