### ISSUE TITLE
 Cant Run Composer Install -- Possible SSL Cert Issue?

### ISSUE THREAD

**Issue by fpurser** [davidalger/warden#477]
Have an older Magento 2 site I'm trying to run inside a 7.1 shell. When I run `composer install` I get: 

```
 SSL operation failed with code 1. OpenSSL Error messages:                                                                   
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed                                           
  Failed to enable crypto                                                                                                     
  failed to open stream: operation failed      
```

`composer diagnose` shows no error. 

Thank you,

**Comment by erfanimani** [comment]
What composer version are you running?

**Comment by fpurser** [comment]
> What composer version are you running?

I have Composer 2.1.12 is installed on my machine. 

Inside my shell (where I run composer install) Im using Composer 1 as defined in my env. 

`WARDEN_ENV_NAME=m2project
WARDEN_ENV_TYPE=magento2
WARDEN_WEB_ROOT=/
TRAEFIK_DOMAIN=m2project.test
TRAEFIK_SUBDOMAIN=app
WARDEN_DB=1
WARDEN_ELASTICSEARCH=1
WARDEN_VARNISH=1
WARDEN_RABBITMQ=1
WARDEN_REDIS=1
ELASTICSEARCH_VERSION=6.8
MARIADB_VERSION=10.3
NODE_VERSION=10
COMPOSER_VERSION=1
PHP_VERSION=7.1
PHP_XDEBUG_3=0
RABBITMQ_VERSION=3.8
REDIS_VERSION=5.0
VARNISH_VERSION=6.0
WARDEN_SYNC_IGNORE=

WARDEN_ALLURE=0
WARDEN_SELENIUM=0
WARDEN_SELENIUM_DEBUG=0
WARDEN_BLACKFIRE=0
WARDEN_SPLIT_SALES=0
WARDEN_SPLIT_CHECKOUT=0
WARDEN_TEST_DB=0
WARDEN_MAGEPACK=0
BLACKFIRE_CLIENT_ID=
BLACKFIRE_CLIENT_TOKEN=
BLACKFIRE_SERVER_ID=
BLACKFIRE_SERVER_TOKEN=`

**Comment by erfanimani** [comment]
Hmm not sure. It simply looks like an outdated image. PHP 7.1 hasn't been supported since late 2019.

**Comment by fpurser** [comment]
> Hmm not sure. It simply looks like an outdated image. PHP 7.1 hasn't been supported since late 2019.

That's what I think too -- I just don't know how to update the image.

**Comment by sprankhub** [comment]
To update the images, simply run `warden env pull && warden env up`.
