### ISSUE TITLE
[ARM64] Mutagen sync start randomly fails

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/warden#486]
While trying to run `warden env up` on my MacBook Pro with Apple Silicon processor, usually first time it fails with the following error:
```
 ⠿ Container myproject-db-1                Started                                                                                                                                                            0.4s
Installing agent...                                                             
Error: unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to install agent: unable to invoke agent installation: exit status 1
ERROR: Command `mutagen sync create -c "${MUTAGEN_SYNC_FILE}" --label "warden-sync=${WARDEN_ENV_NAME}" --ignore "${WARDEN_SYNC_IGNORE:-}" "${WARDEN_ENV_PATH}${WARDEN_WEB_ROOT:-}" "docker://$(warden env ps -q php-fpm)/var/www/html"` at /opt/homebrew/Cellar/warden/0.12.0/commands/sync.cmd:45 failed with exit code 1
```

Just re-running it few times usually helps and command executes successfully, but it's annoying.

From the debug, I see it fails on the `warden sync start` command

**Comment by HeRovaZy** [comment]
I had the same issue, but no matter how many times I retry `warden env up` my environment won't come up.
Fixed it by upgrading the Docker Disk Image size, maybe this will help you too?

**Comment by ihor-sviziev** [comment]
Looks like the issue was caused by using debian-based image that had a bug - incorrect home folder for www-data user. After applying the following patch https://github.com/drpayyne/warden-multi-arch/pull/17
 - the issue is gone. I'm closing this issue.
