### ISSUE TITLE
Elastic Search Server Setting - Magento 2

### ISSUE THREAD

**Issue by christian-walker** [davidalger/warden#50]
When loading a site locally that uses elastic search I receive the error `
```
1 exception(s):
Exception #0 (Elasticsearch\Common\Exceptions\NoNodesAvailableException): No alive nodes found in your cluster

Exception #0 (Elasticsearch\Common\Exceptions\NoNodesAvailableException): No alive nodes found in your cluster
```

On [Magento StackExchange](https://magento.stackexchange.com/questions/208822/reindex-command-error-no-alive-nodes-found-in-your-cluster) someone suggests to change the server setting to localhost.  For warden, what would be the localhost setting?

**Comment by christian-walker** [comment]
I ran `warden env config` to get the Elasticsearch configuration settings and added those to the admin area in Magento under **Stores -> Settings -> Configuration -> Catalog -> Catalog - > Catalog Search**

Closing issue.

**Comment by davidalger** [comment]
Glad you got it working @christian-walker! 👍
