### ISSUE TITLE
Magento 2.4.4 & updated system reqs / docker image versions

### ISSUE THREAD

**Issue by kraiglarson** [davidalger/warden#502]
As of Tues, March 29, 2022, the new version of Adobe Commerce 2.4.4 / Magento 2.4.4 is open for testing purposes. (general availability coming on April 12) Reqs here: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

I haven't done any testing yet, but the new Magento 2.4.4 would seem to require newer Docker container image versions (newer than what is available at https://hub.docker.com/u/wardenenv). Magento 2.4.4 would seem to require:

- Elasticsearch 7.17 or OpenSearch 1.2 (only Elasticsearch up to 7.13 is available)
- Rabbitmq 3.9 (only up to 3.8 available)
- Reddis 6.2 (only up to 6.0 available)
- Varnish 7.0 (only up to 6.5 available)

Can new Docker containers be made available?

Thanks, Kraig

<img width="429" alt="image" src="https://user-images.githubusercontent.com/25674561/160645322-ce65d31b-d5d8-4d65-9859-e41409fb38d1.png">

**Comment by davidalger** [comment]
@kraiglarson Images for each of these should be available now, as they were added in #505 and #495
