### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#503]
Everything was working fine but suddenly, I am having this issue when I try to connect to the web or run any command via shell:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/1205071/160908855-196e2513-1d84-4d57-aab4-457d73e80e73.png">

Not sure if it's related to the new version of Docker.

**Comment by mshererSO** [comment]
@MagePsycho just as a sanity check have you confirmed that your mysql container is running? You can check via portainer or the cli (whichever you find more comfortable).

In the past I've seen this issue occur when running out of resources and the container will exit. Other not as applicable thoughts that come to mind is that your env.php is not symlinked anymore (assuming you symlink env.php.warden.php -> env.php).

**Comment by dudzio12** [comment]
Hi!

You should not use this hostname inside your container. Use magento as host instead :) User and password is also magento, same as db name ;)

**Comment by mshererSO** [comment]
@MagePsycho you can check if the symlink exists by doing the following:
1. warden shell - Access your php-fpm container
2. cd app/etc/ - Change directories to your app/etc/ directory (optional step you could always modify step 3 to check)
3. ls -lah - Review the list of files and make sure that you see something like "env.php <- env.php.warden.php" in your file list


Also I agree with @dudzio12.

**Comment by MagePsycho** [comment]
Hi @mshererSO @dudzio12 
It got it working after I shut down the svc and running it again.
