### ISSUE TITLE
Add image for Elasticsearch 7.10.1

### ISSUE THREAD

**Issue by nwcasebolt** [davidalger/warden#509]
Magento 2.4.3 [supports Elasticsearch 7.10](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html). This image is not currently available in this fork. Creating this issue to track the PR.

**Comment by navarr** [comment]
ElasticSearch 7.10 is available: https://hub.docker.com/layers/elasticsearch/wardenenv/elasticsearch/7.10/images/sha256-2c936027e50369bfa7990dfc49c6dee5e0643ba4ff79e1adfb4a439e95036803?context=explore

You'd need to use "7.10" in your `.env` file as opposed to "7.10.1"

**Comment by nwcasebolt** [comment]
Thanks, closing
