### ISSUE TITLE
M2 Setup:upgrade keep executing db_schema every time

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [davidalger/warden#51]
Not sure if this is only in my environment but any time I run  `mr setup:upgrade` keep executing db_schema every time and this is causing fatal error because it tried creating the foreign key again. 
Eg. 

```
<table name="custom_table" resource="default" engine="innodb" comment="custom Table">
        <column xsi:type="int" name="ct_id" padding="10" unsigned="false" nullable="false" identity="true"
                comment="ID"/>
        <column xsi:type="int" name="customer_id" padding="10" unsigned="true" nullable="true" identity="false"
                comment="Customer Id"/>
        <column xsi:type="varchar" name="phone_number" nullable="false" length="255" comment="Phone Number"/>
        <column xsi:type="varchar" name="contact_pref" nullable="false" length="255" comment="Contact Preference"/>
        <column xsi:type="varchar" name="verification_token" nullable="false" length="255"
                comment="Verification Token"/>
        
        <constraint xsi:type="primary" referenceId="PRIMARY">
            <column name="ct_id"/>
        </constraint>

 <constraint xsi:type="foreign" referenceId="custom_table_CUSTOMER_ID_CUSTOMER_ENTITY_ENTITY_ID"
                    table="custom_table"
                    column="customer_id" referenceTable="customer_entity" referenceColumn="entity_id"
                    onDelete="CASCADE"/>
</table>
```

And this yields 

`SQLSTATE[HY000]: General error: 1826 Duplicate FOREIGN KEY constraint name 'mvp_dev_dec/modulegroup_custom_table_CUSTOMER_ID_CUSTOMER_ENTITY_ENTITY_ID', query was: ALTER TABLE ....`

The same code just works fine from direct ubuntu dev environment.

**Comment by navarr** [comment]
Did you generate your whitelist after running a setup:upgrade with db schema?

Your db schema whitelist file must be kept up to date or it will try to regenerate your constraints

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html#create-whitelist

**Comment by Elamurugan-Nallathambi** [comment]
@navarr That was the issue, now its working ok. Though I wonder why this wasn't an issue with AWS RDS Aurora DB.

**Comment by davidalger** [comment]
@Elamurugan-Nallathambi As to why you encountered the issue here but not there, I'm not sure I can say, but since this is clearly a Magento application issue (and it seems you've solved the underlying issue) I'm going to go ahead and close this out. Cheers!
