### ISSUE TITLE
pub/media folder already exists

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#516]
I have noticed that in Mac, the `pub/media` folder already exists and cannot be deleted.
But in Ubuntu, that folder is not present by default while creating a warden environment.

What might be the issue with Mac?

**Comment by davidalger** [comment]
This is a difference due to how volumes are handled on Darwin hosts. On Linux, everything in `/var/www/html` is mounted into the container. On Mac `/var/www/html` is a docker volume synchronized with the host via Mutagen, and `/var/www/html/pub/media` is mounted from the host.
