### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#518]
> Your connection is not private
> Attackers might be trying to steal your information from app.mage244.test (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
> NET::ERR_CERT_AUTHORITY_INVALID

Every time I click on the URL, I get "Your connection is not private" and have to click "Proceed to xxx (unsafe)" link.
FYI, I am using

- Ubuntu v20.04
- Chrome v99

And already allowed self-signed certificate with
```
chrome://flags/#allow-insecure-localhost
```
Let me know how to avoid this annoying issue.

**Comment by tdgroot** [comment]
What seems wrong with the issued certificate? Does the common name match with the domain? Is it expired? Or is the Warden CA expired?

**Comment by MagePsycho** [comment]
@tdgroot 
I signed the certificate with
```
warden sign-certificate mage244.test
```

When I check on the browser it says "Certificate is not valid"
![Certificate Error](https://user-images.githubusercontent.com/1205071/164174488-2db5d5fd-ce28-43b7-84fd-415e322a6e1f.png)

**Comment by tdgroot** [comment]
Please try to answer my questions, it will probably lead you the answer.

**Comment by sprankhub** [comment]
You probably want to check out https://docs.warden.dev/installing.html?highlight=certificate#trusted-ca-root-certificate.

**Comment by MagePsycho** [comment]
> What seems wrong with the issued certificate? Does the common name match with the domain? Is it expired? Or is the Warden CA expired?

Does the common name match with the domain?
> Yes, `mage244.test` is the main domain.

Is it expired?
> No. It says: Expires On	Thursday, April 20, 2023 at 11:17:55 AM

Or is the Warden CA expired?
> Not sure how to validate/check this?

**Comment by MagePsycho** [comment]
> You probably want to check out https://docs.warden.dev/installing.html?highlight=certificate#trusted-ca-root-certificate.

When I tried to import the certificate from Chrome, it says
> Certificate Import Error
> The Private Key for this Client Certificate is missing or invalid

**Comment by davidalger** [comment]
@MagePsycho The error message mentioning a 'Client Certificate' when attempting to import the CA root certificate seems to indicate you are likely attempting to import as a client certificate instead of importing on the "Authorities" tab in the settings interface.

**Comment by MagePsycho** [comment]
@davidalger My bad. Now I am able to import the certificate.

But still, I have the same issue 
![image](https://user-images.githubusercontent.com/1205071/164383578-04e1bd91-b0bf-4082-ad72-8ec861b8a297.png)
