### ISSUE TITLE
rsync: command not found in Magento2 environment 

### ISSUE THREAD

**Issue by mirkocesaro** [davidalger/warden#52]
Following the README file to have a magento2 env set, inside the PHP container, after downloaded Magento2 on `/tmp/exampleproject` folder, there is a problem on rsync.

```
www-data@php-fpm:08:16 AM:/var/www/html$ rsync -a /tmp/exampleproject/ /var/www/html/
bash: rsync: command not found
```

**Comment by navarr** [comment]
Assuming your /var/www/html only contains a pub/media folder, you can work around this with:

```bash
mv /tmp/exampleproject/pub/media/* pub/media/
rm -rf /tmp/exampleproject/pub/media
mv /tmp/exampleproject/pub/* pub/
rm -rf /tmp/exampleproject/pub
mv /tmp/exampleproject/* .
rm -rf /tmp/exampleproject/
```

**Comment by davidalger** [comment]
@mirkocesaro Thank you for reporting this issue. It seems rsync was pulled from the upstream centos:7 base image the FPM image used by Warden is built upon.

I've re-added rsync to the FPM images Warden uses and CI has built and pushed them to Docker Hub. You should be all set after pulling the updated images and re-creating containers:

```
warden env pull
warden env up -d
```

Rsync version installed is 3.1.2:
```
$ warden shell -c 'rsync --version'
rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```
