### ISSUE TITLE
Warden Env up no such service: php-fpm

### ISSUE THREAD

**Issue by powerburn** [davidalger/warden#524]
I was trying to run `warden env up`  on my local Mac book pro on Mojave (10.4.6) and getting the following error.  
It also showed that it successfully created php debug and php-fpm

```
$ warden env up
Connecting traefik to maste_default network
Connecting tunnel to maste_default network
Connecting mailhog to maste_default network
[+] Running 9/9
 ⠿ Container maste-redis-1             Running                                                                                                                        0.0s
 ⠿ Container maste-elasticsearch-hq-1  Running                                                                                                                        0.0s
 ⠿ Container maste-elasticsearch-1     Running                                                                                                                        0.0s
 ⠿ Container maste-db-1                Running                                                                                                                        0.0s
 ⠿ Container maste-rabbitmq-1          Running                                                                                                                        0.0s
 ⠿ Container maste-php-fpm-1           Running                                                                                                                        0.0s
 ⠿ Container maste-php-debug-1         Running                                                                                                                        0.0s
 ⠿ Container maste-nginx-1             Running                                                                                                                        0.0s
 ⠿ Container maste-varnish-1           Running                                                                                                                        0.0s
no such service: php-fpm



```

```
$ warden shell
service "php-fpm" is not running container #1
```
How do I ensure that the service php-fpm runs?

**Comment by mautz-et-tong** [comment]
+1 same here on the latest warden, latest Monterey on M1

**Comment by mautz-et-tong** [comment]
Solved:
I had the following config:
WARDEN_ENV_NAME=customer.tld
TRAEFIK_DOMAIN=customer.tld.test

Switched it to:
WARDEN_ENV_NAME=customer
TRAEFIK_DOMAIN=customer.test

System is no up and running after `warden env up`

So, apparently, no extra dots like adding tld schema is allowed in both env vars. We should wether update the documentation, add some troubleshooting or declare this as an issue and solve this.

@davidalger your choice?

**Comment by poojapawar12** [comment]
I am getting this error on running warden shell command service
**"php-fpm" is not running**

I am trying to setup maento 2.4.6 -p2 using warden setup 

can anyone help me with this

**Comment by poojapawar12** [comment]
@navarr  Please check I am sharing you result of above command  **warden env logs php-fpm**
![image](https://github.com/wardenenv/warden/assets/133887565/42e1c10d-58a7-48c5-a5bd-ac1e7008f22a)

php-fpm-1  | sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr='mailhog:1025'"
php-fpm-1  |   installing : node-v12.22.12
php-fpm-1  |        mkdir : /usr/local/n/versions/node/12.22.12
php-fpm-1  |        fetch : https://nodejs.org/dist/v12.22.12/node-v12.22.12-linux-x64.tar.gz
php-fpm-1  |      copying : node/12.22.12
php-fpm-1  |    installed : v12.22.12 to /usr/local/bin/node
php-fpm-1  |       active : v16.20.2 at /bin/node
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: fpm is running, pid 1
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: ready to handle connections
php-fpm-1  | [19-Apr-2024 14:03:48] NOTICE: systemd monitor interval set to 10000ms
php-fpm-1  | sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr='mailhog:1025'"
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: fpm is running, pid 1
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: ready to handle connections
php-fpm-1  | [20-Apr-2024 11:31:21] NOTICE: systemd monitor interval set to 10000ms
