### ISSUE TITLE
How to integrate with MailHog in order to check emails?

### ISSUE THREAD

**Issue by MagePsycho** [davidalger/warden#552]
My warden environment is working fine. I can access installed Magento and MailHog (https://mailhog.warden.test/)
But when I place an order or register as a customer, I don't see any emails in MailHog.

Is there any configuration for MailHog with Warden?

**Comment by werfu** [comment]
If you look at MailHog documentation, https://github.com/mailhog/MailHog, you can see the SMTP service is listening by default on 1025. The port is also exposed through docker. So your container should be able to connect to the SMTP server to send email using mailhog:1025

**Comment by navarr** [comment]
Following up on Maxime's message, the automatic configuration of PHP's sendmail should result in the `mail` command calls ending up in Mailhog.

Assuming that works, but Magento doesn't - there are a few different things that you should look for:

* Ensure you don't have an SMTP module or other type of mail module or capture module installed
* Ensure that you don't have email queuing turned on (or, run `bin/magento cron:run` manually a few times)

**Comment by dudzio12** [comment]
@MagePsycho I've just tried your script on my env and it worked as expected.

```
sendmail_from => no value => no value
sendmail_path => /usr/local/bin/mhsendmail --smtp-addr='mailhog:1025' => /usr/local/bin/mhsendmail --smtp-addr='mailhog:1025'
Path to sendmail => /usr/local/bin/mhsendmail --smtp-addr='mailhog:1025'
```

**Comment by werfu** [comment]
@MagePsycho if you run a `docker ps` command, do you see a mailhog container running?

**Comment by davidalger** [comment]
Based on the reference to `184.168.221.27` the issue here is `mailhog` is being resolved to `mailhog.net` likely as a result of a search domain being present in `resolvconf` More on this here: https://github.com/davidalger/warden/issues/415#issuecomment-921825274

**Comment by christian-walker** [comment]
@MagePsycho / @werfu @navarr  were you guys ever able to get mailhog emails to work?
