### ISSUE TITLE
Mutagen configuration does not exist for environment type "magento1"

### ISSUE THREAD

**Issue by talesh** [davidalger/warden#56]
**Replication steps:**
1. Create a new Warden environment (warden env-init premigrate magento1)
2. Sign the certificate, spin up the containers (warden env up -d)
3. Start Mutagen sync (warden sync start)

**Expected result:** 
Mutagen to start and files to be synching

**Observed result:**
Error 'Mutagen configuration does not exist for environment type "magento1"' 

I think the problem is that a .toml file is missing for Mutagen, but I can't find the Magento 2 one to figure out where to make a version for Magento 1.

**Comment by davidalger** [comment]
@talesh The `magento1` environment currently doesn't use Mutagen to sync files as I've personally not seen a performance issue such as is encountered with M2 when using a delegated docker volume mounted from the host, although I do admittedly always use redis for sessions and cache so I wouldn't put it beyond the realm of possibility that performance may suffer in a docker.

Have you seen an issue with performance which would indicate it'd be good to setup Mutagen sync for M1 environments or an issue where files simply did not show up in the container?

**Comment by talesh** [comment]
I moved my configuration back to my iMac and I realized that yes indeed, m1 speeds are fast without mutagen on more modern hardware. This PR was unneeded. You can reject it.

**Comment by davidalger** [comment]
Got it, thanks. Do let me know if you experience consistent perf issues running M1 in here and you think Mutagen could solve it!

**Comment by davidalger** [comment]
Quick-note here: Warden 0.7.0 will include a Mutagen configuration for M1 per #97
