### ISSUE TITLE
Setup base environment for Symfony

### ISSUE THREAD

**Issue by lbajsarowicz** [davidalger/warden#61]
In my opinion that would be great to have the possibility of running Symfony-based projects using Warden.

There are multiple projects that would be supported then:
- https://sylius.com/
- https://github.com/pimcore/pimcore
- https://github.com/ergonode

And huge amount of microservices working alongside with Magento

**Comment by davidalger** [comment]
Would love to see this! It would require two things:

a) Adding an appropriate nginx configuration file for Symfony apps to the nginx image similar as to what was added for Laravel here: https://github.com/davidalger/docker-images-warden/commit/b7215c0ce8138de69293a2a3619d718c13532307


b) Setting up at minimum a `symfony.base.yml` and `symfony.darwin.yml` in the `environments` directory similar to the ones added on #60 for supporting Laravel

**Comment by davidalger** [comment]
Added via #146 in Warden 0.5.0
