### ISSUE TITLE
Support Live Reload routing natively on Magento 2 environment

### ISSUE THREAD

**Issue by davidalger** [davidalger/warden#62]
Magento 2 can be rather simply configured to serve the Live Reload script by including the following bit in the `env.php` file and running `bin/magento app:config:import`:

```
    'system' => [
        'default' => [
            'design' => [
                'footer' => [
                    'absolute_footer' => '
                        <script id="__lr_script__">//<![CDATA[
                            document.write("<script src=\'/livereload.js?port=443\'/>");
                        //]]></script>
                    '
                ]
            ],
        ],
    ],
```

Routing requests to this has required using per-project configuration in `.warden/warden-env.yml` to label the php-fpm container as required to serve the Live Reload JS file and process Web Socket requests when `grunt watch` is running.

In the upcoming Warden 0.2.0 release Live Reload should require nothing more than adding the script tag to the env.php file or including it via design configuration in the admin.

## Example documentation on how to leverage Live Reload:

This project uses the core bundled Grunt workflow. A Gruntfile and package.json are already included. We are ascribing to server-side compilation, in conjunction with the Grunt watch task, so that changes can be applied more rapidly during development.

To get started, run:

```
warden shell
grunt clean
grunt exec:<theme_name>
grunt less:<theme_name>
```

Thereafter, a single command should be needed for daily development:

```
grunt watch
```

Note: Grunt should be used within the `php-fpm` container only.

LiveReload is also used to persist changes to your compiled CSS. When you run the watch task, a LiveReload server will be started on port 35729 within the `php-fpm` container and Traefik will take care of proxying the JavaScript tag and WebSocket requests to this listener. This project's `env.php` used for local development injects the LiveReload JavaScript tag necessary for WebSocket communication via app:config:import.

**Comment by zaximus84** [comment]
I encountered a JS issue today that turned out to be the result of the script tag being added for livereload.js. The browser wasn't properly parsing the self-closing tag, so it saw the following script tag's content as being inside of the livereload.js tag.

It was fixed by replacing the self-closing tag with a proper closing tag:
document.write("<script src=\'/livereload.js?port=443\'></script>");

**Comment by davidalger** [comment]
@zaximus84 Thanks for the note. That is likely why @erikhansen encountered an issue and suggested a change which is now in the template and docs page on the subject:
* https://docs.warden.dev/configuration/livereload.html
* https://github.com/davidalger/warden-env-magento2/blob/develop/webroot/app/etc/env.php.init.php#L23-L25

It would be good to reference those if encountering issues in the future. I'll update the above description to correct the bad JS bit as well. Cheers!
