### ISSUE TITLE
BUG: `extra_hosts` in docker-compose does not react on `additional domains`

### ISSUE THREAD

**Issue by lbajsarowicz** [davidalger/warden#72]
https://github.com/davidalger/warden/blob/59ac9baf6b1262952a55bad784330efd28be5e0a/environments/magento2.base.yml#L40-L41

Does not reflect the situation when Developer runs his own hosts using Traefik Additional Domains: https://docs.warden.dev/configuration/multipledomains.html

**Comment by davidalger** [comment]
Quick-note: the referenced documentation needs to be updated to reflect upcoming support for any sub-domain of the TRAEFIK_DOMAIN to route to Nginx/Varnish by default.

I'm open to suggestions, but I'm currently unsure of how to set things up so (inside the container) all sub-domains will resolve without adding something like dnsmasq to each environment.

**Comment by davidalger** [comment]
I have added a note to the documentation and an example of using `extra_hosts` to configure `/etc/hosts` entries within FPM containers and am marking this as closed. Currently no wheels are moving that would support using dnsmasq for DNS resolution within the containers, as would be needed for wildcard sub-domains to be magically resolvable.
