### ISSUE TITLE
DB Export Syntax

### ISSUE THREAD

**Issue by christian-walker** [davidalger/warden#73]
Is there a way to export dbs using warden shell?

**Comment by davidalger** [comment]
The following should work since mariadb container images include the mysqldump CLI util:
```
warden env exec db mysqldump ...
```

`mysqldump` also exists within the shell available via `warden shell` and would be easily used to dump a database.

**Comment by mrtuvn** [comment]
@davidalger current i can't export db inside container use warden shell

Tried command below 
warden shell
=> mysqldump -u magento -p magento > backup.sql

Result
mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)" when trying to connect

**Comment by davidalger** [comment]
@mrtuvn When connecting to MySQL from within the `php-fpm` container you need to specify a hostname since MySQL is running in a different container. Try this instead:

```
mysqldump -h db -u magento -p magento > backup.sql
```

**Comment by mrtuvn** [comment]
ok thanks u i miss that. I think we can update that part in document
