### ISSUE TITLE
Consider Adding Ubuntu Alternatives

### ISSUE THREAD

**Issue by ryantfowler** [davidalger/warden#8]
First, thanks for the time put towards this tooling. Next, the current php containers are based on Centos, which isn't as prevalent as it once was. Currently, most servers are based on Ubuntu, and even Magento Cloud is based on Debian. What are your thoughts @davidalger on offering up alternative containers?

Thanks

**Comment by davidalger** [comment]
@ryantfowler I'll just say, without going into too much detail that although I disagree with popularity of an OS being a good reason for choice of base image flavor, I do appreciate the suggestion. Personally though I don't have the time to maintain and support a second set of images as the edge cases would simply be too many to deal with given how different EL and Debian flavors can be at times, even if I could manage creating them will full feature parity. I'd rather pour my energy into improving things withing a single stream of development. You are most certainly free however to build base images using an Ubuntu base if you'd rather use that as a base, and then define your container layout via `.warden/warden-env.yml` and related files within the project.

Most of my ops experience is in working with RHEL and related EL derivatives such as CentOS, which is certainly a big part of why I chose it. Given that I've built and maintained dozens of M2 production systems based on EL, my existing knowledge base and most my Ansible tooling (like the roles up here on Github) are weighted heavily towards EL, and the combination of packages and choice of underlying configuration has lent itself to highly performant, scalable, and stable production systems. So EL is likely going to be my starting point for some time to come, especially seeing as how the big players like AWS and Google are both behind EL systems (Amazon Linux itself is actually a CentOS derivative as well, and the only OS with which you can use certain high-end features on AWS infrastructure).

**Comment by ryantfowler** [comment]
@davidalger Thank you for the feedback and rationale behind your decision to use CentOS. I see your points and respect them. Thanks
