### ISSUE TITLE
Databases declared by an environment type should be created in `db` one container

### ISSUE THREAD

**Issue by davidalger** [davidalger/warden#88]
This relates to #20 and doing this opens door to supporting having an integration test database readily available. This would also remove the separate database _instances_ that WARDEN_SPLIT_SALES and WARDEN_SPLIT_CHECKOUT create and replace them with additional databases within a single db container.

**Comment by navarr** [comment]
If done, the users for these databases shouldn't have access to the other ones, so that environments where the databases are on different servers are properly emulated
