### ISSUE TITLE
Problem with connect to selenium via Remmina

### ISSUE THREAD

**Issue by mrtuvn** [davidalger/warden#93]
I try to connect but get connecting.. forever
Every set and up already. The only problem i can't connect to selenium chrome for test mftf

Already read docs about this and follow but not get any luck
https://docs.warden.dev/configuration/mftf.html

How to solve this! I have no idea to get debug on this

Used ubuntu 18.04 + with warden 0.2.2
SELENIUM_HOST=selenium-hub
BROWSER=chrome
![Screenshot from 2020-02-13 01-34-01](https://user-images.githubusercontent.com/1908873/74365577-f1af8580-4e00-11ea-9b21-ffb0ead27ac7.png)
![Screenshot from 2020-02-13 01-34-03](https://user-images.githubusercontent.com/1908873/74365587-f5dba300-4e00-11ea-81f5-2a7634f3b005.png)

**Comment by lbajsarowicz** [comment]
Could you submit screenshot of your Remmina connection details?

**Comment by mrtuvn** [comment]
@lbajsarowicz hi i have just uploaded screenshot

**Comment by lbajsarowicz** [comment]
You haven't provided the Server name in `basic` tab:
![image](https://user-images.githubusercontent.com/1639941/74365899-3e7a6880-4dcf-11ea-8c35-66bca1968d44.png)

Instead of `magento2` you should put the value of `WARDEN_ENV_NAME` with latest Warden.

**Comment by mrtuvn** [comment]
@lbajsarowicz tried like your screenshot but not get any luck. Same results

**Comment by mrtuvn** [comment]
@lbajsarowicz @davidalger 
![Screenshot from 2020-02-13 22-35-07](https://user-images.githubusercontent.com/1908873/74450758-32ff6e00-4eb1-11ea-8359-003d682e61e5.png)

**Comment by lbajsarowicz** [comment]
Let me verify Documentation, as from `0.2.0` warden needs to have DEBUG setting on, to run Debug Docker image. Example:
```env
WARDEN_SELENIUM=1
WARDEN_SELENIUM_DEBUG=1
```

**Comment by davidalger** [comment]
Closing this issue for now due to inactivity.
